- id: 'shri-ram-stuti'
  type: 'leaf'
  paginated: false
  meta:
    hi:
      title: 'श्री राम स्तुति'
      subtitle: 'श्री रामचन्द्र कृपालु भजुमन'
      image: 'images/shri-ram-stuti-cover-4x3.jpg'
      description: |-
        श्रीरामचंद्र कृपालु भज मन अथवा राम स्तुति गोस्वामी तुलसीदास द्वारा रचित १६वीं शताब्दी का एक भजन है । इसमें श्रीराम प्रभु के अदभुत गुण एवं शौर्य का वर्णन है । मनुष्य के मन को नियंत्रित करनेवाली ये यह स्तुति संस्कृतमय अवधी में है ।
    en:
      title: 'Shri Ram Stuti'
      subtitle: 'Śrī Rāmacandra Kṛpālu Bhajumana'
      image: 'images/shri-ram-stuti-cover-4x3.jpg'
      description: |-
        Shri Shri Ram Stuti (Ramachandra Kripalu) is an aarti, written by Gosvāmī Tulasīdāsa. It was written in the sixteenth century, in a mix of Sanskrit and Awadhi languages. The prayer glorifies Śrī Rāma and his characteristics.
- id: 'om-jai-jagdish-hare'
  type: 'leaf'
  paginated: false
  meta:
    hi:
      title: 'विष्णु आरती'
      subtitle: 'ॐ जय जगदीश हरे'
      image: 'images/vishnu-shodasa-nama-stotram-cover-4x3.jpg'
      description: ''
    en:
      title: 'Vishnu Aarti'
      subtitle: 'Oṃ Jaya Jagadīśa Hare'
      image: 'images/vishnu-shodasa-nama-stotram-cover-4x3.jpg'
      description: ''
- id: 'om-jai-shiv-omkara'
  type: 'leaf'
  paginated: false
  meta:
    hi:
      title: 'शिव आरती'
      subtitle: 'ॐ जय शिव ओंकारा'
      image: 'images/shiv-chalisa-cover-4x3.jpg'
      description: ''
    en:
      title: 'Shiv Aarti'
      subtitle: 'Oṃ Jaya Śiva Oṃkārā'
      image: 'images/shiv-chalisa-cover-4x3.jpg'
      description: ''
