- id: '1'
  type: 'leaf'
  paginated: true
  meta:
    hi:
      title: 'भाग - १'
      subtitle: ''
      image: ''
      description: 'मङ्गलाचरण'
    en:
      title: 'Part - 1'
      subtitle: ''
      image: ''
      description: 'Invocations'
- id: '2'
  type: 'leaf'
  paginated: true
  meta:
    hi:
      title: 'भाग - २'
      subtitle: ''
      image: ''
      description: 'जयन्त की कुटिलता और फल प्राप्ति'
    en:
      title: 'Part - 2'
      subtitle: ''
      image: ''
      description: 'Jayanta''s mischief and punishment'
- id: '3'
  type: 'leaf'
  paginated: true
  meta:
    hi:
      title: 'भाग - ३'
      subtitle: ''
      image: ''
      description: 'अत्रि-मिलन एवं स्तुति'
    en:
      title: 'Part - 3'
      subtitle: ''
      image: ''
      description: 'Meeting with the sage Atri and his hymn of praise to Śrī Rāma'
- id: '4'
  type: 'leaf'
  paginated: true
  meta:
    hi:
      title: 'भाग - ४'
      subtitle: ''
      image: ''
      description: 'श्रीसीता-अनसूया-मिलन और श्रीसीताजी को अनसूयाजी का पतिव्रत धर्म कहना'
    en:
      title: 'Part - 4'
      subtitle: ''
      image: ''
      description: 'Sītā''s meeting with Anasūyā (Atri''s wife) and the latter''s discourse on the duties of a devoted wife'
- id: '5'
  type: 'leaf'
  paginated: true
  meta:
    hi:
      title: 'भाग - ५'
      subtitle: ''
      image: ''
      description: 'श्रीरामजी का आगे प्रस्थान, विराध-वध और शरभङ्ग-प्रसङ्ग'
    en:
      title: 'Part - 5'
      subtitle: ''
      image: ''
      description: 'Śrī Rāma proceeds further and kill Virādha; the episode of the sage Śarabhaṅga'
- id: '6'
  type: 'leaf'
  paginated: true
  meta:
    hi:
      title: 'भाग - ६'
      subtitle: ''
      image: ''
      description: 'राक्षस-वध की प्रतिज्ञा करना'
    en:
      title: 'Part - 6'
      subtitle: ''
      image: ''
      description: 'Śrī Rāma takes a vow to kill the demons'
- id: '7'
  type: 'leaf'
  paginated: true
  meta:
    hi:
      title: 'भाग - ७'
      subtitle: ''
      image: ''
      description: 'सुतीक्ष्णजी का प्रेम, अगस्त्य-मिलन, अगस्त्य-संवाद, राम का दण्डकवन-प्रवेश और जटायु-मिलन, पञ्चवटी-निवास और श्रीराम-लक्ष्मण-संवाद'
    en:
      title: 'Part - 7'
      subtitle: ''
      image: ''
      description: 'Sutīkṣṇa''s love and Śrī Rāma''s meeting with the sage Agastya; dialogue with Agastya; Śrī Rāma''s entry into the Daṇḍaka forest and His meeting with Jaṭāyu'
- id: '8'
  type: 'leaf'
  paginated: true
  meta:
    hi:
      title: 'भाग - ८'
      subtitle: ''
      image: ''
      description: 'शूर्पणखा की कथा, शूर्पणखा का खर-दूषण के पास जाना और खर-दूषणादि का वध'
    en:
      title: 'Part - 8'
      subtitle: ''
      image: ''
      description: 'The story of Śūrpaṇakhā; her approaching Khara, Dūṣaṇa and Triśirā for redress and their subsequent death at Śrī Rāma''s hands'
- id: '9'
  type: 'leaf'
  paginated: true
  meta:
    hi:
      title: 'भाग - ९'
      subtitle: ''
      image: ''
      description: 'शूर्पणखा का रावण के निकट जाना, श्रीसीताजी का अग्नि-प्रवेश और माया-सीता'
    en:
      title: 'Part - 9'
      subtitle: ''
      image: ''
      description: 'Śūrpaṇakhā approaches Rāvaṇa; Sītā enters into the fire leaving Her shadow behind'
- id: '10'
  type: 'leaf'
  paginated: true
  meta:
    hi:
      title: 'भाग - १०'
      subtitle: ''
      image: ''
      description: 'मारीच प्रसङ्ग और स्वर्णमृग रूप में मारीच का मारा जाना'
    en:
      title: 'Part - 10'
      subtitle: ''
      image: ''
      description: 'The episode of Mārīca and how he was killed in the form of a gold deer'
- id: '11'
  type: 'leaf'
  paginated: true
  meta:
    hi:
      title: 'भाग - ११'
      subtitle: ''
      image: ''
      description: 'श्रीसीता हरण और श्रीसीता-विलाप'
    en:
      title: 'Part - 11'
      subtitle: ''
      image: ''
      description: 'Sītā''s abduction and Her wail'
- id: '12'
  type: 'leaf'
  paginated: true
  meta:
    hi:
      title: 'भाग - १२'
      subtitle: ''
      image: ''
      description: 'जटायु-रावण युद्ध'
    en:
      title: 'Part - 12'
      subtitle: ''
      image: ''
      description: 'The combat of Jaṭāyu with Rāvaṇa'
- id: '13'
  type: 'leaf'
  paginated: true
  meta:
    hi:
      title: 'भाग - १३'
      subtitle: ''
      image: ''
      description: 'श्रीरामजी का विलाप, जटायु का प्रसङ्ग, कबन्ध-उद्धार'
    en:
      title: 'Part - 13'
      subtitle: ''
      image: ''
      description: 'Śrī Rāma''s lament; His meeting with Jaṭāyu'
- id: '14'
  type: 'leaf'
  paginated: true
  meta:
    hi:
      title: 'भाग - १४'
      subtitle: ''
      image: ''
      description: 'शबरी पर कृपा, नवधा भक्ति-उपदेश और पम्पासर की ओर प्रस्थान'
    en:
      title: 'Part - 14'
      subtitle: ''
      image: ''
      description: 'Grace on Śabarī; a discourse on the nine forms of Devotion and departure for the Pampā lake'
- id: '15'
  type: 'leaf'
  paginated: true
  meta:
    hi:
      title: 'भाग - १५'
      subtitle: ''
      image: ''
      description: 'नारद-राम-संवाद'
    en:
      title: 'Part - 15'
      subtitle: ''
      image: ''
      description: 'A description of the spring; Nārada''s meeting with Śrī Rāma'
- id: '16'
  type: 'leaf'
  paginated: true
  meta:
    hi:
      title: 'भाग - १६'
      subtitle: ''
      image: ''
      description: 'संतों के लक्षण और सत्सङ्ग-भजन के लिये प्रेरणा'
    en:
      title: 'Part - 16'
      subtitle: ''
      image: ''
      description: 'The glory of hearing the praises of Śrī Rāma and an exhortation to cultivate fellowship with saints and practise adoration'
