- id: 'books'
  type: 'tree'
  paginated: false
  meta:
    hi:
      title: 'शास्त्र'
      subtitle: ''
      image: ''
      description: ''
    en:
      title: 'Books'
      subtitle: ''
      image: ''
      description: ''
- id: 'stotra'
  type: 'tree'
  paginated: false
  meta:
    hi:
      title: 'स्तोत्रं'
      subtitle: ''
      image: ''
      description: ''
    en:
      title: 'Stotra (Hymns)'
      subtitle: ''
      image: ''
      description: ''
- id: 'chalisa'
  type: 'tree'
  paginated: false
  meta:
    hi:
      title: 'चालीसा'
      subtitle: ''
      image: ''
      description: ''
    en:
      title: 'Chalisa (Poetry)'
      subtitle: ''
      image: ''
      description: ''
- id: 'mantra'
  type: 'tree'
  paginated: false
  meta:
    hi:
      title: 'मंत्र'
      subtitle: ''
      image: ''
      description: ''
    en:
      title: 'Mantra'
      subtitle: ''
      image: ''
      description: ''