- id: 'bhagavad-gita'
  type: 'tree'
  paginated: false
  meta:
    hi:
      title: 'श्रीमद्भगवद्गीता - यथारूप'
      subtitle: 'ए.सी. भक्तिवेदांत स्वामी प्रभुपाद'
      image: 'images/bhagavad-gita-cover-4x3.jpg'
      description: |-
        यह एक हिंदू धर्मग्रंथ है जिसमें ७०० श्लोकों की रचना अर्जुन और भगवान् कृष्ण के बीच संवाद के रूप में की गई है, यह संस्कृत महाकाव्य महाभारत की एक उपकथा के रूप में प्राप्त है । महाभारत में वर्तमान कलियुग तक की घटनाओं का विवरण मिलता है । इसी युग के प्रारम्भ में आज से लगभग ५,००० वर्ष पूर्व भगवान् श्रीकृष्ण ने अपने मित्र तथा भक्त अर्जुन को भगवद्गीता का उपदेश दिया था ।
    en:
      title: 'Shrimad Bhagavad Gita - As It Is'
      subtitle: 'A.C. Bhaktivendanta Swami Prabhupada'
      image: 'images/bhagavad-gita-cover-4x3.jpg'
      description: |-
        Bhagavad-gītā originally appears as an episode in the Mahābhārata, the epic Sanskrit history of the ancient world. The Mahābhārata tells of events leading up to the present Age of Kali. It was at the beginning of this age, some fifty centuries ago, that Lord Kṛṣṇa spoke Bhagavad-gītā to His friend and devotee Arjuna.
- id: 'ramcharitmanas'
  type: 'tree'
  paginated: false
  meta:
    hi:
      title: 'श्रीरामचरितमानस (तुलसी रामायण)'
      subtitle: 'गोस्वामी तुलसीदास'
      image: 'images/ramcharitmanas-cover-4x3.jpg'
      description: |-
        रामचरितमानस अवधी भाषा में गोस्वामी तुलसीदास द्वारा १६वीं सदी में रचित प्रसिद्ध ग्रन्थ है । इस ग्रन्थ को अवधी साहित्य (हिंदी साहित्य) की एक महान कृति माना जाता है । इसे सामान्यतः 'तुलसी रामायण' या 'तुलसीकृत रामायण' भी कहा जाता है । गोस्वामी जी ने रामचरित का अनुपम शैली में दोहों, चौपाइयों, सोरठों तथा छंद का आश्रय लेकर वर्णन किया है ।
    en:
      title: 'Shri Ramcharitmanas (Tulsi Ramayana)'
      subtitle: 'Goswami Tulsidas'
      image: 'images/ramcharitmanas-cover-4x3.jpg'
      description: |-
        Shri Ramcharitmanas (Śrī Rāmacaritamānasa), is an epic poem in Awadhi language, composed by the 16th-century Indian bhakti poet Tulsidas (c. 1532–1623). The word Ramcharitmanas literally means *Lake of the deeds of Rama*.
- id: 'chanakya-neeti'
  type: 'tree'
  paginated: false
  meta:
    hi:
      title: 'चाणक्य नीति'
      subtitle: ''
      image: 'images/chanakya-neeti-cover-4x3.jpg'
      description: |-
        चाणक्य नीति एक सर्वाधिक लोकप्रिय व पढ़ी जाने वाली चाणक्य द्वारा लिखी गई रचना है । इसमें उन्होंने सभी शास्त्रों का सार, जीवन के मूल्य सूत्रों के रूप में संस्कृत दोहों व चौपाइयों की शैली में प्रस्तुत किए हैं । इसे पढ़कर एक आम आदमी जीवन में सफलता, उचित व अनुचित, नैतिक या अनैतिक, धर्म या अधर्म, बुद्धिमानी या मूर्खता, लाभदायक या हानिकारक, अच्छा या बुरा, उपयोगी या अनुपयोगी की पहचान कर सकता है ।