- id: '1'
  type: leaf
  paginated: true
  meta:
    hi:
      title: 'अध्याय ८ - श्लोक १'
      subtitle: ''
      image: ''
      description: |-
        जो लोग संसार में केवल धन की इच्छा करते हैं, वे अधम अर्थात नीच कोटि के हैं । मध्यम श्रेणी के लोग धन और सम्मान दोनों की इच्छा करते हैं जबकि उत्तम कोटि के मनुष्यों को केवल आदर-सम्मान ही चाहिए होता है ।
    en:
      title: 'Chapter 8 - Verse 1'
      subtitle: ''
      image: ''
      description: |-
        Low class men desire wealth; middle class men both wealth and respect; but the noble, honour only; hence honour is the noble man's true wealth.
- id: '2'
  type: leaf
  paginated: true
  meta:
    hi:
      title: 'अध्याय ८ - श्लोक २'
      subtitle: ''
      image: ''
      description: |-
        गन्ना, पानी, दूध, कंदमूल फल, पान तथा दवाइयों का सेवन करने के बाद भी स्नान आदि और धर्म कार्य किए जा सकते हैं ।
    en:
      title: 'Chapter 8 - Verse 2'
      subtitle: ''
      image: ''
      description: |-
        After consuming sugarcane juice, milk, roots, betel leaves, fruits & medicine, one should take bath, give charity & perform other acts.
- id: '3'
  type: leaf
  paginated: true
  meta:
    hi:
      title: 'अध्याय ८ - श्लोक ३'
      subtitle: ''
      image: ''
      description: |-
        दीपक अंधकार को खाता है और उससे काजल की उत्पत्ति होती है । इसी प्रकार मनुष्य जैसा अन्न खाता है, वैसी ही उसकी संतान उत्पन्न होती है ।
    en:
      title: 'Chapter 8 - Verse 3'
      subtitle: ''
      image: ''
      description: |-
        The lamp eats up the darkness and therefore it produces lamp black; in the same way according to the nature of our diet (sattva, rajas, or tamas) we produce offspring in similar quality.
- id: '4'
  type: leaf
  paginated: true
  meta:
    hi:
      title: 'अध्याय ८ - श्लोक ४'
      subtitle: ''
      image: ''
      description: |-
        बुद्धिमान या अच्छे गुणों से युक्त मनुष्य को ही धन दो, गुणहीनों को धन मत दो । समुद्र का खारा पानी बादल के मीठे पानी से मिलकर मीठा हो जाता है और इस संसार में रहने वाले सभी जड़-चेतन, चर और अचर जीवों को जीवन देकर फिर समुद्र में मिल जाता है । विद्वान् लोग जो तत्त्व को जानने वाले है उन्होंने कहा है की मास खाने वाले चांडालो से हजार गुना नीच है । इसलिए ऐसे आदमी से नीच कोई नहीं ।
    en:
      title: 'Chapter 8 - Verse 4'
      subtitle: ''
      image: ''
      description: |-
        O wise man! Give your wealth only to the worthy and never to others. The water of the sea received by the clouds is always sweet. The rain water enlivens all living beings of the earth both movable (insects, animals, humans, etc.) and immovable (plants, trees, etc.), and then returns to the ocean it value multiplied a million fold. The wise who discern the essence of things have declared that the yavana (meat eater) is equal in baseness to a thousand candalas the lowest class), and hence a yavana is the basest of men; indeed there is no one more base.
- id: '5'
  type: leaf
  paginated: true
  meta:
    hi:
      title: 'अध्याय ८ - श्लोक ५'
      subtitle: ''
      image: ''
      description: |-
        तत्त्व को जानने वाले विद्वानों ने यह कहा है कि हजारों चाण्डालों के समान एक यवन अर्थात म्लेच्छ- धर्मविरोधी होता है । इससे बढ़कर कोई दूसरा नीच नहीं होता ।
    en:
      title: 'Chapter 8 - Verse 5'
      subtitle: ''
      image: ''
      description: |-
        After having rubbed oil on the body, after encountering the smoke from a funeral pyre, after sexual intercourse, and after being shaved, one remains a Cāṇḍāla until he bathes.
- id: '6'
  type: leaf
  paginated: true
  meta:
    hi:
      title: 'अध्याय ८ - श्लोक ६'
      subtitle: ''
      image: ''
      description: |-
        तेल की मालिश करने के बाद, चिता के धुएं के स्पर्श करने के बाद, स्त्री से संभोग करने के बाद और हजामत आदि करवाने के बाद मनुष्य जब तक स्नान नहीं कर लेता, तब तक वह चाण्डाल अर्थात् अशुद्ध होता है ।
    en:
      title: 'Chapter 8 - Verse 6'
      subtitle: ''
      image: ''
      description: |-
        Water is the medicine for indigestion; it is invigorating when the food that is eaten is well digested; it is like nectar when drunk in the middle of a dinner; and it is like poison when taken at the end of a meal.
- id: '7'
  type: leaf
  paginated: true
  meta:
    hi:
      title: 'अध्याय ८ - श्लोक ७'
      subtitle: ''
      image: ''
      description: |-
        अपच की स्थिति में जल पीना औषधि का काम देता है और भोजन के पच जाने पर जल पीने से शरीर का बल बढ़ता है, भोजन के बीच में जल पीना अमृत के समान है, परंतु भोजन के अंत में जल का सेवन विष के समान हानिकारक होता है ।
    en:
      title: 'Chapter 8 - Verse 7'
      subtitle: ''
      image: ''
      description: |-
        Knowledge is lost without putting it into practice; a man is lost due to ignorance; an army is lost without a commander; and a woman is lost without a husband.
- id: '8'
  type: leaf
  paginated: true
  meta:
    hi:
      title: 'अध्याय ८ - श्लोक ८'
      subtitle: ''
      image: ''
      description: |-
        आचरण के बिना ज्ञान व्यर्थ है । अज्ञान से मनुष्य नष्ट हो जाता है । सेनापति के अभाव में सेना नष्ट हो जाती है और पति से रहित स्त्रियां भी नष्ट हो जाती हैं ।
    en:
      title: 'Chapter 8 - Verse 8'
      subtitle: ''
      image: ''
      description: |-
        A man who encounters the following three is unfortunate; the death of his wife in his old age, the entrusting of money into the hands of relatives, and depending upon others for food.
- id: '9'
  type: leaf
  paginated: true
  meta:
    hi:
      title: 'अध्याय ८ - श्लोक ९'
      subtitle: ''
      image: ''
      description: |-
        वृद्धावस्था में पत्नी का देहान्त हो जाना, धन अथवा संपत्ति का भाई-बन्धुओं के हाथ में चले जाना और भोजन के लिए दूसरों पर आश्रित रहना, यह तीनों बातें मनुष्य के लिए मृत्यु समान दुखदायी हैं ।
    en:
      title: 'Chapter 8 - Verse 9'
      subtitle: ''
      image: ''
      description: |-
        Death of a wife in old age, wealth or property gone in the hands of brothers and relatives and being dependent on others for food, these three things are as painful as death for a man.
- id: '10'
  type: leaf
  paginated: true
  meta:
    hi:
      title: 'अध्याय ८ - श्लोक १०'
      subtitle: ''
      image: ''
      description: |-
        अग्निहोत्र आदि कर्मों के बिना वेदों का अध्ययन व्यर्थ है तथा दान-दक्षिणा के बिना यज्ञ आदि कर्म निष्फल होते हैं । श्रद्धा और भक्ति के बिना किसी भी कार्य में सफलता प्राप्त नहीं होती अर्थात मनुष्य की भावना ही उसके विचार, उसकी सब सिद्धियों और सफलता का कारण मानी गई है ।
    en:
      title: 'Chapter 8 - Verse 10'
      subtitle: ''
      image: ''
      description: |-
        Chanting of the Vedas without making ritualistic sacrifices to the Supreme Lord through the medium of Agni, and sacrifices not followed by bountiful gifts are futile. Perfection can be achieved only through devotion (to the Supreme Lord) for devotion is the basis of all success.
- id: '11'
  type: leaf
  paginated: true
  meta:
    hi:
      title: 'अध्याय ८ - श्लोक ११'
      subtitle: ''
      image: ''
      description: |-
        लकड़ी, पत्थर अथवा धातु की मूर्ति में प्रभु की भावना और श्रद्धा रखकर उसकी पूजा की जाएगी, तो सिद्धि अवश्य प्राप्त होती है । प्रभु इस भक्त पर अवश्य प्रसन्न होते हैं ।
    en:
      title: 'Chapter 8 - Verse 11'
      subtitle: ''
      image: ''
      description: |-
        If Supreme Lord is worshiped in an idol of wood, stone or metal with the devotion and faith, then accomplishment is definitely achieved. The Lord must be pleased with the devotee.
- id: '12'
  type: leaf
  paginated: true
  meta:
    hi:
      title: 'अध्याय ८ - श्लोक १२'
      subtitle: ''
      image: ''
      description: |-
        देवता अथवा परमेश्वर, काठ अथवा पत्थर की मूर्ति में नहीं हैं । परमेश्वर तो मनुष्य की भावना में विद्यमान रहते हैं अर्थात जहां मनुष्य भावना द्वारा उसकी पूजा करता है, वहीं वे प्रकट होते हैं ।
    en:
      title: 'Chapter 8 - Verse 12'
      subtitle: ''
      image: ''
      description: |-
        The deity or the Supreme Lord is not in the idol of wood or stone. Supreme Lord exists in the devotion of a man, that is, where man worships the Lord through devotion and faith, that is where he appears.
- id: '13'
  type: leaf
  paginated: true
  meta:
    hi:
      title: 'अध्याय ८ - श्लोक १३'
      subtitle: ''
      image: ''
      description: |-
        शांति से बढ़कर कोई तप नहीं, संतोष से बढ़कर कोई सुख नहीं । तृष्णा अथवा चाह से बढ़कर कोई रोग नहीं, दयालुता से बढ़कर कोई धर्म नहीं ।
    en:
      title: 'Chapter 8 - Verse 13'
      subtitle: ''
      image: ''
      description: |-
        There is no austerity equal to a balanced mind, and there is no happiness equal to contentment; there is no disease like covetousness, and no virtue like mercy.
- id: '14'
  type: leaf
  paginated: true
  meta:
    hi:
      title: 'अध्याय ८ - श्लोक १४'
      subtitle: ''
      image: ''
      description: |-
        क्रोध यमराज के समान है । तृष्णा वैतरणी है । विद्या कामधेनु है और संतोष नंदन वन अर्थात इंद्र के उद्यान के समान है ।
    en:
      title: 'Chapter 8 - Verse 14'
      subtitle: ''
      image: ''
      description: |-
        Anger is a personification of Yama (the demigod of death); thirst is like the hellish river Vaitarani; knowledge is like a kamadhenu (the cow of plenty); and contentment is like Nandanavana (the garden of Indra).
- id: '15'
  type: leaf
  paginated: true
  meta:
    hi:
      title: 'अध्याय ८ - श्लोक १५'
      subtitle: ''
      image: ''
      description: |-
        गुणों से मनुष्य के सौन्दर्य की वृद्धि होती है । शील से कुल की शोभा होती है । कार्यों में सफलता से विद्या शोभित होती है और धन के सही उपभोग से धन की शोभा बढ़ती है ॥ १५११
    en:
      title: 'Chapter 8 - Verse 15'
      subtitle: ''
      image: ''
      description: |-
        Moral excellence is an ornament for personal beauty; righteous conduct, for high birth; success for learning; and proper spending for wealth.
- id: '16'
  type: leaf
  paginated: true
  meta:
    hi:
      title: 'अध्याय ८ - श्लोक १६'
      subtitle: ''
      image: ''
      description: |-
        गुणहीन मनुष्यों का सुंदर अथवा रूपवान होना व्यर्थ होता है । जिस व्यक्ति का आचरण शील से युक्त नहीं, उसकी कुल में निंदा होती है । जिस व्यक्ति में किसी कार्य को सिद्ध करने की शक्ति नहीं, ऐसे बुद्धिहीन व्यक्ति की विद्या व्यर्थ है और जिस धन का उपभोग नहीं किया जाता, वह धन भी व्यर्थ है ।
    en:
      title: 'Chapter 8 - Verse 16'
      subtitle: ''
      image: ''
      description: |-
        Beauty is spoiled by an immoral nature; noble birth by bad conduct; learning, without being perfected; and wealth by not being properly utilised.
- id: '17'
  type: leaf
  paginated: true
  meta:
    hi:
      title: 'अध्याय ८ - श्लोक १७'
      subtitle: ''
      image: ''
      description: |-
        भूमि के अंदर से निकलने वाला पानी शुद्ध माना जाता है । पतिव्रता नारी पवित्र होती है । लोगों का कल्याण करने वाला राजा पवित्र माना जाता है और संतोषी ब्राह्मण को भी पवित्र माना गया है ।
    en:
      title: 'Chapter 8 - Verse 17'
      subtitle: ''
      image: ''
      description: |-
        Water seeping into the earth is pure; and a devoted wife is pure; the king who is the benefactor of his people is pure; and pure is the Brāhmaṇa who is contented.
- id: '18'
  type: leaf
  paginated: true
  meta:
    hi:
      title: 'अध्याय ८ - श्लोक १८'
      subtitle: ''
      image: ''
      description: |-
        संतोषरहित ब्राह्मण, संतुष्ट होने वाला राजा, शर्म करने वाली वेश्या और लज्जाहीन कुलीन स्त्रियां नष्ट हो जाती हैं ।
    en:
      title: 'Chapter 8 - Verse 18'
      subtitle: ''
      image: ''
      description: |-
        Discontented brahmanas, contented kings, shy prostitutes, and immodest housewives are ruined.
- id: '19'
  type: leaf
  paginated: true
  meta:
    hi:
      title: 'अध्याय ८ - श्लोक १९'
      subtitle: ''
      image: ''
      description: |-
        यदि कुल विद्याहीन है तो उसके विशाल और बड़े होने से कोई लाभ नहीं, यदि बुरे कुल में उत्पन्न हुआ व्यक्ति विद्वान है तो देवता लोग भी उसकी पूजा करते हैं ।
    en:
      title: 'Chapter 8 - Verse 19'
      subtitle: ''
      image: ''
      description: |-
        Of what avail is a high birth if a person is destitute of scholarship? A man who is of low extraction is honoured even by the Gods if he is learned.
- id: '20'
  type: leaf
  paginated: true
  meta:
    hi:
      title: 'अध्याय ८ - श्लोक २०'
      subtitle: ''
      image: ''
      description: |-
        इस संसार में विद्वान की प्रशंसा होती है । विद्वान को ही आदर- सम्मान और धनधान्य की प्राप्ति होती है । प्रत्येक वस्तु की प्राप्ति विद्या द्वारा ही होती है और विद्या की सब जगह पूजा होती है ।
    en:
      title: 'Chapter 8 - Verse 20'
      subtitle: ''
      image: ''
      description: |-
        A learned man is honoured by the people. A learned man commands respect everywhere for his learning. Indeed, learning is honoured everywhere.
- id: '21'
  type: leaf
  paginated: true
  meta:
    hi:
      title: 'अध्याय ८ - श्लोक २१'
      subtitle: ''
      image: ''
      description: |-
        मांस खाने वाले, शराब पीने वाले, मूर्ख और निरक्षर मनुष्य रूपी पशुओं के भार से यह पृथ्वी पीड़ित और दुखी रहती है ।
    en:
      title: 'Chapter 8 - Verse 21'
      subtitle: ''
      image: ''
      description: |-
        The earth is encumbered with the weight of the flesh-eaters, winebibblers, dolts and blockheads, who are beasts in the form of men.
- id: '22'
  type: leaf
  paginated: true
  meta:
    hi:
      title: 'अध्याय ८ - श्लोक २२'
      subtitle: ''
      image: ''
      description: |-
        जो देश को अन्नहीन करता हो, जिसमें मंत्रों को न जानने वाले ऋत्विज हों, जिसके यजमान दान भावना से रहित हों, ऐसा यज्ञ शत्रु समान है ।
    en:
      title: 'Chapter 8 - Verse 22'
      subtitle: ''
      image: ''
      description: |-
        There is no enemy like a yajna (sacrifice) which consumes the kingdom when not attended by feeding on a large scale; consumes the priest when the chanting is not done properly; and consumes the yajaman (the responsible person) when the gifts are not made.
