- id: '1'
  type: leaf
  paginated: true
  meta:
    hi:
      title: 'अध्याय १५ - श्लोक १'
      subtitle: ''
      image: ''
      description: |-
        जिसका हृदय प्राणिमात्र पर दया से पिघल जाता है, उसे ज्ञान और मोक्ष प्राप्त करने, तथा जटाधारण और शरीर पर भस्म लगाने की क्या आवश्यकता है ? ॥1 ॥
    en:
      title: 'Chapter 15 - Verse 1'
      subtitle: ''
      image: ''
      description: ''
- id: '2'
  type: leaf
  paginated: true
  meta:
    hi:
      title: 'अध्याय १५ - श्लोक २'
      subtitle: ''
      image: ''
      description: |-
        जो गुरु अपने शिष्य को एक अक्षर ॐ अर्थात परमेश्वर का ठीक से ज्ञान करवा देता है, उस गुरु के ऋण से शिष्य मुक्त नहीं हो पाते । संसार में ऐसा कोई पदार्थ नहीं, जिसे गुरु को समर्पित करके शिष्य गुरु के ऋण से मुक्त हो सके ॥ 2 ॥
    en:
      title: 'Chapter 15 - Verse 2'
      subtitle: ''
      image: ''
      description: ''
- id: '3'
  type: leaf
  paginated: true
  meta:
    hi:
      title: 'अध्याय १५ - श्लोक ३'
      subtitle: ''
      image: ''
      description: |-
        दुर्जन और कांटे इन दो चीजों से बचने के दो ही उपाय हैं, या तो जूतों से इनका मुंह कुचल दिया जाए, उसके अस्तित्व को ही समाप्त कर दिया जाए अथवा उनको दूर से ही त्याग दिया जाए ॥ 3 ॥
    en:
      title: 'Chapter 15 - Verse 3'
      subtitle: ''
      image: ''
      description: ''
- id: '4'
  type: leaf
  paginated: true
  meta:
    hi:
      title: 'अध्याय १५ - श्लोक ४'
      subtitle: ''
      image: ''
      description: |-
        गंदे कपड़े पहनने वाले, गंदे दांतों वाले अर्थात दांतों की सफाई न करने वाले, अधिक भोजन करने वाले, कठोर वचन बोलने वाले, सूर्य उदय होने तथा सूर्यास्त के समय सोने वाले व्यक्ति को लक्ष्मी स्वास्थ्य, सौंदर्य और शोभा त्याग देती है, भले ही विष्णु क्यों न हो ॥ 4 ॥
    en:
      title: 'Chapter 15 - Verse 4'
      subtitle: ''
      image: ''
      description: ''
- id: '5'
  type: leaf
  paginated: true
  meta:
    hi:
      title: 'अध्याय १५ - श्लोक ५'
      subtitle: ''
      image: ''
      description: |-
        जब मनुष्य के पास धन नहीं रहता तो उसके मित्र, स्त्री, नौकर-चाकर और भाई-बंधु सब उसे छोड़कर चले जाते हैं । यदि उसके पास फिर से धन-संपत्ति आ जाए तो वे फिर उसका आश्रय ले लेते हैं । संसार में धन ही मनुष्य का बन्धु है ॥ 5 ॥
    en:
      title: 'Chapter 15 - Verse 5'
      subtitle: ''
      image: ''
      description: ''
- id: '6'
  type: leaf
  paginated: true
  meta:
    hi:
      title: 'अध्याय १५ - श्लोक ६'
      subtitle: ''
      image: ''
      description: |-
        अन्याय से कमाया हुआ धन अधिक से अधिक दस वर्ष तक आदमी के पास ठहरता है और ग्यारहवां वर्ष प्रारंभ होते ही ब्याज और मूल सहित नष्ट हो जाता है ॥ 6 ॥
    en:
      title: 'Chapter 15 - Verse 6'
      subtitle: ''
      image: ''
      description: ''
- id: '7'
  type: leaf
  paginated: true
  meta:
    hi:
      title: 'अध्याय १५ - श्लोक ७'
      subtitle: ''
      image: ''
      description: |-
        समर्थ और शक्तिवान पुरुष यदि कोई अनुचित कार्य भी करता है तो उसे उचित समझा जाता है, जबकि नीच पुरुष द्वारा किया उचित कार्य भी अनुचित कहलाता है । उदाहरण के लिए राहु नामक दैत्य के लिए अमृत भी मृत्यु का कारण बन गया और शिव के लिए विष भी उनके कंठ का आभूषण माना गया । विषपान के कारण उनकी मृत्यु नहीं हुई, बल्कि उन्हें नीलकंठ कहा जाने लगा ॥ 7 ॥
    en:
      title: 'Chapter 15 - Verse 7'
      subtitle: ''
      image: ''
      description: ''
- id: '8'
  type: leaf
  paginated: true
  meta:
    hi:
      title: 'अध्याय १५ - श्लोक ८'
      subtitle: ''
      image: ''
      description: |-
        वास्तविक भोजन वह है जो ब्राह्मण आदि को खिला देने के बाद बचता है, अर्थात गृहस्थ को चाहिए कि वह स्वयं भोजन करने से पहले ब्राह्मण को भोजन कराए, इसी प्रकार प्रेम और स्नेह उसे ही कहा जा सकता है जो परायों से किया जाता है, अपने बन्धु-बान्धवों से तो सभी प्रेम करते हैं । बुद्धिमत्ता यह है कि मनुष्य पाप कर्म करने से बचा रहे । धर्म वह है जिसमें छल-कपट न हो ॥ 8 ॥
    en:
      title: 'Chapter 15 - Verse 8'
      subtitle: ''
      image: ''
      description: ''
- id: '9'
  type: leaf
  paginated: true
  meta:
    hi:
      title: 'अध्याय १५ - श्लोक ९'
      subtitle: ''
      image: ''
      description: |-
        किसी विशेष स्थिति में रत्न चाहे पैरों में लुढ़कता रहे और कांच को सिर पर धारण किया जाए, परंतु जब बेचने अथवा लेने का समय आता है तो कांच को कांच और रत्न को रत्न ही कहा जाता है ॥ 9 ॥
    en:
      title: 'Chapter 15 - Verse 9'
      subtitle: ''
      image: ''
      description: ''
- id: '10'
  type: leaf
  paginated: true
  meta:
    hi:
      title: 'अध्याय १५ - श्लोक १०'
      subtitle: ''
      image: ''
      description: |-
        वेद आदि शास्त्र अत्यंत विशाल हैं, वे ज्ञान के समुद्र हैं, विद्याएं भी बहुत सी हैं, परंतु मनुष्य की आयु सीमित है और उसके मार्ग में कठिनाइयां भी बहुत-सी आती हैं, इसलिए उसके लिए उचित है कि वह शास्त्रों से सारभूत बातों को उसी प्रकार ग्रहण कर ले, जिस प्रकार हंस पानी मिले दूध से दूध ग्रहण कर लेता है ॥ 10 ॥
    en:
      title: 'Chapter 15 - Verse 10'
      subtitle: ''
      image: ''
      description: ''
- id: '11'
  type: leaf
  paginated: true
  meta:
    hi:
      title: 'अध्याय १५ - श्लोक ११'
      subtitle: ''
      image: ''
      description: |-
        दूर से चलकर आने वाला यात्री थका हुआ होता है, बिना किसी स्वार्थ के घर में आए हुए अतिथि की पूजा किए बिना जो घर का स्वामी स्वयं भोजन कर लेता है, उसे निश्चय ही चाण्डाल कहा जाता है ॥ 11 ॥
    en:
      title: 'Chapter 15 - Verse 11'
      subtitle: ''
      image: ''
      description: ''
- id: '12'
  type: leaf
  paginated: true
  meta:
    hi:
      title: 'अध्याय १५ - श्लोक १२'
      subtitle: ''
      image: ''
      description: |-
        जो लोग वेद आदि शास्त्रों का अध्ययन करने के बाद भी आत्मा- परमात्मा के संबंध में कुछ नहीं जानते, वे आत्मज्ञान से रहित उस कलछी की तरह हैं, जो स्वादिष्ट साग सब्जी में तो घूमती है, परंतु उसे उसके स्वाद का बिलकुल भी ज्ञान नहीं होता ॥ 12 ॥
    en:
      title: 'Chapter 15 - Verse 12'
      subtitle: ''
      image: ''
      description: ''
- id: '13'
  type: leaf
  paginated: true
  meta:
    hi:
      title: 'अध्याय १५ - श्लोक १३'
      subtitle: ''
      image: ''
      description: |-
        इस संसार-सागर में ब्राह्मणरूपी नौका धन्य है, जो उल्टी गति से चलती है । यह उल्टी गति क्या है ? जो इस नाव के नीचे रहते हैं, वे सब तो भवसागर से पार उतर जाते हैं और जो नाव के ऊपर चढ़ते हैं, उनका पतन हो होता है ॥ 13 ॥
    en:
      title: 'Chapter 15 - Verse 13'
      subtitle: ''
      image: ''
      description: ''
- id: '14'
  type: leaf
  paginated: true
  meta:
    hi:
      title: 'अध्याय १५ - श्लोक १४'
      subtitle: ''
      image: ''
      description: |-
        दूसरे के घर में जाने से व्यक्ति का सम्मान घटता है, वह छोटा होता है । जैसे चंद्रमा को अमृत का भण्डार कहा जाता है, यह गुणकारी औषधियों का स्वामी भी है, इसकी छवि अथवा इसकी किरणों को अमृत के समान माना जाता है, इसमें कांति भी है अर्थात यह प्रकाश से युक्त है, परंतु जब यही चंद्रमा सूर्यमण्डल पर जाता है तो तेजरहित हो जाता है, वहां उसकी सारी चमक-दमक समाप्त हो जाती है ॥ 14 ॥
    en:
      title: 'Chapter 15 - Verse 14'
      subtitle: ''
      image: ''
      description: ''
- id: '15'
  type: leaf
  paginated: true
  meta:
    hi:
      title: 'अध्याय १५ - श्लोक १५'
      subtitle: ''
      image: ''
      description: |-
        भौंरा कमलिनी के फूल की पंखुड़ियों में बैठा रहता है, उसके पराग का रस चूसता रहता है और उसके मध्य में मस्त बना रहता है, परंतु दैवयोग से जब उसे एक स्थान से किसी दूसरे स्थान को जाना पड़ता है, तो वहां उसे करील आदि वृक्षों के फूलों से रस तो मिल जाता है, किंतु कांटों के कारण काफी कष्ट भी उठाना पड़ता है ॥ 15 ॥
    en:
      title: 'Chapter 15 - Verse 15'
      subtitle: ''
      image: ''
      description: ''
- id: '16'
  type: leaf
  paginated: true
  meta:
    hi:
      title: 'अध्याय १५ - श्लोक १६'
      subtitle: ''
      image: ''
      description: |-
        विष्णु लक्ष्मी से पूछते हैं कि वह ब्राह्मणों से नाराज क्यों रहती हैं तो उत्तर देती हुई लक्ष्मी कहती हैं-अगस्त्य ऋषि ने नाराज होकर मेरे पिता समुद्र को ही पी लिया था, ब्राह्मण भृगु ने क्रोध में आकर आपकी छाती पर लात मारी थी और ये ब्राह्मण लोग बचपन से ही मेरी सौत सरस्वती को प्रसन्न करने का प्रयत्न करते रहते हैं, प्रतिदिन शिव की पूजा के लिए मेरे निवास स्थान से कमल पुष्पों को उजाड़ देते हैं । हे स्वामी! यही कारण है, जिससे मैं ब्राह्मणों से सदा दूर रहती हूं ॥ 16 ॥
    en:
      title: 'Chapter 15 - Verse 16'
      subtitle: ''
      image: ''
      description: ''
- id: '17'
  type: leaf
  paginated: true
  meta:
    hi:
      title: 'अध्याय १५ - श्लोक १७'
      subtitle: ''
      image: ''
      description: |-
        इस संसार में बहुत से बंधन हैं, परंतु प्रेमरूपी रस्सी का बंधन कुछ विचित्र होता है । लकड़ी को छेदने की शक्ति रखने वाला भौंरा भी कमल के फूल में बंद होकर निष्क्रिय हो जाता है । कमल की पंखुड़ियों को काटने की उसमें शक्ति होती है, परंतु उनके प्रति अतिरेक प्रेम- भावना होने के कारण वह ऐसा नहीं करता ॥ 17 ॥
    en:
      title: 'Chapter 15 - Verse 17'
      subtitle: ''
      image: ''
      description: ''
- id: '18'
  type: leaf
  paginated: true
  meta:
    hi:
      title: 'अध्याय १५ - श्लोक १८'
      subtitle: ''
      image: ''
      description: |-
        चंदन का वृक्ष कट जाने पर भी अपनी सुगंध नहीं छोड़ता, बूढ़ा हो जाने पर भी हाथी अपनी क्रीड़ाएं नहीं छोड़ता, कोल्हू पर पेर (पेल) दिए जाने के बाद भी ईख अपनी मिठास को नहीं छोड़ता, इसी प्रकार कुलीन मनुष्य निर्धन हो जाने पर भी अपनी शालीनता को नहीं छोड़ता ॥ 18 ॥
    en:
      title: 'Chapter 15 - Verse 18'
      subtitle: ''
      image: ''
      description: ''
