- id: '1'
  type: leaf
  paginated: true
  meta:
    hi:
      title: 'अध्याय १५ - श्लोक १'
      subtitle: ''
      image: ''
      description: |-
        जिसका हृदय प्राणिमात्र पर दया से पिघल जाता है, उसे ज्ञान और मोक्ष प्राप्त करने, तथा जटाधारण और शरीर पर भस्म लगाने की क्या आवश्यकता है ? ।
    en:
      title: 'Chapter 15 - Verse 1'
      subtitle: ''
      image: ''
      description: |-
        For one whose heart melts with compassion for all creatures; what is the necessity of knowledge, liberation, matted hair on the head, and smearing the body with ashes.
- id: '2'
  type: leaf
  paginated: true
  meta:
    hi:
      title: 'अध्याय १५ - श्लोक २'
      subtitle: ''
      image: ''
      description: |-
        जो गुरु अपने शिष्य को एक अक्षर ॐ अर्थात परमेश्वर का ठीक से ज्ञान करवा देता है, उस गुरु के ऋण से शिष्य मुक्त नहीं हो पाते । संसार में ऐसा कोई पदार्थ नहीं, जिसे गुरु को समर्पित करके शिष्य गुरु के ऋण से मुक्त हो सके ।
    en:
      title: 'Chapter 15 - Verse 2'
      subtitle: ''
      image: ''
      description: |-
        There is no treasure on earth the gift of which will cancel the debt a disciple owes his guru for having taught him even a single letter.
- id: '3'
  type: leaf
  paginated: true
  meta:
    hi:
      title: 'अध्याय १५ - श्लोक ३'
      subtitle: ''
      image: ''
      description: |-
        दुर्जन और कांटे इन दो चीजों से बचने के दो ही उपाय हैं, या तो जूतों से इनका मुंह कुचल दिया जाए, उसके अस्तित्व को ही समाप्त कर दिया जाए अथवा उनको दूर से ही त्याग दिया जाए ।
    en:
      title: 'Chapter 15 - Verse 3'
      subtitle: ''
      image: ''
      description: |-
        There are two ways to get rid of thorns and wicked persons; using footwear in the first case and in the second shaming them so that they cannot raise their faces again thus keeping them at a distance.
- id: '4'
  type: leaf
  paginated: true
  meta:
    hi:
      title: 'अध्याय १५ - श्लोक ४'
      subtitle: ''
      image: ''
      description: |-
        गंदे कपड़े पहनने वाले, गंदे दांतों वाले अर्थात दांतों की सफाई न करने वाले, अधिक भोजन करने वाले, कठोर वचन बोलने वाले, सूर्य उदय होने तथा सूर्यास्त के समय सोने वाले व्यक्ति को लक्ष्मी, स्वास्थ्य, सौंदर्य और शोभा त्याग देती है, भले ही विष्णु क्यों न हो ।
    en:
      title: 'Chapter 15 - Verse 4'
      subtitle: ''
      image: ''
      description: |-
        He who wears unclean garments, has dirty teeth, as a glutton, speaks unkindly and sleeps after sunrise -- although he may be the greatest personality -- will lose the favour of Lakshmi.
- id: '5'
  type: leaf
  paginated: true
  meta:
    hi:
      title: 'अध्याय १५ - श्लोक ५'
      subtitle: ''
      image: ''
      description: |-
        जब मनुष्य के पास धन नहीं रहता तो उसके मित्र, स्त्री, नौकर-चाकर और भाई-बंधु सब उसे छोड़कर चले जाते हैं । यदि उसके पास फिर से धन-संपत्ति आ जाए तो वे फिर उसका आश्रय ले लेते हैं । संसार में धन ही मनुष्य का बन्धु है ।
    en:
      title: 'Chapter 15 - Verse 5'
      subtitle: ''
      image: ''
      description: |-
        He who loses his money is forsaken by his friends, his wife, his servants and his relations; yet when he regains his riches those who have forsaken him come back to him. Hence wealth is certainly the best of relations.
- id: '6'
  type: leaf
  paginated: true
  meta:
    hi:
      title: 'अध्याय १५ - श्लोक ६'
      subtitle: ''
      image: ''
      description: |-
        अन्याय से कमाया हुआ धन अधिक से अधिक दस वर्ष तक आदमी के पास ठहरता है और ग्यारहवां वर्ष प्रारंभ होते ही ब्याज और मूल सहित नष्ट हो जाता है ।
    en:
      title: 'Chapter 15 - Verse 6'
      subtitle: ''
      image: ''
      description: |-
        Sinfully acquired wealth may remain for ten years; in the eleventh year it disappears with even the original stock.
- id: '7'
  type: leaf
  paginated: true
  meta:
    hi:
      title: 'अध्याय १५ - श्लोक ७'
      subtitle: ''
      image: ''
      description: |-
        समर्थ और शक्तिवान पुरुष यदि कोई अनुचित कार्य भी करता है तो उसे उचित समझा जाता है, जबकि नीच पुरुष द्वारा किया उचित कार्य भी अनुचित कहलाता है । उदाहरण के लिए राहु नामक दैत्य के लिए अमृत भी मृत्यु का कारण बन गया और शिव के लिए विष भी उनके कंठ का आभूषण माना गया । विषपान के कारण उनकी मृत्यु नहीं हुई, बल्कि उन्हें नीलकंठ कहा जाने लगा ।
    en:
      title: 'Chapter 15 - Verse 7'
      subtitle: ''
      image: ''
      description: |-
        A bad action committed by a great man is not censured (as there is none that can reproach him), and a good action performed by a low-class man comes to be condemned (because none respects him). Just see: the drinking of nectar is excellent, but it became the cause of Rahu's demise; and the drinking of poison is harmful, but when Lord Shiva (who is exalted) drank it, it became an ornament to his neck.
- id: '8'
  type: leaf
  paginated: true
  meta:
    hi:
      title: 'अध्याय १५ - श्लोक ८'
      subtitle: ''
      image: ''
      description: |-
        वास्तविक भोजन वह है जो ब्राह्मण आदि को खिला देने के बाद बचता है, अर्थात गृहस्थ को चाहिए कि वह स्वयं भोजन करने से पहले ब्राह्मण को भोजन कराए, इसी प्रकार प्रेम और स्नेह उसे ही कहा जा सकता है जो परायों से किया जाता है, अपने बन्धु-बान्धवों से तो सभी प्रेम करते हैं । बुद्धिमत्ता यह है कि मनुष्य पाप कर्म करने से बचा रहे । धर्म वह है जिसमें छल-कपट न हो ।
    en:
      title: 'Chapter 15 - Verse 8'
      subtitle: ''
      image: ''
      description: |-
        A true meal is that which consists of the remnants left after a Brāhmaṇa's meal. Love which is shown to others is true love, not that which is cherished for one's own self. to abstain from sin is true wisdom. That is an act of charity which is performed without ostentation.
- id: '9'
  type: leaf
  paginated: true
  meta:
    hi:
      title: 'अध्याय १५ - श्लोक ९'
      subtitle: ''
      image: ''
      description: |-
        किसी विशेष स्थिति में रत्न चाहे पैरों में लुढ़कता रहे और कांच को सिर पर धारण किया जाए, परंतु जब बेचने अथवा लेने का समय आता है तो कांच को कांच और रत्न को रत्न ही कहा जाता है ।
    en:
      title: 'Chapter 15 - Verse 9'
      subtitle: ''
      image: ''
      description: |-
        For want of discernment the most precious jewels lie in the dust at the feet of men while bits of glass are worn on their heads. But we should not imagine that the gems have sunk in value, and the bits of glass have risen in importance. When a person of critical judgement shall appear, each will be given its right position.
- id: '10'
  type: leaf
  paginated: true
  meta:
    hi:
      title: 'अध्याय १५ - श्लोक १०'
      subtitle: ''
      image: ''
      description: |-
        वेद आदि शास्त्र अत्यंत विशाल हैं, वे ज्ञान के समुद्र हैं, विद्याएं भी बहुत सी हैं, परंतु मनुष्य की आयु सीमित है और उसके मार्ग में कठिनाइयां भी बहुत-सी आती हैं, इसलिए उसके लिए उचित है कि वह शास्त्रों से सारभूत बातों को उसी प्रकार ग्रहण कर ले, जिस प्रकार हंस पानी मिले दूध से दूध ग्रहण कर लेता है ।
    en:
      title: 'Chapter 15 - Verse 10'
      subtitle: ''
      image: ''
      description: |-
        Vedic knowledge is unlimited, and the arts to be learned are many; the time we have is short, and our opportunities to learn are beset with obstacles. Therefore select for learning that which is most important, just as the swan drinks only the milk in water.
- id: '11'
  type: leaf
  paginated: true
  meta:
    hi:
      title: 'अध्याय १५ - श्लोक ११'
      subtitle: ''
      image: ''
      description: |-
        दूर से चलकर आने वाला यात्री थका हुआ होता है, बिना किसी स्वार्थ के घर में आए हुए अतिथि की पूजा किए बिना जो घर का स्वामी स्वयं भोजन कर लेता है, उसे निश्चय ही चाण्डाल कहा जाता है ।
    en:
      title: 'Chapter 15 - Verse 11'
      subtitle: ''
      image: ''
      description: |-
        He is a Cāṇḍāla who eats his dinner without entertaining the stranger who has come to his house quite accidentally, having travelled from a long distance and is wearied.
- id: '12'
  type: leaf
  paginated: true
  meta:
    hi:
      title: 'अध्याय १५ - श्लोक १२'
      subtitle: ''
      image: ''
      description: |-
        जो लोग वेद आदि शास्त्रों का अध्ययन करने के बाद भी आत्मा- परमात्मा के संबंध में कुछ नहीं जानते, वे आत्मज्ञान से रहित उस कलछी की तरह हैं, जो स्वादिष्ट साग सब्जी में तो घूमती है, परंतु उसे उसके स्वाद का बिलकुल भी ज्ञान नहीं होता ।
    en:
      title: 'Chapter 15 - Verse 12'
      subtitle: ''
      image: ''
      description: |-
        One may know the four Vedas and the Dharma-Śāstras, yet if he has no realisation of his own spiritual self, he can be said to be like the ladle which stirs all kinds of foods but knows not the taste of any.
- id: '13'
  type: leaf
  paginated: true
  meta:
    hi:
      title: 'अध्याय १५ - श्लोक १३'
      subtitle: ''
      image: ''
      description: |-
        इस संसार-सागर में ब्राह्मणरूपी नौका धन्य है, जो उल्टी गति से चलती है । यह उल्टी गति क्या है ? जो इस नाव के नीचे रहते हैं, वे सब तो भवसागर से पार उतर जाते हैं और जो नाव के ऊपर चढ़ते हैं, उनका पतन हो होता है ।
    en:
      title: 'Chapter 15 - Verse 13'
      subtitle: ''
      image: ''
      description: |-
        Those blessed souls are certainly elevated who, while crossing the ocean of life, take shelter of a genuine Brāhmaṇa, who is likened unto a boat. They are unlike passengers aboard an ordinary ship which runs the risk of sinking.
- id: '14'
  type: leaf
  paginated: true
  meta:
    hi:
      title: 'अध्याय १५ - श्लोक १४'
      subtitle: ''
      image: ''
      description: |-
        दूसरे के घर में जाने से व्यक्ति का सम्मान घटता है, वह छोटा होता है । जैसे चंद्रमा को अमृत का भण्डार कहा जाता है, यह गुणकारी औषधियों का स्वामी भी है, इसकी छवि अथवा इसकी किरणों को अमृत के समान माना जाता है, इसमें कांति भी है अर्थात यह प्रकाश से युक्त है, परंतु जब यही चंद्रमा सूर्यमण्डल पर जाता है तो तेजरहित हो जाता है, वहां उसकी सारी चमक-दमक समाप्त हो जाती है ।
    en:
      title: 'Chapter 15 - Verse 14'
      subtitle: ''
      image: ''
      description: |-
        The moon, who is the abode of nectar and the presiding deity of all medicines, although immortal like amrta and resplendent in form, loses the brilliance of his rays when he repairs to the abode of the sun (day time). Therefore will not an ordinary man be made to feel inferior by going to live at the house of another.
- id: '15'
  type: leaf
  paginated: true
  meta:
    hi:
      title: 'अध्याय १५ - श्लोक १५'
      subtitle: ''
      image: ''
      description: |-
        भौंरा कमलिनी के फूल की पंखुड़ियों में बैठा रहता है, उसके पराग का रस चूसता रहता है और उसके मध्य में मस्त बना रहता है, परंतु दैवयोग से जब उसे एक स्थान से किसी दूसरे स्थान को जाना पड़ता है, तो वहां उसे करील आदि वृक्षों के फूलों से रस तो मिल जाता है, किंतु कांटों के कारण काफी कष्ट भी उठाना पड़ता है ।
    en:
      title: 'Chapter 15 - Verse 15'
      subtitle: ''
      image: ''
      description: |-
        This humble bee, who always resides among the soft petals of the lotus and drinks abundantly its sweet nectar, is now feasting on the flower of the ordinary Kutaja. Being in a strange country where the lotuses do not exist, he is considering the pollen of the kutaja to be nice.
- id: '16'
  type: leaf
  paginated: true
  meta:
    hi:
      title: 'अध्याय १५ - श्लोक १६'
      subtitle: ''
      image: ''
      description: |-
        श्री विष्णु लक्ष्मी माता से पूछते हैं कि वह ब्राह्मणों से नाराज क्यों रहती हैं तो उत्तर देती हुई लक्ष्मी माता कहती हैं - अगस्त्य ऋषि ने नाराज होकर मेरे पिता समुद्र को ही पी लिया था, ब्राह्मण भृगु ने क्रोध में आकर आपकी छाती पर लात मारी थी और ये ब्राह्मण लोग बचपन से ही मेरी सौत सरस्वती को प्रसन्न करने का प्रयत्न करते रहते हैं, प्रतिदिन शिव की पूजा के लिए मेरे निवास स्थान से कमल पुष्पों को उजाड़ देते हैं । हे स्वामी! यही कारण है, जिससे मैं ब्राह्मणों से सदा दूर रहती हूं ।
    en:
      title: 'Chapter 15 - Verse 16'
      subtitle: ''
      image: ''
      description: |-
        (Lord Viṣṇu asked His spouse Lakṣmī why She did not care to live in the house of a Brāhmaṇa, when She replied) ' O Lord a Rishi named Agastya drank up My father (the ocean) in anger; Bhṛgu Muni kicked You in the chest; Brāhmaṇas pride themselves on their learning having sought the favour of My competitor Sarasvatī; and lastly they pluck each day the lotus which is My abode, and therewith worship Lord Shiva. Therefore, O Lord, I fear to dwell with a Brāhmaṇa and that properly.
- id: '17'
  type: leaf
  paginated: true
  meta:
    hi:
      title: 'अध्याय १५ - श्लोक १७'
      subtitle: ''
      image: ''
      description: |-
        इस संसार में बहुत से बंधन हैं, परंतु प्रेमरूपी रस्सी का बंधन कुछ विचित्र होता है । लकड़ी को छेदने की शक्ति रखने वाला भौंरा भी कमल के फूल में बंद होकर निष्क्रिय हो जाता है । कमल की पंखुड़ियों को काटने की उसमें शक्ति होती है, परंतु उनके प्रति प्रेम-भावना होने के कारण वह ऐसा नहीं करता ।
    en:
      title: 'Chapter 15 - Verse 17'
      subtitle: ''
      image: ''
      description: |-
        There are many ways of binding by which one can be dominated and controlled in this world, but the bond of affection is the strongest. For example, take the case of the humble bee which, although expert at piercing hardened wood, becomes caught in the embrace of its beloved flowers (as the petals close at dusk).
- id: '18'
  type: leaf
  paginated: true
  meta:
    hi:
      title: 'अध्याय १५ - श्लोक १८'
      subtitle: ''
      image: ''
      description: |-
        चंदन का वृक्ष कट जाने पर भी अपनी सुगंध नहीं छोड़ता, बूढ़ा हो जाने पर भी हाथी अपनी क्रीड़ाएं नहीं छोड़ता, गन्ना निचोड़े जाने पर भी अपनी मिठास नहीं छोड़ता, इसी प्रकार ऊँचे कुल में पैदा हुआ व्यक्ति मनुष्य निर्धन हो जाने पर भी अपनी शालीनता को नहीं छोड़ता ।
    en:
      title: 'Chapter 15 - Verse 18'
      subtitle: ''
      image: ''
      description: |-
        Although sandalwood be cut, it does not forsake its natural quality of fragrance; so also the elephant does not give up sportiveness though he should grow old. The sugarcane does not cease to be sweet though squeezed in a mill; so the man of noble extraction does not lose his lofty qualities, no matter how pinched he is by poverty.
