- id: '1'
  type: leaf
  paginated: true
  meta:
    hi:
      title: 'अध्याय ९ - श्लोक १'
      subtitle: ''
      image: ''
      description: |-
        यदि तू मुक्ति चाहता है तो बुरे व्यसनों और बुरी आदतों को विष के समान समझकर उनका त्याग कर दे तथा क्षमा, सरलता, दया, पवित्रता और सत्य को अमृत के समान ग्रहण कर ।
    en:
      title: 'Chapter 9 - Verse 1'
      subtitle: ''
      image: ''
      description: |-
        My dear child, if you desire to be free from the cycle of birth and death, then abandon the objects of sense gratification as poison. Drink instead the nectar of forbearance, upright conduct, mercy, cleanliness and truth.
- id: '2'
  type: leaf
  paginated: true
  meta:
    hi:
      title: 'अध्याय ९ - श्लोक २'
      subtitle: ''
      image: ''
      description: |-
        जो लोग एक-दूसरे के भेदों को प्रकट करते हैं, वे उसी प्रकार नष्ट हो जाते हैं जैसे बांबी में फंसकर सांप नष्ट हो जाता है ।
    en:
      title: 'Chapter 9 - Verse 2'
      subtitle: ''
      image: ''
      description: |-
        Those base men who speak of the secret faults of others destroy themselves like serpents who stray onto anthills.
- id: '3'
  type: leaf
  paginated: true
  meta:
    hi:
      title: 'अध्याय ९ - श्लोक ३'
      subtitle: ''
      image: ''
      description: |-
        ब्रह्मा ने सोने में सुगंध और ईख के पौधे में फल उत्पन्न नहीं किए और निश्चय ही चंदन के वृक्ष में फूल भी पैदा नहीं होते, इसी तरह विद्वान व्यक्ति को अधिक धनी और राजा को अधिक लंबी आयु वाला नहीं बनाया । उससे ऐसा लगता है कि प्राचीनकाल में प्रभु को बुद्धि देने वाला कोई नहीं था ।
    en:
      title: 'Chapter 9 - Verse 3'
      subtitle: ''
      image: ''
      description: |-
        Perhaps nobody has advised Lord Brahma, the creator, to impart perfume to gold; fruit to the sugarcane; flowers to the sandalwood tree; wealth to the learned; and long life to the king.
- id: '4'
  type: leaf
  paginated: true
  meta:
    hi:
      title: 'अध्याय ९ - श्लोक ४'
      subtitle: ''
      image: ''
      description: |-
        सभी प्रकार की औषधियों में अमृत सबसे प्रमुख औषधि है । सुख देने वाले सब साधनों में भोजन सबसे प्रमुख है । मनुष्य की सभी इंद्रियों में आंखें सबसे प्रधान और श्रेष्ठ हैं तथा शरीर के सभी अंगों में मनुष्य का सिर सर्वश्रेष्ठ है ।
    en:
      title: 'Chapter 9 - Verse 4'
      subtitle: ''
      image: ''
      description: |-
        Nectar (amrita) is the best among medicines; eating good food is the best of all types of material happiness; the eye is the chief among all organs; and the head occupies the chief position among all parts of the body.
- id: '5'
  type: leaf
  paginated: true
  meta:
    hi:
      title: 'अध्याय ९ - श्लोक ५'
      subtitle: ''
      image: ''
      description: |-
        आकाश में किसी दूत का जाना संभव नहीं और वहां किसी से किसी प्रकार की बातचीत भी नहीं हो सकती, परंतु जिस श्रेष्ठ ब्राह्मण ने आकाश में सूर्य और चंद्रमा के ग्रहण की बात बताई है, उसे विद्वान क्यों न माना जाए ।
    en:
      title: 'Chapter 9 - Verse 5'
      subtitle: ''
      image: ''
      description: |-
        No messenger can travel about in the sky and no tidings come from there. The voice of its inhabitants as never heard, nor can any contact be established with them. Therefore the Brāhmaṇa who predicts the eclipse of the sun and moon which occur in the sky must be considered as a vidwan (man of great learning).
- id: '6'
  type: leaf
  paginated: true
  meta:
    hi:
      title: 'अध्याय ९ - श्लोक ६'
      subtitle: ''
      image: ''
      description: |-
        विद्यार्थी, सेवक, मार्ग में चलने वाला पथिक, यात्री, भख से पीडित. डरा हआ व्यक्ति और भण्डार की रक्षा करने वाला द्वारपाल यदि अपने कार्यकाल में सो रहे हों, तो इन्हें जगा देना चाहिए ।
    en:
      title: 'Chapter 9 - Verse 6'
      subtitle: ''
      image: ''
      description: |-
        The student, the servant, the traveller, the hungry person, the frightened man, the treasury guard, and the steward: these seven ought to be awakened if they fall asleep.
- id: '7'
  type: leaf
  paginated: true
  meta:
    hi:
      title: 'अध्याय ९ - श्लोक ७'
      subtitle: ''
      image: ''
      description: |-
        सांप, राजा, बाघ, सूअर, बालक, दूसरे के कुत्ते और मूर्ख व्यक्ति को सोते में जगाना नहीं चाहिए ।
    en:
      title: 'Chapter 9 - Verse 7'
      subtitle: ''
      image: ''
      description: |-
        The serpent, the king, the tiger, the stinging wasp, the small child, the dog owned by other people, and the fool: these seven ought not to be awakened from sleep.
- id: '8'
  type: leaf
  paginated: true
  meta:
    hi:
      title: 'अध्याय ९ - श्लोक ८'
      subtitle: ''
      image: ''
      description: |-
        जो ब्राह्मण धन की प्राप्ति के विचार से वेदों का अध्ययन करते हैं और जो शूद्रों अर्थात नीच मनुष्यों का अन्न खाते हैं, वे विषहीन सांप के समान कुछ भी करने में असमर्थ होते हैं ।
    en:
      title: 'Chapter 9 - Verse 8'
      subtitle: ''
      image: ''
      description: |-
        Of those who have studied the Vedas for material rewards, and those who accept foodstuffs offered by shudras, what potency have they? They are just like serpents without fangs.
- id: '9'
  type: leaf
  paginated: true
  meta:
    hi:
      title: 'अध्याय ९ - श्लोक ९'
      subtitle: ''
      image: ''
      description: |-
        जिसके नाराज होने पर किसी प्रकार का डर नहीं होता और जिसके प्रसन्न होने पर धन प्राप्ति की आशा नहीं होती, जो न दण्ड दे सकता है और न ही किसी प्रकार की दया प्रकट कर सकता है उसके नाराज होने पर किसी का कुछ नहीं बिगड़ता ।
    en:
      title: 'Chapter 9 - Verse 9'
      subtitle: ''
      image: ''
      description: |-
        He who neither rouses fear by his anger, nor confers a favour when he is pleased can neither control nor protect. What can he do?
- id: '10'
  type: leaf
  paginated: true
  meta:
    hi:
      title: 'अध्याय ९ - श्लोक १०'
      subtitle: ''
      image: ''
      description: |-
        विषहीन सांप को भी अपना फन फैलाना चाहिए, उसमें विष है या नहीं, इस बात को कोई नहीं जानता ? हां, उसके इस आडंबर से अथवा दिखावे से लोग भयभीत अवश्य हो सकते हैं ।
    en:
      title: 'Chapter 9 - Verse 10'
      subtitle: ''
      image: ''
      description: |-
        The serpent may, without being poisonous, raise high its hood, but the show of terror is enough to frighten people -- whether he be venomous or not.
- id: '11'
  type: leaf
  paginated: true
  meta:
    hi:
      title: 'अध्याय ९ - श्लोक ११'
      subtitle: ''
      image: ''
      description: |-
        मूर्ख लोग अपना प्रातःकाल का समय जुआ खेलने में, दोपहर का समय स्त्री प्रसंग में और रात्रि का समय चोरी आदि में व्यर्थ करते हैं ।
    en:
      title: 'Chapter 9 - Verse 11'
      subtitle: ''
      image: ''
      description: |-
        Wise men spend their mornings in discussing gambling, the afternoon discussing the activities of women, and the night hearing about the activities of theft. (The first item above refers to the gambling of King Yuddhisthira, the great devotee of Krishna. The second item refers to the glorious deeds of mother Sita, the consort of Lord Ramachandra. The third item hints at the adorable childhood pastimes of Sri Krishna who stole butter from the elderly cowherd ladies of Gokula. Hence Chanakya Pandits advises wise persons to spend the morning absorbed in Mahabharata, the afternoon studying Ramayana, and the evening devotedly hearing the Srimad-Bhagvatam.)
- id: '12'
  type: leaf
  paginated: true
  meta:
    hi:
      title: 'अध्याय ९ - श्लोक १२'
      subtitle: ''
      image: ''
      description: |-
        अपने ही हाथ से गंथी हई माला, अपने हाथ से घिसा हआ चंदन और अपने ही हाथ से लिखी हुई भगवान की स्तुति करने से मनुष्य इंद्र की धन-सम्पत्ति को भी वश में कर सकता है ।
    en:
      title: 'Chapter 9 - Verse 12'
      subtitle: ''
      image: ''
      description: |-
        By preparing a garland for a Deity with one's own hand; by grinding sandal paste for the Lord with one's own hand; and by writing sacred texts with one's own hand -- one becomes blessed with opulence equal to that of Indra.
- id: '13'
  type: leaf
  paginated: true
  meta:
    hi:
      title: 'अध्याय ९ - श्लोक १३'
      subtitle: ''
      image: ''
      description: |-
        ईख, तिल, मूर्ख, छोटे आदमी, स्त्री, सोना, भूमि, चंदन और दही तथा पान इन्हें जितना मला जाएगा उतने ही इनके गुण बढ़ेंगे ।
    en:
      title: 'Chapter 9 - Verse 13'
      subtitle: ''
      image: ''
      description: |-
        Reed, mole, fool, little man, woman, gold, earth, sandalwood and curd and betel leaves, the more they are rubbed, the more their qualities will increase.
- id: '14'
  type: leaf
  paginated: true
  meta:
    hi:
      title: 'अध्याय ९ - श्लोक १४'
      subtitle: ''
      image: ''
      description: |-
        दरिद्र अवस्था में यदि व्यक्ति धैर्य नहीं छोड़ता, तो निर्धनता कष्ट नहीं देती । साधारण वस्त्र को यदि साफ रखा जाए तो वह भी अच्छा लगता है । यदि सामान्य भोजन, जिसे पुष्टिकारक न माना जाए, भी ताजा और गर्म-गर्म खाया जाए तो अच्छा लगता है । इसी प्रकार सुशीलता आदि गुणों के होने पर कुरूपता बुरी नहीं लगती ।
    en:
      title: 'Chapter 9 - Verse 14'
      subtitle: ''
      image: ''
      description: |-
        Poverty is set off by fortitude; shabby garments by keeping them clean; bad food by warming it; and ugliness by good behaviour.
