- id: '1'
  type: leaf
  paginated: true
  meta:
    hi:
      title: 'अध्याय ६ - श्लोक १'
      subtitle: ''
      image: ''
      description: |-
        मनुष्य वेद आदि शास्त्रों को सुनकर धर्म के रहस्य को जान लेता है । विद्वानों की बात सुनकर दुष्ट व्यक्ति बुरे ढंग से सोचना छोड़ देता है । गुरु से ज्ञान प्राप्त कर मनुष्य संसार के बंधन से छूट जाता है ।
    en:
      title: 'Chapter 6 - Verse 1'
      subtitle: ''
      image: ''
      description: |-
        By means of hearing one understands dharma, malignity vanishes, knowledge is acquired, and liberation from material bondage is gained.
- id: '2'
  type: leaf
  paginated: true
  meta:
    hi:
      title: 'अध्याय ६ - श्लोक २'
      subtitle: ''
      image: ''
      description: |-
        पक्षियों में कौआ, पशुओं में कुत्ता, मुनियों में क्रोध करने वाला और सामान्यजन में दूसरे लोगों की निंदा करने वाला व्यक्ति दुष्ट और चाण्डाल होता है ।
    en:
      title: 'Chapter 6 - Verse 2'
      subtitle: ''
      image: ''
      description: |-
        Among birds the crow is vile; among beasts the dog; the ascetic whose sins is abominable, but he who blasphemes others is the worst Cāṇḍāla.
- id: '3'
  type: leaf
  paginated: true
  meta:
    hi:
      title: 'अध्याय ६ - श्लोक ३'
      subtitle: ''
      image: ''
      description: |-
        कांसे का बर्तन राख से मांजने पर, तांबा खटाई से, स्त्री रजस्वला होने के बाद तथा नदी का जल तीव्र वेग से शुद्ध होता है ।
    en:
      title: 'Chapter 6 - Verse 3'
      subtitle: ''
      image: ''
      description: |-
        Brass is polished by ashes; copper is cleaned by tamarind; a woman, by her menses; and a river by its flow.
- id: '4'
  type: leaf
  paginated: true
  meta:
    hi:
      title: 'अध्याय ६ - श्लोक ४'
      subtitle: ''
      image: ''
      description: |-
        अपनी प्रजा में घूम-फिरकर उसकी स्थिति को जानने वाले राजा की प्रजा उसकी पूजा करती है । जो द्विज अर्थात विद्वान ब्राह्मण देश- प्रदेश की भूमि पर ज्ञान का प्रचार करता है, उसकी पूजा होती है । जो योगी सदा घूमता रहता है, वह आदर-सत्कार का भागी होता है, परंतु भ्रमण करने वाली स्त्री भ्रष्ट हो जाती है ।
    en:
      title: 'Chapter 6 - Verse 4'
      subtitle: ''
      image: ''
      description: |-
        The king, the Brāhmaṇa, and the ascetic yogi who go abroad are respected; but the woman who wanders is utterly ruined.
- id: '5'
  type: leaf
  paginated: true
  meta:
    hi:
      title: 'अध्याय ६ - श्लोक ५'
      subtitle: ''
      image: ''
      description: |-
        मनुष्य जैसा भाग्य लेकर जन्म लेता है, उसकी बुद्धि उसी के अनुसार प्रवृत्त होती है और वह व्यवसाय अथवा काम-धन्धा भी वैसा ही चुनता है तथा उसके सहायक भी उसी प्रकार के होते हैं ।
    en:
      title: 'Chapter 6 - Verse 5'
      subtitle: ''
      image: ''
      description: |-
        As is the desire of Providence, so functions one's intellect; one's activities are also controlled by Providence; and by the will of Providence one is surrounded by helpers.
- id: '6'
  type: leaf
  paginated: true
  meta:
    hi:
      title: 'अध्याय ६ - श्लोक ६'
      subtitle: ''
      image: ''
      description: |-
        समय सब प्राणियों को अपने पेट में पचा लेता है अर्थात सबको नष्ट कर देता है । काल ही सबकी मृत्यु का कारण होता है । जब सब लोग सो जाते हैं, तो काल ही जागता रहता है । इसमें संदेह नहीं कि काल बड़ा बलवान है । काल से पार पाना अत्यंत कठिन है ।
    en:
      title: 'Chapter 6 - Verse 6'
      subtitle: ''
      image: ''
      description: |-
        Time perfects all living beings as well as kills them; it alone is awake when all others are asleep. Time is insurmountable.
- id: '7'
  type: leaf
  paginated: true
  meta:
    hi:
      title: 'अध्याय ६ - श्लोक ७'
      subtitle: ''
      image: ''
      description: |-
        जन्म से अंधे को, कामांध को और शराब आदि के नशे में मस्त व्यक्ति को कुछ दिखाई नहीं देता । स्वार्थी व्यक्ति की भी यही स्थिति है क्योंकि वह उस व्यक्ति के दोषों को देख नहीं पाता, जिससे उसके स्वार्थों की पूर्ति होती हो ।
    en:
      title: 'Chapter 6 - Verse 7'
      subtitle: ''
      image: ''
      description: |-
        Those born blind cannot see; similarly blind are those in the grip of lust. Proud men have no perception of evil; and those bent on acquiring riches see no sin in their actions.
- id: '8'
  type: leaf
  paginated: true
  meta:
    hi:
      title: 'अध्याय ६ - श्लोक ८'
      subtitle: ''
      image: ''
      description: |-
        जीवात्मा स्वयं कार्य करता है और उसका फल भी स्वयं भोगता है । वह स्वयं ही विभिन्न योनियों में जन्म लेकर संसार में भ्रमण करता है और स्वयं ही अपने पुरुषार्थ से संसार के बंधनों तथा आवागमन के चक्र से छूटकर मुक्ति को प्राप्त करता है ।
    en:
      title: 'Chapter 6 - Verse 8'
      subtitle: ''
      image: ''
      description: |-
        The spirit soul goes through his own course of karma and he himself suffers the good and bad results thereby accrued. By his own actions he entangles himself in samsara, and by his own efforts he extricates himself.
- id: '9'
  type: leaf
  paginated: true
  meta:
    hi:
      title: 'अध्याय ६ - श्लोक ९'
      subtitle: ''
      image: ''
      description: |-
        राजा को राष्ट्र के पापों का फल भोगना पड़ता है । राजा के पाप पुरोहित भोगता है । पत्नी के पाप उसके पति को भोगने पड़ते हैं और शिष्य के पाप गुरु भोगते हैं ।
    en:
      title: 'Chapter 6 - Verse 9'
      subtitle: ''
      image: ''
      description: |-
        The king is obliged to accept the sins of his subjects; the purohit (priest) suffers for those of the king; a husband suffers for those of his wife; and the guru suffers for those of his pupils.
- id: '10'
  type: leaf
  paginated: true
  meta:
    hi:
      title: 'अध्याय ६ - श्लोक १०'
      subtitle: ''
      image: ''
      description: |-
        ऋणी पिता अपनी संतान का शत्रु होता है । यही स्थिति बरे आचरण वाली माता की भी है । सुन्दर पत्नी अपने पति की और मूर्ख पुत्र अपने माता-पिता का शत्रु होता है ।
    en:
      title: 'Chapter 6 - Verse 10'
      subtitle: ''
      image: ''
      description: |-
        A father who is a chronic debtor, an adulterous mother, a beautiful wife, and an unlearned son are enemies (in one's own home).
- id: '11'
  type: leaf
  paginated: true
  meta:
    hi:
      title: 'अध्याय ६ - श्लोक ११'
      subtitle: ''
      image: ''
      description: |-
        लोभी को धन देकर, अभिमानी को हाथ जोड़कर, मूर्ख को उसकी इच्छा के अनुसार कार्य करके और विद्वान को सच्ची बात बताकर वश में करने का प्रयत्न करना चाहिए ।
    en:
      title: 'Chapter 6 - Verse 11'
      subtitle: ''
      image: ''
      description: |-
        Conciliate a covetous man by means of a gift, an obstinate man with folded hands in salutation, a fool by humouring him, and a learned man by truthful words.
- id: '12'
  type: leaf
  paginated: true
  meta:
    hi:
      title: 'अध्याय ६ - श्लोक १२'
      subtitle: ''
      image: ''
      description: |-
        बुरे राज्य की अपेक्षा किसी प्रकार का राज्य न होना अच्छा है, दुष्ट मित्रों के बजाय मित्र न होना अच्छा है, दुष्ट शिष्यों की जगह शिष्य न होना अधिक अच्छा है और दुष्ट पत्नी का पति कहलाने से अच्छा है कि पत्नी न हो ।
    en:
      title: 'Chapter 6 - Verse 12'
      subtitle: ''
      image: ''
      description: |-
        It is better to be without a kingdom than to rule over a petty one; better to be without a friend than to befriend a rascal; better to be without a disciple than to have a stupid one; and better to be without a wife than to have a bad one.
- id: '13'
  type: leaf
  paginated: true
  meta:
    hi:
      title: 'अध्याय ६ - श्लोक १३'
      subtitle: ''
      image: ''
      description: |-
        दुष्ट राजा के शासन में प्रजा को सुख नहीं मिल सकता, धोखेबाज मित्र से सुख की प्राप्ति नहीं हो सकती, दुष्ट स्त्री को पत्नी बनाने से घर में सुख और शांति नहीं रह सकती, इसी प्रकार खोटे शिष्य को विद्या दान देने वाले गुरु को भी अपयश ही मिलता है ।
    en:
      title: 'Chapter 6 - Verse 13'
      subtitle: ''
      image: ''
      description: |-
        How can people be made happy in a petty kingdom? What peace can we expect from a rascal friend? What happiness can we have at home in the company of a bad wife? How can renown be gained by instructing an unworthy disciple?
- id: '14'
  type: leaf
  paginated: true
  meta:
    hi:
      title: 'अध्याय ६ - श्लोक १४'
      subtitle: ''
      image: ''
      description: |-
        व्यक्ति को शेर और बगुले से एक-एक, मुर्गे से चार, कौए से पांच, कुत्ते से छह और गधे से तीन गुण सीखने चाहिए ।
    en:
      title: 'Chapter 6 - Verse 14'
      subtitle: ''
      image: ''
      description: |-
        Learn one thing from a lion; one from a crane; four from a cock; five from a crow; six from a dog; and three from an ass.
- id: '15'
  type: leaf
  paginated: true
  meta:
    hi:
      title: 'अध्याय ६ - श्लोक १५'
      subtitle: ''
      image: ''
      description: |-
        कार्य छोटा हो या बड़ा व्यक्ति को शुरू से ही उसमें पूरी शक्ति लगा देनी चाहिए, यह शिक्षा हम सिंह से ले सकते हैं ।
    en:
      title: 'Chapter 6 - Verse 15'
      subtitle: ''
      image: ''
      description: |-
        The one excellent thing that can be learned from a lion is that whatever a man intends doing should be done by him with a whole-hearted and strenuous effort.
- id: '16'
  type: leaf
  paginated: true
  meta:
    hi:
      title: 'अध्याय ६ - श्लोक १६'
      subtitle: ''
      image: ''
      description: |-
        बुद्धिमान व्यक्ति को अपनी इन्द्रियों को वश में करके समय के अनुरूप अपनी क्षमता को तौलकर बगुले के समान अपने कार्य को सिद्ध करना चाहिए ।
    en:
      title: 'Chapter 6 - Verse 16'
      subtitle: ''
      image: ''
      description: |-
        The wise man should restrain his senses like the crane and accomplish his purpose with due knowledge of his place, time and ability.
- id: '17'
  type: leaf
  paginated: true
  meta:
    hi:
      title: 'अध्याय ६ - श्लोक १७'
      subtitle: ''
      image: ''
      description: |-
        समय पर उठना, युद्ध के लिए सदा तैयार रहना, अपने बन्धुओं को उनका उचित हिस्सा देना और स्वयं आक्रमण करके भोजन करना मनुष्य को ये चार बातें मुर्गे से सीखनी चाहिए ।
    en:
      title: 'Chapter 6 - Verse 17'
      subtitle: ''
      image: ''
      description: |-
        To wake at the proper time; to take a bold stand and fight; to make a fair division (of property) among relations; and to earn one's own bread by personal exertion are the four excellent things to be learned from a cock.
- id: '18'
  type: leaf
  paginated: true
  meta:
    hi:
      title: 'अध्याय ६ - श्लोक १८'
      subtitle: ''
      image: ''
      description: |-
        छिपकर मैथुन करना, ढीठ होना, समय-समय पर कुछ वस्तुएं इकट्ठी करना, निरंतर सावधान रहना और किसी दूसरे पर पूरी तरह विश्वास नहीं करना, ये पांच बातें कौए से सीखने योग्य है ।
    en:
      title: 'Chapter 6 - Verse 18'
      subtitle: ''
      image: ''
      description: |-
        Union in privacy (with one's wife); boldness; storing away useful items; watchfulness; and not easily trusting others; these five things are to be learned from a crow.
- id: '19'
  type: leaf
  paginated: true
  meta:
    hi:
      title: 'अध्याय ६ - श्लोक १९'
      subtitle: ''
      image: ''
      description: |-
        बहुत भोजन करना लेकिन कम में भी संतुष्ट रहना, गहरी नींद लेकिन जल्दी से उठ बैठना, स्वामिभक्ति और बहादुरी ये छह गुण कुत्ते से सीखने चाहिए ।
    en:
      title: 'Chapter 6 - Verse 19'
      subtitle: ''
      image: ''
      description: |-
        Contentment with little or nothing to eat although one may have a great appetite; to awaken instantly although one may be in a deep slumber; unflinching devotion to the master; and bravery; these six qualities should be learned from the dog.
- id: '20'
  type: leaf
  paginated: true
  meta:
    hi:
      title: 'अध्याय ६ - श्लोक २०'
      subtitle: ''
      image: ''
      description: |-
        व्यक्ति को ये तीन बातें गधे से सीख लेनी चाहिए-अपने मालिक के लिए बोझ ढोना, सर्दी-गर्मी की चिंता नहीं करना तथा सदा संतोष से अपना जीवन बिताना ।
    en:
      title: 'Chapter 6 - Verse 20'
      subtitle: ''
      image: ''
      description: |-
        Although an ass is tired, he continues to carry his burden; he is unmindful of cold and heat; and he is always contented; these three things should be learned from the ass.
- id: '21'
  type: leaf
  paginated: true
  meta:
    hi:
      title: 'अध्याय ६ - श्लोक २१'
      subtitle: ''
      image: ''
      description: |-
        जो व्यक्ति इन बीस गुणों को सीख लेता है अर्थात इन्हें अपने आचरण में ले आता है, वह सब कार्यों और अवस्थाओं में विजयी होता है अर्थात उसे किसी भी अवस्था में पराजय का मुख नहीं देखना पड़ता ।
    en:
      title: 'Chapter 6 - Verse 21'
      subtitle: ''
      image: ''
      description: |-
        He who shall practice these twenty virtues shall become invincible in all his undertakings.
