- id: '1'
  type: 'leaf'
  paginated: true
  meta:
    hi:
      title: 'अध्याय १२ - श्लोक १'
      subtitle: ''
      image: ''
      description: |-
        अर्जुन ने पूछा - जो आपकी सेवा में सदैव तत्पर रहते हैं, या जो अव्यक्त निर्विशेष ब्रह्म की पूजा करते हैं, इन दोनों में से किसे अधिक पूर्ण (सिद्ध) माना जाय ?
    en:
      title: 'Chapter 12 - Verse 1'
      subtitle: ''
      image: ''
      description: |-
        Arjuna inquired: Which are considered to be more perfect, those who are always properly engaged in Your devotional service or those who worship the impersonal Brahman, the unmanifested?
- id: '2'
  type: 'leaf'
  paginated: true
  meta:
    hi:
      title: 'अध्याय १२ - श्लोक २'
      subtitle: ''
      image: ''
      description: |-
        श्रीभगवान् ने कहा - जो लोग अपने मन को मेरे साकार रूप में एकाग्र करते हैं, और अत्यन्त श्रद्धापूर्वक मेरी पूजा करने में सदैव लगे रहते हैं, वे मेरे द्वारा परम सिद्ध माने जाते हैं ।
    en:
      title: 'Chapter 12 - Verse 2'
      subtitle: ''
      image: ''
      description: |-
        The Supreme Personality of Godhead said: Those who fix their minds on My personal form and are always engaged in worshiping Me with great and transcendental faith are considered by Me to be most perfect.
- id: '3-4'
  type: 'leaf'
  paginated: true
  meta:
    hi:
      title: 'अध्याय १२ - श्लोक ३-४'
      subtitle: ''
      image: ''
      description: |-
        लेकिन जो लोग अपनी इन्द्रियों को वश में करके तथा सबों के प्रति समभाव रखकर परम सत्य की निराकार कल्पना के अन्तर्गत उस अव्यक्त की पूरी तरह से पूजा करते हैं, जो इन्द्रियों की अनुभूति के परे है, सर्वव्यापी है, अकल्पनीय है, अपरिवर्तनीय है, अचल तथा ध्रुव है, वे समस्त लोगों के कल्याण में संलग्न रहकर अन्ततः मुझे प्राप्त करते है ।
    en:
      title: 'Chapter 12 - Verse 3-4'
      subtitle: ''
      image: ''
      description: |-
        But those who fully worship the unmanifested, that which lies beyond the perception of the senses, the all-pervading, inconceivable, unchanging, fixed and immovable – the impersonal conception of the Absolute Truth – by controlling the various senses and being equally disposed to everyone, such persons, engaged in the welfare of all, at last achieve Me.
- id: '5'
  type: 'leaf'
  paginated: true
  meta:
    hi:
      title: 'अध्याय १२ - श्लोक ५'
      subtitle: ''
      image: ''
      description: |-
        जिन लोगों के मन परमेश्वर के अव्यक्त, निराकार स्वरूप के प्रति आसक्त हैं, उनके लिए प्रगति कर पाना अत्यन्त कष्टप्रद है । देहधारियों के लिए उस क्षेत्र में प्रगति कर पाना सदैव दुष्कर होता है ।
    en:
      title: 'Chapter 12 - Verse 5'
      subtitle: ''
      image: ''
      description: |-
        For those whose minds are attached to the unmanifested, impersonal feature of the Supreme, advancement is very troublesome. To make progress in that discipline is always difficult for those who are embodied.
- id: '6-7'
  type: 'leaf'
  paginated: true
  meta:
    hi:
      title: 'अध्याय १२ - श्लोक ६-७'
      subtitle: ''
      image: ''
      description: |-
        जो अपने सारे कार्यों को मुझमें अर्पित करके तथा अविचलित भाव से मेरी भक्ति करते हुए मेरी पूजा करते हैं और अपने चित्तों को मुझ पर स्थिर करके निरन्तर मेरा ध्यान करते हैं, उनके लिए हे पार्थ! मैं जन्म-मृत्यु के सागर से शीघ्र उद्धार करने वाला हूँ ।
    en:
      title: 'Chapter 12 - Verse 6-7'
      subtitle: ''
      image: ''
      description: |-
        But those who worship Me, giving up all their activities unto Me and being devoted to Me without deviation, engaged in devotional service and always meditating upon Me, having fixed their minds upon Me, O son of Pṛthā – for them I am the swift deliverer from the ocean of birth and death.
- id: '8'
  type: 'leaf'
  paginated: true
  meta:
    hi:
      title: 'अध्याय १२ - श्लोक ८'
      subtitle: ''
      image: ''
      description: |-
        मुझ भगवान् में अपने चित्त को स्थिर करो और अपनी सारी बुद्धि मुझमें लगाओ । इस प्रकार तुम निस्सन्देह मुझमें सदैव वास करोगे ।
    en:
      title: 'Chapter 12 - Verse 8'
      subtitle: ''
      image: ''
      description: |-
        Just fix your mind upon Me, the Supreme Personality of Godhead, and engage all your intelligence in Me. Thus you will live in Me always, without a doubt.
- id: '9'
  type: 'leaf'
  paginated: true
  meta:
    hi:
      title: 'अध्याय १२ - श्लोक ९'
      subtitle: ''
      image: ''
      description: |-
        हे अर्जुन, हे धनञ्जय! यदि तुम अपने चित्त को अविचल भाव से मुझ पर स्थिर नहीं कर सकते, तो तुम भक्तियोग के विधि-विधानों का पालन करो । इस प्रकार तुम मुझे प्राप्त करने की चाह उत्पन्न करो ।
    en:
      title: 'Chapter 12 - Verse 9'
      subtitle: ''
      image: ''
      description: |-
        My dear Arjuna, O winner of wealth, if you cannot fix your mind upon Me without deviation, then follow the regulative principles of bhakti-yoga. In this way develop a desire to attain Me.
- id: '10'
  type: 'leaf'
  paginated: true
  meta:
    hi:
      title: 'अध्याय १२ - श्लोक १०'
      subtitle: ''
      image: ''
      description: |-
        यदि तुम भक्तियोग के विधि-विधानों का भी अभ्यास नहीं कर सकते, तो मेरे लिए कर्म करने का प्रयत्न करो, क्योंकि मेरे लिए कर्म करने से तुम पूर्ण अवस्था (सिद्धि) को प्राप्त होगे ।
    en:
      title: 'Chapter 12 - Verse 10'
      subtitle: ''
      image: ''
      description: |-
        If you cannot practice the regulations of bhakti-yoga, then just try to work for Me, because by working for Me you will come to the perfect stage.
- id: '11'
  type: 'leaf'
  paginated: true
  meta:
    hi:
      title: 'अध्याय १२ - श्लोक ११'
      subtitle: ''
      image: ''
      description: |-
        किन्तु यदि तुम मेरे इस भावनामृत में कर्म करने में असमर्थ हो तो तुम अपने कर्म के समस्त फलों को त्याग कर कर्म करने का तथा आत्म-स्थित होने का प्रयत्न करो ।
    en:
      title: 'Chapter 12 - Verse 11'
      subtitle: ''
      image: ''
      description: |-
        If, however, you are unable to work in this consciousness of Me, then try to act giving up all results of your work and try to be self-situated.
- id: '12'
  type: 'leaf'
  paginated: true
  meta:
    hi:
      title: 'अध्याय १२ - श्लोक १२'
      subtitle: ''
      image: ''
      description: |-
        यदि तुम यह अभ्यास नहीं कर सकते, तो ज्ञान के अनुशीलन में लग जाओ । लेकिन ज्ञान से श्रेष्ठ ध्यान है और ध्यान से भी श्रेष्ठ है कर्म फलों का परित्याग क्योंकि ऐसे त्याग से मनुष्य को मनःशान्ति प्राप्त हो सकती है ।
    en:
      title: 'Chapter 12 - Verse 12'
      subtitle: ''
      image: ''
      description: |-
        If you cannot take to this practice, then engage yourself in the cultivation of knowledge. Better than knowledge, however, is meditation, and better than meditation is renunciation of the fruits of action, for by such renunciation one can attain peace of mind.
- id: '13-14'
  type: 'leaf'
  paginated: true
  meta:
    hi:
      title: 'अध्याय १२ - श्लोक १३-१४'
      subtitle: ''
      image: ''
      description: |-
        जो किसी से द्वेष नहीं करता, लेकिन सभी जीवों का दयालु मित्र है, जो अपने को स्वामी नहीं मानता और मिथ्या अहंकार से मुक्त है, जो सुख-दुख में समभाव रहता है, सहिष्णु है, सदैव आत्मतुष्ट रहता है, आत्मसंयमी है तथा जो निश्चय के साथ मुझमें मन तथा बुद्धि को स्थिर करके भक्ति में लगा रहता है, ऐसा भक्त मुझे अत्यन्त प्रिय है ।
    en:
      title: 'Chapter 12 - Verse 13-14'
      subtitle: ''
      image: ''
      description: |-
        One who is not envious but is a kind friend to all living entities, who does not think himself a proprietor and is free from false ego, who is equal in both happiness and distress, who is tolerant, always satisfied, self-controlled, and engaged in devotional service with determination, his mind and intelligence fixed on Me – such a devotee of Mine is very dear to Me.
- id: '15'
  type: 'leaf'
  paginated: true
  meta:
    hi:
      title: 'अध्याय १२ - श्लोक १५'
      subtitle: ''
      image: ''
      description: |-
        जिससे किसी को कष्ट नहीं पहुँचता तथा जो अन्य किसी के द्वारा विचलित नहीं किया जाता, जो सुख-दुख में, भय तथा चिन्ता में समभाव रहता है, वह मुझे अत्यन्त प्रिय है ।
    en:
      title: 'Chapter 12 - Verse 15'
      subtitle: ''
      image: ''
      description: |-
        He by whom no one is put into difficulty and who is not disturbed by anyone, who is equipoised in happiness and distress, fear and anxiety, is very dear to Me.
- id: '16'
  type: 'leaf'
  paginated: true
  meta:
    hi:
      title: 'अध्याय १२ - श्लोक १६'
      subtitle: ''
      image: ''
      description: |-
        मेरा ऐसा भक्त जो सामान्य कार्य-कलापों पर आश्रित नहीं है, जो शुद्ध है, दक्ष है, चिन्तारहित है, समस्त कष्टों से रहित है और किसी फल के लिए प्रयत्नशील नहीं रहता, मुझे अतिशय प्रिय है ।
    en:
      title: 'Chapter 12 - Verse 16'
      subtitle: ''
      image: ''
      description: |-
        My devotee who is not dependent on the ordinary course of activities, who is pure, expert, without cares, free from all pains, and not striving for some result, is very dear to Me.
- id: '17'
  type: 'leaf'
  paginated: true
  meta:
    hi:
      title: 'अध्याय १२ - श्लोक १७'
      subtitle: ''
      image: ''
      description: |-
        जो न कभी हर्षित होता है, न शोक करता है, जो न तो पछताता है, न इच्छा करता है, तथा जो शुभ तथा अशुभ दोनों प्रकार की वस्तुओं का परित्याग कर देता है, ऐसा भक्त मुझे अत्यन्त प्रिय है ।
    en:
      title: 'Chapter 12 - Verse 17'
      subtitle: ''
      image: ''
      description: |-
        One who neither rejoices nor grieves, who neither laments nor desires, and who renounces both auspicious and inauspicious things – such a devotee is very dear to Me.
- id: '18-19'
  type: 'leaf'
  paginated: true
  meta:
    hi:
      title: 'अध्याय १२ - श्लोक १८-१९'
      subtitle: ''
      image: ''
      description: |-
        जो मित्रों तथा शत्रुओं के लिए समान है, जो मान तथा अपमान, शीत तथा गर्मी, सुख तथा दुख, यश तथा अपयश में समभाव रखता है, जो दूषित संगति से सदैव मुक्त रहता है, जो सदैव मौन और किसी भी वस्तु से संतुष्ट रहता है, जो किसी प्रकार के घर-बार की परवाह नहीं करता, जो ज्ञान में दृढ़ है और जो भक्ति में संलग्न है - ऐसा पुरुष मुझे अत्यन्त प्रिय है ।
    en:
      title: 'Chapter 12 - Verse 18-19'
      subtitle: ''
      image: ''
      description: |-
        One who is equal to friends and enemies, who is equipoised in honor and dishonor, heat and cold, happiness and distress, fame and infamy, who is always free from contaminating association, always silent and satisfied with anything, who doesn’t care for any residence, who is fixed in knowledge and who is engaged in devotional service – such a person is very dear to Me.
- id: '20'
  type: 'leaf'
  paginated: true
  meta:
    hi:
      title: 'अध्याय १२ - श्लोक २०'
      subtitle: ''
      image: ''
      description: |-
        जो इस भक्ति के अमर पथ का अनुसरण करते हैं, और जो मुझे ही अपना चरम लक्ष्य बना कर श्रद्धासहित पूर्णरूपेण संलग्न रहते हैं, वे भक्त मुझे अत्यधिक प्रिय हैं ।
    en:
      title: 'Chapter 12 - Verse 20'
      subtitle: ''
      image: ''
      description: |-
        Those who follow this imperishable path of devotional service and who completely engage themselves with faith, making Me the supreme goal, are very, very dear to Me.
