- id: '1'
  type: 'leaf'
  paginated: true
  meta:
    hi:
      title: 'भाग - १'
      subtitle: ''
      image: ''
      description: 'मङ्गलाचरण'
    en:
      title: 'Part - 1'
      subtitle: ''
      image: ''
      description: 'Invocations'
- id: '2'
  type: 'leaf'
  paginated: true
  meta:
    hi:
      title: 'भाग - २'
      subtitle: ''
      image: ''
      description: 'श्रीरामजी से हनुमान् जी का मिलना और श्रीराम-सुग्रीव की मित्रता'
    en:
      title: 'Part - 2'
      subtitle: ''
      image: ''
      description: 'Śrī Rāma''s meeting with Hanumān and the conclusion of an alliance between Śrī Rāma and Sugrīva'
- id: '3'
  type: 'leaf'
  paginated: true
  meta:
    hi:
      title: 'भाग - ३'
      subtitle: ''
      image: ''
      description: 'सुग्रीव का दुःख सुनाना, बालि वध की प्रतिज्ञा, श्रीरामजी का मित्र-लक्षण-वर्णन, सुग्रीव का वैराग्य'
    en:
      title: 'Part - 3'
      subtitle: ''
      image: ''
      description: 'Sugrīva apprizes Śrī Rāma of his woes; the latter''s vow to kill Vāli; Śrī Rāma expatiates on the characteristics of a friend'
- id: '4'
  type: 'leaf'
  paginated: true
  meta:
    hi:
      title: 'भाग - ४'
      subtitle: ''
      image: ''
      description: 'बालि-सुग्रीव-युद्ध, बालि-उद्धार'
    en:
      title: 'Part - 4'
      subtitle: ''
      image: ''
      description: 'Duel between Vāli and Sugrīva; deliverance of Vāli'
- id: '5'
  type: 'leaf'
  paginated: true
  meta:
    hi:
      title: 'भाग - ५'
      subtitle: ''
      image: ''
      description: 'तारा का विलाप, तारा को श्रीरामजी द्वारा उपदेश और सुग्रीव का राज्याभिषेक तथा अङ्गद को युवराज पद'
    en:
      title: 'Part - 5'
      subtitle: ''
      image: ''
      description: 'Tārā''s wail; Śrī Rāma''s advice to Tārā and Sugrīva''s coronation and Aṅgada''s installation as his Heir- Apparent'
- id: '6'
  type: 'leaf'
  paginated: true
  meta:
    hi:
      title: 'भाग - ६'
      subtitle: ''
      image: ''
      description: 'वर्षा-ऋतु-वर्णन'
    en:
      title: 'Part - 6'
      subtitle: ''
      image: ''
      description: 'A description of the rainy season'
- id: '7'
  type: 'leaf'
  paginated: true
  meta:
    hi:
      title: 'भाग - ७'
      subtitle: ''
      image: ''
      description: 'शरद्-ऋतु-वर्णन'
    en:
      title: 'Part - 7'
      subtitle: ''
      image: ''
      description: 'Autumn Description'
- id: '8'
  type: 'leaf'
  paginated: true
  meta:
    hi:
      title: 'भाग - ८'
      subtitle: ''
      image: ''
      description: 'श्रीराम की सुग्रीव पर नाराजी, लक्ष्मणजी का कोप'
    en:
      title: 'Part - 8'
      subtitle: ''
      image: ''
      description: 'Śrī Rāma''s show of displeasure towards Sugrīva and Lakṣmaṇa''s wrath'
- id: '9'
  type: 'leaf'
  paginated: true
  meta:
    hi:
      title: 'भाग - ९'
      subtitle: ''
      image: ''
      description: 'सुग्रीव-राम-संवाद और सीताजी की खोज के लिये बंदरों का प्रस्थान'
    en:
      title: 'Part - 9'
      subtitle: ''
      image: ''
      description: 'Dialogue between Sugrīva and Śrī Rāma and the departure of the monkeys in quest of Sītā'
- id: '10'
  type: 'leaf'
  paginated: true
  meta:
    hi:
      title: 'भाग - १०'
      subtitle: ''
      image: ''
      description: 'गुफा में तपस्विनी के दर्शन, वानरों का समुद्र तट पर आना, सम्पाती से भेंट और बातचीत'
    en:
      title: 'Part - 10'
      subtitle: ''
      image: ''
      description: 'The monkeys'' arrival at the seashore; their meeting and conversation with Sampātī (Jaṭāyu''s brother)'
- id: '11'
  type: 'leaf'
  paginated: true
  meta:
    hi:
      title: 'भाग - ११'
      subtitle: ''
      image: ''
      description: 'समुद्र लाँघने का परामर्श, जाम्बवन्त का हनुमान् जी को बल याद दिलाकर उत्साहित करना, श्रीराम-गुण का माहात्म्य'
    en:
      title: 'Part - 11'
      subtitle: ''
      image: ''
      description: 'Sampātī''ss advice to the monkeys to leap across the ocean; Jāmbavān encourages Hanumān by reminding him of his strength'
