- id: '1'
  type: leaf
  paginated: true
  meta:
    hi:
      title: 'अध्याय १७ - श्लोक १'
      subtitle: ''
      image: ''
      description: |-
        जिन व्यक्तियों ने गुरु के पास बैठकर विद्या का अध्ययन नहीं किया वरन् पुस्तकों से ही ज्ञान प्राप्त किया है, वह विद्वान लोगों की सभा में उसी तरह सम्मान प्राप्त नहीं करते, जिस प्रकार दुष्कर्म से गर्भ धारण करने वाली स्त्री का समाज में सम्मान नहीं होता ।
    en:
      title: 'Chapter 17 - Verse 1'
      subtitle: ''
      image: ''
      description: |-
        The scholar who has acquired knowledge by studying innumerable books without the blessings of a bonafide spiritual master does not shine in an assembly of truly learned men just as an illegitimate child is not honoured in society.
- id: '2'
  type: leaf
  paginated: true
  meta:
    hi:
      title: 'अध्याय १७ - श्लोक २'
      subtitle: ''
      image: ''
      description: |-
        जो जैसा करे, उससे वैसा बरतें । कृतज्ञ के प्रति कृतज्ञता भरा, हिंसक (दुष्ट) के साथ हिंसायुक्त और दुष्ट से दुष्टताभरा व्यवहार करने में किसी प्रकार का पाप (पातक) नहीं है ।
    en:
      title: 'Chapter 17 - Verse 2'
      subtitle: ''
      image: ''
      description: |-
        We should repay the favours of others by acts of kindness; so also should we return evil for evil in which there is no sin, for it is necessary to pay a wicked man in his own coin.
- id: '3'
  type: leaf
  paginated: true
  meta:
    hi:
      title: 'अध्याय १७ - श्लोक ३'
      subtitle: ''
      image: ''
      description: |-
        जो वस्तु अत्यंत दूर है, जिसकी आराधना करना अत्यंत कठिन है और जो अत्यंत ऊंचे स्थान पर स्थित है, ऐसी चीजों को तप द्वारा ही सिद्ध किया जा सकता है । सिद्धि का प्रयोग यह प्राप्त करना भी है ।
    en:
      title: 'Chapter 17 - Verse 3'
      subtitle: ''
      image: ''
      description: |-
        That thing which is distant, that thing which appears impossible, and that which is far beyond our reach, can be easily attained through Tapasyā (religious austerity), for nothing can surpass austerity.
- id: '4'
  type: leaf
  paginated: true
  meta:
    hi:
      title: 'अध्याय १७ - श्लोक ४'
      subtitle: ''
      image: ''
      description: |-
        यदि मनुष्य में लोभ है तो उसे किसी अन्य बुराई की आवश्यकता नहीं । यदि व्यक्ति चुगलखोर है तो इससे बढ़कर और क्या पाप हो सकता है ? यदि उसके जीवन में सत्यवादिता, सत्याचरण आदि गुण हैं तो उसे तप करने की क्या आवश्यकता है ? यदि मनुष्य का मन पवित्र है तो विभिन्न तीर्थों पर जाकर वहां स्नान करने से क्या लाभ ? यदि मनुष्य में प्रेम है तो उसे अन्य गुणों की क्या आवश्यकता है ? यदि संसार में उसका यश फैल रहा है तो उसे अन्य किसी आभूषण की क्या आवश्यकता है ? अर्थात उसे अपने शरीर को सजाने के लिए आभूषण की आवश्यकता नहीं है, यदि उसके पास उत्तम विद्या है तो उसे किसी अन्य धन की क्या आवश्यकता है और यदि उसका अपयश फैल रहा है तो उसे मृत्यु से क्या लेना-देना ? वह जीते जी मृत के समान है ।
    en:
      title: 'Chapter 17 - Verse 4'
      subtitle: ''
      image: ''
      description: |-
        What vice could be worse than covetousness? What is more sinful than slander? For one who is truthful, what need is there for austerity? For one who has a clean heart, what is the need for pilgrimage? If one has a good disposition, what other virtue is needed? If a man has fame, what is the value of other ornamentation? What need is there for wealth for the man of practical knowledge? And if a man is dishonoured, what could there be worse in death?
- id: '5'
  type: leaf
  paginated: true
  meta:
    hi:
      title: 'अध्याय १७ - श्लोक ५'
      subtitle: ''
      image: ''
      description: |-
        समुद्र शंख का पिता है । लक्ष्मी का जन्म भी समुद्र में हुआ है अर्थात वह शंख की बहन है । शंख चंद्रमा के समान चमकता है, इतने पर भी यदि कोई शंख बजाकर भीख मांगता है तो यही समझना चाहिए कि दान दिए बिना मान-सम्मान नहीं होता ।
    en:
      title: 'Chapter 17 - Verse 5'
      subtitle: ''
      image: ''
      description: |-
        Though the sea, which is the reservoir of all jewels, is the father of the conch shell, and the Goddess of fortune Lakṣmī is conch's sister, still the conch must go from door to door for alms (in the hands of a beggar). It is true, therefore, that one gains nothing without having given in the past.
- id: '6'
  type: leaf
  paginated: true
  meta:
    hi:
      title: 'अध्याय १७ - श्लोक ६'
      subtitle: ''
      image: ''
      description: |-
        शक्तिहीन व्यक्ति सज्जन, निर्धन ब्रह्मचारी, रोगी देवार्चन करने वाला और बूढ़ी स्त्री पतिव्रता बन जाती है ।
    en:
      title: 'Chapter 17 - Verse 6'
      subtitle: ''
      image: ''
      description: |-
        When a man has no strength left in him he becomes a Sādhu, one without wealth acts like a Brahmacārī, a sick man behaves like a devotee of the Lord, and when a woman grows old she becomes devoted to her husband.
- id: '7'
  type: leaf
  paginated: true
  meta:
    hi:
      title: 'अध्याय १७ - श्लोक ७'
      subtitle: ''
      image: ''
      description: |-
        अन्न और जल के समान कोई श्रेष्ठ दान नहीं, द्वादशी के समान कोई श्रेष्ठ तिथि नहीं, गायत्री से बढ़कर कोई मंत्र नहीं और माता से बढ़कर कोई देवता नहीं ।
    en:
      title: 'Chapter 17 - Verse 7'
      subtitle: ''
      image: ''
      description: |-
        There is no better gift than offering food and water, no auspicious date like Dwadashi, no mantra greater than Gayatri, and no god greater than mother.
- id: '8'
  type: leaf
  paginated: true
  meta:
    hi:
      title: 'अध्याय १७ - श्लोक ८'
      subtitle: ''
      image: ''
      description: |-
        सांप का विष उसके दांत में होता है, मक्खी का विष उसके मुह में रहता है, बिच्छू का विष उसकी पूंछ में होता है अर्थात इन सभी विषैले प्राणियों के एक-एक अंग में ही विष होता है, लेकिन दुर्जन मनुष्य के सभी अंग विष से भरे हुए होते हैं ।
    en:
      title: 'Chapter 17 - Verse 8'
      subtitle: ''
      image: ''
      description: |-
        There is poison in the fang of the serpent, in the mouth of the fly and in the sting of a scorpion; but the wicked man is saturated with it.
- id: '9'
  type: leaf
  paginated: true
  meta:
    hi:
      title: 'अध्याय १७ - श्लोक ९'
      subtitle: ''
      image: ''
      description: |-
        पति की आज्ञा के बिना जो स्त्री उपवास रूपी व्रत करती है, वह अपने पति की आयु को कम करने वाली होती है । वह स्त्री नरक में जाती है, उसे महान कष्ट भोगने पड़ते हैं ।
    en:
      title: 'Chapter 17 - Verse 9'
      subtitle: ''
      image: ''
      description: |-
        The woman who fasts and observes religious vows without the permission of her husband shortens his life, and goes to hell.
- id: '10'
  type: leaf
  paginated: true
  meta:
    hi:
      title: 'अध्याय १७ - श्लोक १०'
      subtitle: ''
      image: ''
      description: |-
        स्त्री अनेक प्रकार के दान करने से शुद्ध नहीं होती अर्थात मोक्ष प्राप्त नहीं कर सकती, सैकड़ों उपवास करने से भी वह शुद्ध नहीं होती, अनेक तीर्थों की यात्रा करने के बाद भी वह शुद्ध नहीं होती, वह तो केवल पति के चरणों की सेवा से ही शुद्ध हो सकती है अर्थात मोक्ष प्राप्त कर सकती है ।
    en:
      title: 'Chapter 17 - Verse 10'
      subtitle: ''
      image: ''
      description: |-
        A woman does not become holy by offering by charity, by observing hundreds of fasts, or by sipping sacred water, as by sipping the water used to wash her husbands feet.
- id: '11'
  type: leaf
  paginated: true
  meta:
    hi:
      title: 'अध्याय १७ - श्लोक ११'
      subtitle: ''
      image: ''
      description: |-
        हाथ की शोभा कगंन पहनने से नहीं वरन् दान आदि देने से होती है । शरीर की शुद्धि स्नान करने से होती है, चंदन लगाने से नहीं । मनुष्य की तृप्ति आदर-सम्मान से होती है, भोजन से नहीं और मनुष्य को मोक्ष ज्ञान से होता है, चंदन आदि के तिलक लगाने से नहीं ।
    en:
      title: 'Chapter 17 - Verse 11'
      subtitle: ''
      image: ''
      description: |-
        The hand is not so well adorned by ornaments as by charitable offerings; one does not become clean by smearing sandalwood paste upon the body as by taking a bath; one does not become so much satisfied by dinner as by having respect shown to him; and salvation is not attained by self-adornment as by cultivation of spiritual knowledge.
- id: '12'
  type: leaf
  paginated: true
  meta:
    hi:
      title: 'अध्याय १७ - श्लोक १२'
      subtitle: ''
      image: ''
      description: |-
        नाई के घर पर जाकर बाल बनाना, पत्थर पर चन्दन आदि सुगन्धित द्रव्य लगाना और अपने रूप, प्रतिबिम्ब को जल में देखना ये कार्य इन्द्र की शोभा को भी नष्ट कर देते हैं ।
    en:
      title: 'Chapter 17 - Verse 12'
      subtitle: ''
      image: ''
      description: |-
        Going to the barber making hair, applying scented substances like sandalwood on a stone and seeing one's own form and reflection in water, these acts also destroy the beauty of Indra.
- id: '13'
  type: leaf
  paginated: true
  meta:
    hi:
      title: 'अध्याय १७ - श्लोक १३'
      subtitle: ''
      image: ''
      description: |-
        इकुंदरु खाने से तत्काल मनुष्य की बुद्धि नष्ट होती है, वच खाने से तत्काल बुद्धि बढ़ती है, नारी शीघ्र ही शक्ति का हरण करती है और दूध पीने से उसी क्षण बल प्राप्त होता है ।
    en:
      title: 'Chapter 17 - Verse 13'
      subtitle: ''
      image: ''
      description: |-
        The eating of tundi fruit deprives a man of his sense, while the vacha root administered revives his reasoning immediately. A woman at once robs a man of his vigour while milk at once restores it.
- id: '14'
  type: leaf
  paginated: true
  meta:
    hi:
      title: 'अध्याय १७ - श्लोक १४'
      subtitle: ''
      image: ''
      description: |-
        जिन सज्जन लोगों के दिल में दूसरों का उपकार करने की भावना जाग्रत रहती है, उनकी विपत्तियां नष्ट हो जाती हैं और पग-पग पर उन्हें धन-संपत्ति की प्राप्ति होती है ।
    en:
      title: 'Chapter 17 - Verse 14'
      subtitle: ''
      image: ''
      description: |-
        He who nurtures benevolence for all creatures within his heart overcomes all difficulties and will be the recipient of all types of riches at every step.
- id: '15'
  type: leaf
  paginated: true
  meta:
    hi:
      title: 'अध्याय १७ - श्लोक १५'
      subtitle: ''
      image: ''
      description: |-
        भोजन करना, नींद लेना, भयभीत होना और मैथुन अर्थात संतान की उत्पत्ति करना, ये सब बातें मनुष्य और पशु में एक जैसी होती हैं । मनुष्य में पशुओं की अपेक्षा धर्म ही ऐसी विशेष वस्तु है जो उनसे अधिक होती है । यदि मनुष्य में धर्म न हो तो वह पशु के समान है ।
    en:
      title: 'Chapter 17 - Verse 15'
      subtitle: ''
      image: ''
      description: |-
        Men have eating, sleeping, fearing and mating in common with the lower animals. That in which men excel the beasts is discretionary knowledge; hence, indiscreet men who are without knowledge should be regarded as beasts.
- id: '16'
  type: leaf
  paginated: true
  meta:
    hi:
      title: 'अध्याय १७ - श्लोक १६'
      subtitle: ''
      image: ''
      description: |-
        यदि मद में अंधा हाथी अपनी मंदबुद्धि के कारण अपने मस्तक पर बैठे हुए मद पीने के इच्छुक भौंरों को अपने कान फड़फड़ाकर दूर भगा देता है तो इसमें भौंरों की कोई हानि नहीं होती । वे जाकर खिले हुए कमलों पर जा बैठते हैं, उन्हें वहां से रस मिल जाता है, परंतु ऐसा करने से हाथी के गण्डस्थल की ही शोभा नष्ट होती है ।
    en:
      title: 'Chapter 17 - Verse 16'
      subtitle: ''
      image: ''
      description: |-
        If the bees which seek the liquid oozing from the head of a lustintoxicated elephant are driven away by the flapping of his ears, then the elephant has lost only the ornament of his head. The bees are quite happy in the lotus filled lake.
- id: '17'
  type: leaf
  paginated: true
  meta:
    hi:
      title: 'अध्याय १७ - श्लोक १७'
      subtitle: ''
      image: ''
      description: |-
        राजा, वेश्या, यमराज, अग्नि, चोर, बालक, याचक और ग्रामीणों को सताने वाले - ये आठों बड़े ही कठोर होते हैं । ये दूसरों के कष्टों को नहीं समझते ।
    en:
      title: 'Chapter 17 - Verse 17'
      subtitle: ''
      image: ''
      description: |-
        A king, a prostitute, Lord Yamarāja, fire, a thief, a young boy, and a beggar cannot understand the suffering of others. The eighth of this category are the tax collector.
- id: '18'
  type: leaf
  paginated: true
  meta:
    hi:
      title: 'अध्याय १७ - श्लोक १८'
      subtitle: ''
      image: ''
      description: |-
        किसी अत्यंत बूढ़ी स्त्री को, जिसकी कमर बुढ़ापे के कारण झुक गई थी, देखकर कोई युवक व्यंग्य करते हुए पूछने लगा हे वृद्धे! नीचे क्या ढूंढ़ रही हो ? क्या पृथ्वी पर तुम्हारी कोई चीज गिरी पड़ी है ? तुम्हारा कुछ खो तो नहीं गया ? उस व्यंग्य को सुनकर बूढ़ी औरत ने कहा कि अरे मूर्ख! तू नहीं जानता कि मेरा यौवनरूपी मोती खो गया है । मैं उसी को ढूंढ़ रही हूं ।
    en:
      title: 'Chapter 17 - Verse 18'
      subtitle: ''
      image: ''
      description: |-
        Seeing a very old woman, who is bent down due to old age, a young man satirically asked - O lady, why are you gazing downward? Has something of yours fallen on the ground? (She replies) O fool, can you not understand the pearl of my youth has slipped away?
- id: '19'
  type: leaf
  paginated: true
  meta:
    hi:
      title: 'अध्याय १७ - श्लोक १९'
      subtitle: ''
      image: ''
      description: |-
        हे केतकी! तुझसे सांप लिपटे रहते हैं, फल भी नहीं लगते, कांटे भी हैं और वक्रता भी है । इसके अतिरिक्त तेरा जन्म कीचड़ में होता है और तू सरलता से प्राप्त भी नहीं होती । इतना सब कुछ होने पर भी तेरे में जो गंध है, वह सब प्राणियों को मोह लेती है ।
    en:
      title: 'Chapter 17 - Verse 19'
      subtitle: ''
      image: ''
      description: |-
        O ketki flower! Serpents live in your midst, you bear no edible fruits, your leaves are covered with thorns, you are crooked in growth, you thrive in mud, and you are not easily accessible. Still for your exceptional fragrance you are as dear as a kinsmen to others. Hence, a single excellence overcomes a multitude of blemishes.
