- id: '1'
  type: 'leaf'
  paginated: true
  meta:
    hi:
      title: 'भाग - १'
      subtitle: ''
      image: ''
      description: 'मङ्गलाचरण'
    en:
      title: 'Part - 1'
      subtitle: ''
      image: ''
      description: 'Invocations'
- id: '2'
  type: 'leaf'
  paginated: true
  meta:
    hi:
      title: 'भाग - २'
      subtitle: ''
      image: ''
      description: 'हनुमान् जी लङ्का को प्रस्थान, सुरसा से भेंट, छाया पकड़ने वाली राक्षसी का वध'
    en:
      title: 'Part - 2'
      subtitle: ''
      image: ''
      description: 'Hanumān leaves for Laṅkā, meets Surasa and kills the image-catching demoness'
- id: '3'
  type: 'leaf'
  paginated: true
  meta:
    hi:
      title: 'भाग - ३'
      subtitle: ''
      image: ''
      description: 'लङ्का वर्णन, लङ्किनी पर प्रहार, लङ्का में प्रवेश'
    en:
      title: 'Part - 3'
      subtitle: ''
      image: ''
      description: 'Description of Laṅkā; Hanumān strikes Laṅkinī and enters Laṅkā'
- id: '4'
  type: 'leaf'
  paginated: true
  meta:
    hi:
      title: 'भाग - ४'
      subtitle: ''
      image: ''
      description: 'हनुमान्-विभीषण-संवाद'
    en:
      title: 'Part - 4'
      subtitle: ''
      image: ''
      description: 'Hanumān meets Vibhīṣaṇa'
- id: '5'
  type: 'leaf'
  paginated: true
  meta:
    hi:
      title: 'भाग - ५'
      subtitle: ''
      image: ''
      description: 'हनुमान् जी अशोक-वाटिका में सीता को देखकर दुखी होना और रावण का सीताजी को भय दिखलाना'
    en:
      title: 'Part - 5'
      subtitle: ''
      image: ''
      description: 'Hanumān''s grief at the sight of Sītā in the Aśoka grove and Rāvaṇa''s threat to Sītā'
- id: '6'
  type: 'leaf'
  paginated: true
  meta:
    hi:
      title: 'भाग - ६'
      subtitle: ''
      image: ''
      description: 'श्रीसीता-त्रिजटा-संवाद'
    en:
      title: 'Part - 6'
      subtitle: ''
      image: ''
      description: 'Dialogue between Sītā and Trijaṭā'
- id: '7'
  type: 'leaf'
  paginated: true
  meta:
    hi:
      title: 'भाग - ७'
      subtitle: ''
      image: ''
      description: 'श्रीसीता-हनुमान्-संवाद'
    en:
      title: 'Part - 7'
      subtitle: ''
      image: ''
      description: 'Dialogue between Sītā and Hanumān'
- id: '8'
  type: 'leaf'
  paginated: true
  meta:
    hi:
      title: 'भाग - ८'
      subtitle: ''
      image: ''
      description: 'हनुमानजी द्वारा अशोक-वाटिका-विध्वंस, अक्षय-कुमार-वध और मेघनाद का हनुमान् जी को नागपाश में बाँधकर सभा में ले जाना'
    en:
      title: 'Part - 8'
      subtitle: ''
      image: ''
      description: 'Hanumān lays waste the Aśoka grove and kills prince Aksaya; at last Meghanāda entangles Hanumān in a noose of serpents and carries him off to Rāvaṇa''s court'
- id: '9'
  type: 'leaf'
  paginated: true
  meta:
    hi:
      title: 'भाग - ९'
      subtitle: ''
      image: ''
      description: 'हनुमान्-रावण-संवाद'
    en:
      title: 'Part - 9'
      subtitle: ''
      image: ''
      description: 'Dialogue between Hanumān and Rāvaṇa'
- id: '10'
  type: 'leaf'
  paginated: true
  meta:
    hi:
      title: 'भाग - १०'
      subtitle: ''
      image: ''
      description: 'लङ्का दहन'
    en:
      title: 'Part - 10'
      subtitle: ''
      image: ''
      description: 'Burning of Laṅkā'
- id: '11'
  type: 'leaf'
  paginated: true
  meta:
    hi:
      title: 'भाग - ११'
      subtitle: ''
      image: ''
      description: 'लङ्का जलाने के बाद हनुमान् जी का सीताजी से विदा माँगना और चूड़ामणि पाना'
    en:
      title: 'Part - 11'
      subtitle: ''
      image: ''
      description: 'After burning Laṅkā Hanumān asks leave of Sītā and obtains the crest-jewel from Her'
- id: '12'
  type: 'leaf'
  paginated: true
  meta:
    hi:
      title: 'भाग - १२'
      subtitle: ''
      image: ''
      description: 'समुद्र के इस पार आना, सबका लौटना, मधुवन प्रवेश, सुग्रीव-मिलन, श्रीराम-हनुमान्-संवाद'
    en:
      title: 'Part - 12'
      subtitle: ''
      image: ''
      description: 'On Hanumān''s reaching the opposite shore all the monkeys return and enter Madhuvana; their meeting with Sugrīva and the dialogue between Śrī Rāma and Hanumān'
- id: '13'
  type: 'leaf'
  paginated: true
  meta:
    hi:
      title: 'भाग - १३'
      subtitle: ''
      image: ''
      description: 'श्रीरामजी का वानरों की सेना के साथ चलकर समुद्र तट पर पहुँचना'
    en:
      title: 'Part - 13'
      subtitle: ''
      image: ''
      description: 'Śrī Rāma''s march to the beach alongwith the army of monkeys'
- id: '14'
  type: 'leaf'
  paginated: true
  meta:
    hi:
      title: 'भाग - १४'
      subtitle: ''
      image: ''
      description: 'मंदोदरी-रावण-संवाद'
    en:
      title: 'Part - 14'
      subtitle: ''
      image: ''
      description: 'Dialogue between Mandodarī and Rāvaṇa'
- id: '15'
  type: 'leaf'
  paginated: true
  meta:
    hi:
      title: 'भाग - १५'
      subtitle: ''
      image: ''
      description: 'रावण को विभीषण का समझाना और विभीषण का अपमान'
    en:
      title: 'Part - 15'
      subtitle: ''
      image: ''
      description: 'Vibhīṣaṇa offers advice to Rāvaṇa and meets with an affront at the latter''s hands'
- id: '16'
  type: 'leaf'
  paginated: true
  meta:
    hi:
      title: 'भाग - १६'
      subtitle: ''
      image: ''
      description: 'विभीषण का भगवान् श्रीरामजी की शरण के लिये प्रस्थान और शरण प्राप्ति'
    en:
      title: 'Part - 16'
      subtitle: ''
      image: ''
      description: 'Vibhīṣaṇa sallies forth to obtain Śrī Rāma''s protection and secures it'
- id: '17'
  type: 'leaf'
  paginated: true
  meta:
    hi:
      title: 'भाग - १७'
      subtitle: ''
      image: ''
      description: 'समुद्र पार करने के लिये विचार, रावण दूत शुक का आना और लक्ष्मणजी के पत्र को लेकर लौटना'
    en:
      title: 'Part - 17'
      subtitle: ''
      image: ''
      description: 'Deliberation over the question of crossing the sea; appearance of Śuka, a spy of Rāvaṇa, and his return with Lakṣmaṇa''s letter'
- id: '18'
  type: 'leaf'
  paginated: true
  meta:
    hi:
      title: 'भाग - १८'
      subtitle: ''
      image: ''
      description: 'दूत का रावण को समझाना और लक्ष्मणजी का पत्र देना'
    en:
      title: 'Part - 18'
      subtitle: ''
      image: ''
      description: 'The spy gives counsel to Rāvaṇa and delivers Lakṣmaṇa''s note to him'
- id: '19'
  type: 'leaf'
  paginated: true
  meta:
    hi:
      title: 'भाग - १९'
      subtitle: ''
      image: ''
      description: 'समुद्र पर श्रीरामजी का क्रोध और समुद्र की विनती, श्रीरामगुणगान की महिमा'
    en:
      title: 'Part - 19'
      subtitle: ''
      image: ''
      description: 'Śrī Rāma''s fury against the sea and the latter''s supplication'
