- id: '1'
  type: 'leaf'
  paginated: true
  meta:
    hi:
      title: 'अध्याय १५ - श्लोक १'
      subtitle: ''
      image: ''
      description: |-
        भगवान् ने कहा - कहा जाता है कि एक शाश्वत अश्वत्थ वृक्ष है, जिसकी जड़ें तो ऊपर की ओर हैं और शाखाएँ नीचे की ओर तथा पत्तियाँ वैदिक स्तोत्र हैं । जो इस वृक्ष को जानता है, वह वेदों का ज्ञाता है ।
    en:
      title: 'Chapter 15 - Verse 1'
      subtitle: ''
      image: ''
      description: |-
        The Supreme Personality of Godhead said: It is said that there is an imperishable banyan tree that has its roots upward and its branches down and whose leaves are the Vedic hymns. One who knows this tree is the knower of the Vedas.
- id: '2'
  type: 'leaf'
  paginated: true
  meta:
    hi:
      title: 'अध्याय १५ - श्लोक २'
      subtitle: ''
      image: ''
      description: |-
        इस वृक्ष की शाखाएँ ऊपर तथा नीचे फैली हुई हैं और प्रकृति के तीन गुणों द्वारा पोषित हैं । इसकी टहनियाँ इन्द्रियविषय हैं । इस वृक्ष की जड़ें नीचे की ओर भी जाती हैं, जो मानवसमाज के सकाम कर्मों से बँधी हुई हैं ।
    en:
      title: 'Chapter 15 - Verse 2'
      subtitle: ''
      image: ''
      description: |-
        The branches of this tree extend downward and upward, nourished by the three modes of material nature. The twigs are the objects of the senses. This tree also has roots going down, and these are bound to the fruitive actions of human society.
- id: '3-4'
  type: 'leaf'
  paginated: true
  meta:
    hi:
      title: 'अध्याय १५ - श्लोक ३-४'
      subtitle: ''
      image: ''
      description: |-
        इस वृक्ष के वास्तविक स्वरूप का अनुभव इस जगत् में नहीं किया जा सकता । कोई भी नहीं समझ सकता कि इसका आदि कहाँ है, अन्त कहाँ है या इसका आधार कहाँ है ? लेकिन मनुष्य को चाहिए कि इस दृढ़ मूल वाले वृक्ष को विरक्ति के शस्त्र से काट गिराए । तत्पश्चात् उसे ऐसे स्थान की खोज करनी चाहिए जहाँ जाकर लौटना न पड़े और जहाँ उस भगवान् की शरण ग्रहण कर ली जाये, जिससे अनादि काल से प्रत्येक वस्तु का सूत्रपात तथा विस्तार होता आया है ।
    en:
      title: 'Chapter 15 - Verse 3-4'
      subtitle: ''
      image: ''
      description: |-
        The real form of this tree cannot be perceived in this world. No one can understand where it ends, where it begins, or where its foundation is. But with determination one must cut down this strongly rooted tree with the weapon of detachment. Thereafter, one must seek that place from which, having gone, one never returns, and there surrender to that Supreme Personality of Godhead from whom everything began and from whom everything has extended since time immemorial.
- id: '5'
  type: 'leaf'
  paginated: true
  meta:
    hi:
      title: 'अध्याय १५ - श्लोक ५'
      subtitle: ''
      image: ''
      description: |-
        जो झूठी प्रतिष्ठा, मोह तथा कुसंगति से मुक्त हैं, जो शाश्वत तत्त्व को समझते हैं, जिन्होंने भौतिक काम को नष्ट कर दिया है, जो सुख तथा दुख के द्वन्द्व से मुक्त हैं और जो मोहरहित होकर परम पुरुष के शरणागत होना जानते हैं, वे उस शाश्वत राज्य को प्राप्त होते हैं ।
    en:
      title: 'Chapter 15 - Verse 5'
      subtitle: ''
      image: ''
      description: |-
        Those who are free from false prestige, illusion and false association, who understand the eternal, who are done with material lust, who are freed from the dualities of happiness and distress, and who, unbewildered, know how to surrender unto the Supreme Person attain to that eternal kingdom.
- id: '6'
  type: 'leaf'
  paginated: true
  meta:
    hi:
      title: 'अध्याय १५ - श्लोक ६'
      subtitle: ''
      image: ''
      description: |-
        वह मेरा परम धाम न तो सूर्य या चन्द्र के द्वारा प्रकाशित होता है और न अग्नि या बिजली से । जो लोग वहाँ पहुँच जाते हैं, वे इस भौतिक जगत् में फिर से लौट कर नहीं आते ।
    en:
      title: 'Chapter 15 - Verse 6'
      subtitle: ''
      image: ''
      description: |-
        That supreme abode of Mine is not illumined by the sun or moon, nor by fire or electricity. Those who reach it never return to this material world.
- id: '7'
  type: 'leaf'
  paginated: true
  meta:
    hi:
      title: 'अध्याय १५ - श्लोक ७'
      subtitle: ''
      image: ''
      description: |-
        इस बद्ध जगत् में सारे जीव मेरे शाश्वत अंश हैं । बद्ध जीवन के कारण वे छहों इन्द्रियों से घोर संघर्ष कर रहे हैं, जिनमें मन भी सम्मिलित है ।
    en:
      title: 'Chapter 15 - Verse 7'
      subtitle: ''
      image: ''
      description: |-
        The living entities in this conditioned world are My eternal fragmental parts. Due to conditioned life, they are struggling very hard with the six senses, which include the mind.
- id: '8'
  type: 'leaf'
  paginated: true
  meta:
    hi:
      title: 'अध्याय १५ - श्लोक ८'
      subtitle: ''
      image: ''
      description: |-
        इस संसार में जीव अपनी देहात्मबुद्धि को एक शरीर से दूसरे में उसी तरह ले जाता है, जिस तरह वायु सुगन्धि को ले जाता है । इस प्रकार वह एक शरीर धारण करता है और फिर इसे त्याग कर दूसरा शरीर धारण करता है ।
    en:
      title: 'Chapter 15 - Verse 8'
      subtitle: ''
      image: ''
      description: |-
        The living entity in the material world carries his different conceptions of life from one body to another, as the air carries aromas. Thus he takes one kind of body and again quits it to take another.
- id: '9'
  type: 'leaf'
  paginated: true
  meta:
    hi:
      title: 'अध्याय १५ - श्लोक ९'
      subtitle: ''
      image: ''
      description: |-
        इस प्रकार दूसरा स्थूल शरीर धारण करके जीव विशेष प्रकार का कान, आँख, जीभ, नाक तथा स्पर्श इन्द्रिय (त्वचा) प्राप्त करता है, जो मन के चारों ओर संपुंजित हैं । इस प्रकार वह इन्द्रियविषयों के एक विशिष्ट समुच्चय का भोग करता है ।
    en:
      title: 'Chapter 15 - Verse 9'
      subtitle: ''
      image: ''
      description: |-
        The living entity, thus taking another gross body, obtains a certain type of ear, eye, tongue, nose and sense of touch, which are grouped about the mind. He thus enjoys a particular set of sense objects.
- id: '10'
  type: 'leaf'
  paginated: true
  meta:
    hi:
      title: 'अध्याय १५ - श्लोक १०'
      subtitle: ''
      image: ''
      description: |-
        मूर्ख न तो समझ पाते हैं कि जीव किस प्रकार अपना शरीर त्याग सकता है, न ही वे यह समझ पाते हैं कि प्रकृति के गुणों के अधीन वह किस तरह के शरीर का भोग करता है । लेकिन जिसकी आँखें ज्ञान में प्रशिक्षित होती हैं, वह यह सब देख सकता है ।
    en:
      title: 'Chapter 15 - Verse 10'
      subtitle: ''
      image: ''
      description: |-
        The foolish cannot understand how a living entity can quit his body, nor can they understand what sort of body he enjoys under the spell of the modes of nature. But one whose eyes are trained in knowledge can see all this.
- id: '11'
  type: 'leaf'
  paginated: true
  meta:
    hi:
      title: 'अध्याय १५ - श्लोक ११'
      subtitle: ''
      image: ''
      description: |-
        आत्म-साक्षात्कार को प्राप्त प्रयत्नशील योगीजन यह सब स्पष्ट रूप से देख सकते हैं । लेकिन जिनके मन विकसित नहीं हैं और जो आत्म-साक्षात्कार को प्राप्त नहीं हैं, वे प्रयत्न करके भी यह नहीं देख पाते कि क्या हो रहा है ।
    en:
      title: 'Chapter 15 - Verse 11'
      subtitle: ''
      image: ''
      description: |-
        The endeavoring transcendentalists who are situated in self-realization can see all this clearly. But those whose minds are not developed and who are not situated in self-realization cannot see what is taking place, though they may try.
- id: '12'
  type: 'leaf'
  paginated: true
  meta:
    hi:
      title: 'अध्याय १५ - श्लोक १२'
      subtitle: ''
      image: ''
      description: |-
        सूर्य का तेज, जो सारे विश्व के अंधकार को दूर करता है, मुझसे ही निकलता है । चन्द्रमा तथा अग्नि के तेज भी मुझसे उत्पन्न हैं ।
    en:
      title: 'Chapter 15 - Verse 12'
      subtitle: ''
      image: ''
      description: |-
        The splendor of the sun, which dissipates the darkness of this whole world, comes from Me. And the splendor of the moon and the splendor of fire are also from Me.
- id: '13'
  type: 'leaf'
  paginated: true
  meta:
    hi:
      title: 'अध्याय १५ - श्लोक १३'
      subtitle: ''
      image: ''
      description: |-
        मैं प्रत्येक लोक में प्रवेश करता हूँ और मेरी शक्ति से सारे लोक अपनी कक्षा में स्थित रहते हैं । मैं चन्द्रमा बनकर समस्त वनस्पतियों को जीवन-रस प्रदान करता हूँ ।
    en:
      title: 'Chapter 15 - Verse 13'
      subtitle: ''
      image: ''
      description: |-
        I enter into each planet, and by My energy they stay in orbit. I become the moon and thereby supply the juice of life to all vegetables.
- id: '14'
  type: 'leaf'
  paginated: true
  meta:
    hi:
      title: 'अध्याय १५ - श्लोक १४'
      subtitle: ''
      image: ''
      description: |-
        मैं समस्त जीवों के शरीरों में पाचन-अग्नि (वैश्वानर) हूँ और मैं श्वास-प्रश्वास (प्राण वायु) में रह कर चार प्रकार के अन्नों को पचाता हूँ ।
    en:
      title: 'Chapter 15 - Verse 14'
      subtitle: ''
      image: ''
      description: |-
        I am the fire of digestion in the bodies of all living entities, and I join with the air of life, outgoing and incoming, to digest the four kinds of foodstuff.
- id: '15'
  type: 'leaf'
  paginated: true
  meta:
    hi:
      title: 'अध्याय १५ - श्लोक १५'
      subtitle: ''
      image: ''
      description: |-
        मैं प्रत्येक जीव के हृदय में आसीन हूँ और मुझ से ही स्मृति, ज्ञान तथा विस्मृति होती है । मैं ही वेदों के द्वारा जानने योग्य हूँ । निस्सन्देह मैं वेदान्त का संकलनकर्ता तथा समस्त वेदों का जानने वाला हूँ ।
    en:
      title: 'Chapter 15 - Verse 15'
      subtitle: ''
      image: ''
      description: |-
        I am seated in everyone’s heart, and from Me come remembrance, knowledge and forgetfulness. By all the Vedas, I am to be known. Indeed, I am the compiler of Vedānta, and I am the knower of the Vedas.
- id: '16'
  type: 'leaf'
  paginated: true
  meta:
    hi:
      title: 'अध्याय १५ - श्लोक १६'
      subtitle: ''
      image: ''
      description: |-
        जीव दो प्रकार के हैं - च्युत तथा अच्युत । भौतिक जगत् में प्रत्येक जीव च्युत (क्षर) होता है और आध्यात्मिक जगत् में प्रत्येक जीव अच्युत (अक्षर) कहलाता है ।
    en:
      title: 'Chapter 15 - Verse 16'
      subtitle: ''
      image: ''
      description: |-
        There are two classes of beings, the fallible and the infallible. In the material world every living entity is fallible, and in the spiritual world every living entity is called infallible.
- id: '17'
  type: 'leaf'
  paginated: true
  meta:
    hi:
      title: 'अध्याय १५ - श्लोक १७'
      subtitle: ''
      image: ''
      description: |-
        इन दोनों के अतिरिक्त, एक परम पुरुष परमात्मा है, जो साक्षात् अविनाशी भगवान् है और जो तीनों लोकों में प्रवेश करके उनका पालन कर रहा है ।
    en:
      title: 'Chapter 15 - Verse 17'
      subtitle: ''
      image: ''
      description: |-
        Besides these two, there is the greatest living personality, the Supreme Soul, the imperishable Lord Himself, who has entered the three worlds and is maintaining them.
- id: '18'
  type: 'leaf'
  paginated: true
  meta:
    hi:
      title: 'अध्याय १५ - श्लोक १८'
      subtitle: ''
      image: ''
      description: |-
        चूँकि मैं क्षर तथा अक्षर दोनों के परे हूँ और चूँकि मैं सर्वश्रेष्ठ हूँ, अतएव मैं इस जगत् में तथा वेदों में परम पुरुष के रूप में विख्यात हूँ ।
    en:
      title: 'Chapter 15 - Verse 18'
      subtitle: ''
      image: ''
      description: |-
        Because I am transcendental, beyond both the fallible and the infallible, and because I am the greatest, I am celebrated both in the world and in the Vedas as that Supreme Person.
- id: '19'
  type: 'leaf'
  paginated: true
  meta:
    hi:
      title: 'अध्याय १५ - श्लोक १९'
      subtitle: ''
      image: ''
      description: |-
        जो कोई भी मुझे संशयरहित होकर पुरुषोत्तम भगवान् के रूप में जानता है, वह सब कुछ जानने वाला है । अतएव हे भरतपुत्र! वह व्यक्ति मेरी पूर्ण भक्ति में रत होता है ।
    en:
      title: 'Chapter 15 - Verse 19'
      subtitle: ''
      image: ''
      description: |-
        Whoever knows Me as the Supreme Personality of Godhead, without doubting, is the knower of everything. He therefore engages himself in full devotional service to Me, O son of Bharata.
- id: '20'
  type: 'leaf'
  paginated: true
  meta:
    hi:
      title: 'अध्याय १५ - श्लोक २०'
      subtitle: ''
      image: ''
      description: |-
        हे अनघ! यह वैदिक शास्त्रों का सर्वाधिक गुप्त अंश है, जिसे मैंने अब प्रकट किया है । जो कोई इसे समझता है, वह बुद्धिमान हो जाएगा और उसके प्रयास पूर्ण होंगे ।
    en:
      title: 'Chapter 15 - Verse 20'
      subtitle: ''
      image: ''
      description: |-
        This is the most confidential part of the Vedic scriptures, O sinless one, and it is disclosed now by Me. Whoever understands this will become wise, and his endeavors will know perfection.
