- id: 'hanuman-chalisa'
  type: 'leaf'
  paginated: false
  meta:
    hi:
      title: 'हनुमान चालीसा'
      subtitle: ''
      image: 'images/hanuman-chalisa-cover-4x3.jpg'
      description: |-
        हनुमान चालीसा अवधी में लिखी एक काव्यात्मक कृति है जिसमें प्रभु राम के महान भक्त हनुमान के गुणों एवं कार्यों का चालीस चौपाइयों में वर्णन है । यह अत्यन्त लघु रचना है जिसमें पवनपुत्र श्री हनुमान जी की सुन्दर स्तुति की गई है । इसमें बजरंग बली‍ की भावपूर्ण वन्दना तो है ही, श्रीराम का व्यक्तित्व भी सरल शब्दों में उकेरा गया है । 'चालीसा' शब्द से अभिप्राय 'चालीस' (४०) का है क्योंकि इस स्तुति में ४० छन्द हैं (परिचय के २ दोहों को छोड़कर) ।
    en:
      title: 'Hanuman Chalisa'
      subtitle: ''
      image: 'images/hanuman-chalisa-cover-4x3.jpg'
      description: |-
        Hanumāna Chalisa is a timeless ode to devotion Lord Hanumāna is known for his devotion to Lord Rāma and is considered to be the embodiment of faith, surrender, and devotion. He is one of seven chiranjeevs (immortals) as per Sanātan Dharma. Hanumāna also appears in Mahabharata on Arjuna's chariot as 'Dhwaj' (flag).
- id: 'ganesh-chalisa'
  type: 'leaf'
  paginated: false
  meta:
    hi:
      title: 'गणेश चालीसा'
      subtitle: ''
      image: 'images/ganesh-chalisa-cover-4x3.jpg'
      description: ''
    en:
      title: 'Ganesh Chalisa'
      subtitle: ''
      image: 'images/ganesh-chalisa-cover-4x3.jpg'
      description: ''