- id: 'hanuman-chalisa'
  type: 'leaf'
  paginated: false
  meta:
    hi:
      title: 'हनुमान चालीसा'
      subtitle: ''
      image: 'images/hanuman-chalisa-cover-4x3.jpg'
      description: |-
        हनुमान चालीसा अवधी में लिखी एक काव्यात्मक कृति है जिसमें प्रभु राम के महान भक्त हनुमान के गुणों एवं कार्यों का चालीस चौपाइयों में वर्णन है । यह अत्यन्त लघु रचना है जिसमें पवनपुत्र श्री हनुमान जी की सुन्दर स्तुति की गई है । इसमें बजरंग बली‍ की भावपूर्ण वन्दना तो है ही, श्रीराम का व्यक्तित्व भी सरल शब्दों में उकेरा गया है । 'चालीसा' शब्द से अभिप्राय 'चालीस' (४०) का है क्योंकि इस स्तुति में ४० छन्द हैं (परिचय के २ दोहों को छोड़कर) ।
    en:
      title: 'Hanuman Chalisa'
      subtitle: ''
      image: 'images/hanuman-chalisa-cover-4x3.jpg'
      description: |-
        Hanumāna Chalisa is a timeless ode to devotion Lord Hanumāna is known for his devotion to Lord Rāma and is considered to be the embodiment of faith, surrender, and devotion. He is one of seven chiranjeevs (immortals) as per Sanātan Dharma. Hanumāna also appears in Mahabharata on Arjuna's chariot as 'Dhwaj' (flag).
- id: 'ganesh-chalisa'
  type: 'leaf'
  paginated: false
  meta:
    hi:
      title: 'गणेश चालीसा'
      subtitle: ''
      image: 'images/ganesh-chalisa-cover-4x3.jpg'
      description: |-
        भगवान गणेश, जिन्हें गणपति और विनायक जैसे विभिन्न नामों से भी पुकारा जाता है, भगवान शिव और देवी पार्वती के पुत्र हैं । गणेश को सभी शुरुआतओं का भगवान और बाधाओं का अंतिम उपाय माना जाता है । उन्हें अच्छे भाग्य, नए उद्यम और ज्ञान के देवता के रूप में पूजा जाता है । गणेश चालीसा एक धार्मिक भजन है जो भगवान गणेश को समर्पित है ।
    en:
      title: 'Ganesh Chalisa'
      subtitle: ''
      image: 'images/ganesh-chalisa-cover-4x3.jpg'
      description: |-
        Lord Ganesha, also known by different names like Ganapati and Vinayaka, is the son of Lord Shiva and Goddess Parvati. Ganesha is considered the Lord of all beginnings and the last resort of obstacles. He is worshiped as the god of good fortune, new ventures and knowledge. Ganesh Chalisa is a religious hymn dedicated to Lord Ganesha.
- id: 'shiv-chalisa'
  type: 'leaf'
  paginated: false
  meta:
    hi:
      title: 'शिव चालीसा'
      subtitle: ''
      image: 'images/shiv-chalisa-cover-4x3.jpg'
      description: |-
        अयोध्यादासजी द्वारा रचित शिव चालीसा का पाठ करने से सुख-सौभाग्य में वृद्धि होती है । भगवान शिव की कृपा से सिद्धि-बुद्धि, धन-बल और ज्ञान-विवेक की प्राप्ति होती है । भगवान शिव अलौकिक शक्ति के मालिक है, उनकी कृपा मात्र से ही इंसान सारी तकलीफों से दूर हो जाता है ।
    en:
      title: 'Shiv Chalisa'
      subtitle: ''
      image: 'images/shiv-chalisa-cover-4x3.jpg'
      description: |-
        Reciting this Śiva Cālīsā composed by Saint Ayodhyādāsa early in the morning every day, one can easily earn grace of Lord Śiva which brings happiness, good forture, wealth and knowledge.  Lord Śiva is the owner of supernatural power, only from his grace, the person gets away from all the troubles.