- id: '1'
  type: leaf
  paginated: true
  meta:
    hi:
      title: 'अध्याय ७ - श्लोक १'
      subtitle: ''
      image: ''
      description: |-
        एक बुद्धिमान व्यक्ति को चाहिए कि वह अपने धन के नष्ट होने को, मानसिक दुख को, घर के दोषों को, किसी व्यक्ति द्वारा ठगे जाने और अपना अपमान होने की बात किसी पर भी प्रकट न करे, किसी को भी न बताए ।
    en:
      title: 'Chapter 7 - Verse 1'
      subtitle: ''
      image: ''
      description: |-
        A wise man should not reveal his loss of wealth, the vexation of his mind, the misconduct of his own wife, base words spoken by others, and disgrace that has befallen him.
- id: '2'
  type: leaf
  paginated: true
  meta:
    hi:
      title: 'अध्याय ७ - श्लोक २'
      subtitle: ''
      image: ''
      description: |-
        जो व्यक्ति धन-धान्य के लेन-देन में, विद्या अथवा किसी कला को सीखने में, भोजन के समय अथवा व्यवहार में लज्जाहीन होता है, अर्थात् संकोच नहीं करता वह सुखी रहता है ।
    en:
      title: 'Chapter 7 - Verse 2'
      subtitle: ''
      image: ''
      description: |-
        He who gives up shyness in monetary dealings, in acquiring knowledge, in eating and in business, becomes happy.
- id: '3'
  type: leaf
  paginated: true
  meta:
    hi:
      title: 'अध्याय ७ - श्लोक ३'
      subtitle: ''
      image: ''
      description: |-
        जो व्यक्ति संतोषरूपी अमृत से तृप्त है, मन से शांत है, उसे जो सुख प्राप्त होता है, वह धन के लिए इधर-उधर दौड़-धूप करने वाले को कभी प्राप्त नहीं होता ।
    en:
      title: 'Chapter 7 - Verse 3'
      subtitle: ''
      image: ''
      description: |-
        The happiness and peace attained by those satisfied by the nectar of spiritual tranquillity is not attained by greedy persons restlessly moving here and there.
- id: '4'
  type: leaf
  paginated: true
  meta:
    hi:
      title: 'अध्याय ७ - श्लोक ४'
      subtitle: ''
      image: ''
      description: |-
        अपनी पत्नी, भोजन और धन-इन तीनों के प्रति मनुष्य को संतोष रखना चाहिए, परंतु विद्याध्ययन, तप और दान के प्रति कभी संतोष नहीं करना चाहिए ।
    en:
      title: 'Chapter 7 - Verse 4'
      subtitle: ''
      image: ''
      description: |-
        One should feel satisfied with the following three things; his own wife, food given by Providence and wealth acquired by honest effort; but one should never feel satisfied with the following three; study, chanting the holy names of the Lord (japa) and charity.
- id: '5'
  type: leaf
  paginated: true
  meta:
    hi:
      title: 'अध्याय ७ - श्लोक ५'
      subtitle: ''
      image: ''
      description: |-
        दो ब्राह्मणों के बीच से, ब्राह्मण और अग्नि के बीच से, पति-पत्नी के बीच से, सेवक और नौकर के बीच से तथा हल-बैल के बीच से कभी नहीं निकलना चाहिए ।
    en:
      title: 'Chapter 7 - Verse 5'
      subtitle: ''
      image: ''
      description: |-
        Do not pass between two brahmanas, between a Brāhmaṇa and his sacrificial fire, between a wife and her husband, a master and his servant, and a plough and an ox.
- id: '6'
  type: leaf
  paginated: true
  meta:
    hi:
      title: 'अध्याय ७ - श्लोक ६'
      subtitle: ''
      image: ''
      description: |-
        अग्नि, गुरु, ब्राह्मण, गाय, कुंवारी कन्या, बूढ़ा आदमी और छोटे बच्चे–इन सबको पैर से कभी नहीं छूना चाहिए ।
    en:
      title: 'Chapter 7 - Verse 6'
      subtitle: ''
      image: ''
      description: |-
        Do not let your foot touch fire, the spiritual master or a Brāhmaṇa; it must never touch a cow, a virgin, an old person or a child.
- id: '7'
  type: leaf
  paginated: true
  meta:
    hi:
      title: 'अध्याय ७ - श्लोक ७'
      subtitle: ''
      image: ''
      description: |-
        बैलगाड़ी से पांच हाथ, घोड़े से दस हाथ और हाथी से सौ हाथ दूर रहने में ही मनुष्य की भलाई है । लेकिन दुष्ट से बचने के लिए यदि स्थान विशेष का त्याग भी करना पड़े तो हिचकना नहीं चाहिए ।
    en:
      title: 'Chapter 7 - Verse 7'
      subtitle: ''
      image: ''
      description: |-
        Keep one thousand cubits away from an elephant, a hundred from a horse, ten from a horned beast, but keep away from the wicked by leaving the country.
- id: '8'
  type: leaf
  paginated: true
  meta:
    hi:
      title: 'अध्याय ७ - श्लोक ८'
      subtitle: ''
      image: ''
      description: |-
        हाथी को अंकुश से वश में किया जाता है । घोड़े को हाथ की थाप से सीधे रास्ते पर लगाया जाता है । सींग वाले पशुओं को डंडा मारकर सीधे रास्ते पर लाया जा सकता है, परंतु दुष्ट व्यक्ति को हाथ में पकड़ी हुई तलवार से मारा जाना चाहिए क्योंकि वह वश में नहीं आता, उसे नष्ट ही करना होता है ।
    en:
      title: 'Chapter 7 - Verse 8'
      subtitle: ''
      image: ''
      description: |-
        An elephant is controlled by a goad (ankusha), a horse by a slap of the hand, a horned animal with the show of a stick, and a rascal with a sword.
- id: '9'
  type: leaf
  paginated: true
  meta:
    hi:
      title: 'अध्याय ७ - श्लोक ९'
      subtitle: ''
      image: ''
      description: |-
        ब्राह्मण भोजन से तृप्त हो जाता है, मोर बादलों के गर्जने पर, सज्जन दूसरे को संपन्न और सुखी देखकर परंतु दुष्ट दूसरों को विपत्ति में पड़ा देखकर प्रसन्न होते हैं ।
    en:
      title: 'Chapter 7 - Verse 9'
      subtitle: ''
      image: ''
      description: |-
        Brahmanas find satisfaction in a good meal, peacocks in the peal of thunder, a sadhu in seeing the prosperity of others, and the wicked in the misery of others.
- id: '10'
  type: leaf
  paginated: true
  meta:
    hi:
      title: 'अध्याय ७ - श्लोक १०'
      subtitle: ''
      image: ''
      description: |-
        बलवान शत्रु को अनुकूल तथा दुर्जन शत्रु को प्रतिकूल व्यवहार द्वारा अपने वश में करें । इसी प्रकार अपने समान बल वाले शत्रु को विनम्रता या बल द्वारा, जो भी उस समय उपयुक्त हो, अपने वश में करने का प्रयत्न करना चाहिए ।
    en:
      title: 'Chapter 7 - Verse 10'
      subtitle: ''
      image: ''
      description: |-
        Conciliate a strong man by submission, a wicked man by opposition, and the one whose power is equal to yours by politeness or force.
- id: '11'
  type: leaf
  paginated: true
  meta:
    hi:
      title: 'अध्याय ७ - श्लोक ११'
      subtitle: ''
      image: ''
      description: |-
        राजा का बल अथवा शक्ति उसकी भुजाओं का बल है । ब्राह्मण का बल उसका ज्ञान है और स्त्रियों का बल रूप और यौवन के साथ-साथ उनका सुमधुर व्यवहार है ।
    en:
      title: 'Chapter 7 - Verse 11'
      subtitle: ''
      image: ''
      description: |-
        The power of a king lies in his mighty arms; that of a Brāhmaṇa in his spiritual knowledge; and that of a woman in her beauty youth and sweet words.
- id: '12'
  type: leaf
  paginated: true
  meta:
    hi:
      title: 'अध्याय ७ - श्लोक १२'
      subtitle: ''
      image: ''
      description: |-
        मनुष्य को अत्यन्त सरल और सीधा भी नहीं होना चाहिए । वन में जाकर देखो, सीधे वृक्ष काट दिए जाते हैं और टेढ़े-मेढ़े गांठों वाले वृक्ष खड़े रहते हैं ।
    en:
      title: 'Chapter 7 - Verse 12'
      subtitle: ''
      image: ''
      description: |-
        Do not be very upright in your dealings for you would see by going to the forest that straight trees are cut down while crooked ones are left standing.
- id: '13'
  type: leaf
  paginated: true
  meta:
    hi:
      title: 'अध्याय ७ - श्लोक १३'
      subtitle: ''
      image: ''
      description: |-
        जहां जल रहता है, वहां हंस रहते हैं और जब जल सूख जाता है तो हंस उस स्थान को छोड़ देते हैं । मनुष्य को हंस के समान स्वार्थी नहीं होना चाहिए, क्योंकि वे कभी त्याग करते हैं और कभी आश्रय लेते हैं ।
    en:
      title: 'Chapter 7 - Verse 13'
      subtitle: ''
      image: ''
      description: |-
        Swans live wherever there is water, and leave the place where water dries up; let not a man act so -- and come and go as he pleases.
- id: '14'
  type: leaf
  paginated: true
  meta:
    hi:
      title: 'अध्याय ७ - श्लोक १४'
      subtitle: ''
      image: ''
      description: |-
        अर्जित अथवा कमाए हुए धन का त्याग करना अर्थात् उसका ठीक ढंग से व्यय करना, उससे सार्थक लाभ उठाना ही उसकी रक्षा है । जिस प्रकार तालाब में भरे हुए जल को निकालते रहने से ही उस तालाब का पानी शुद्ध और पवित्र रहता है ।
    en:
      title: 'Chapter 7 - Verse 14'
      subtitle: ''
      image: ''
      description: |-
        Accumulated wealth is saved by spending just as incoming fresh water is saved by letting out stagnant water.
- id: '15'
  type: leaf
  paginated: true
  meta:
    hi:
      title: 'अध्याय ७ - श्लोक १५'
      subtitle: ''
      image: ''
      description: |-
        संसार में जिसके पास धन है उसी के सब मित्र होते हैं, उसी के सब भाई-बन्धु और स्वजन होते हैं । धनवान व्यक्ति को ही श्रेष्ठ व्यक्ति माना जाता है । इस प्रकार वह आदरपूर्वक अपना जीवन बिताता है ।
    en:
      title: 'Chapter 7 - Verse 15'
      subtitle: ''
      image: ''
      description: |-
        He who has wealth has friends and relations; he alone survives and is respected as a man.
- id: '16'
  type: leaf
  paginated: true
  meta:
    hi:
      title: 'अध्याय ७ - श्लोक १६'
      subtitle: ''
      image: ''
      description: |-
        स्वर्ग से इस संसार में आने वाले जीव के शरीर में चार बातें उसके चिह्न रूप में रहती हैं अर्थात् उसके चार प्रमुख गुण होते हैं । उसमें दान देने की प्रवृत्ति होती है । वह मधुरभाषी होता है । देवताओं की पूजा-अर्चना करता है, उनका आदर-सत्कार करता है और विद्वानब्राह्मणों को सदैव तृप्त अर्थात् संतुष्ट रखता है ।
    en:
      title: 'Chapter 7 - Verse 16'
      subtitle: ''
      image: ''
      description: |-
        The following four characteristics of the denizens of heaven may be seen in the residents of this earth planet; charity, sweet words, worship of the Supreme Personality of Godhead, and satisfying the needs of brahmanas.
- id: '17'
  type: leaf
  paginated: true
  meta:
    hi:
      title: 'अध्याय ७ - श्लोक १७'
      subtitle: ''
      image: ''
      description: |-
        (इसी प्रकार) नरक में रहने वाले जब देह धारण कर इस संसार में आते हैं तो उनमें ऊपर बताए गए चिह्नों के सर्वथा विपरीत चिह्न होते हैं । वे मधुरभाषी होने के बजाय अत्यंत क्रोधी स्वभाव के होते हैं । कड़वी बात कहते हैं । वे निर्धन होते हैं । अपने परिवारजनों तथा मित्रों से वे द्वेष-भाव रखते हैं । उनकी संगति में नीच लोग रहते हैं और वे नीच कुल वालों की सेवा करते हैं ।
    en:
      title: 'Chapter 7 - Verse 17'
      subtitle: ''
      image: ''
      description: |-
        The following qualities of the denizens of hell may characterise men on earth; extreme wrath, harsh speech, enmity with one's relations, the company with the base, and service to men of low extraction.
- id: '18'
  type: leaf
  paginated: true
  meta:
    hi:
      title: 'अध्याय ७ - श्लोक १८'
      subtitle: ''
      image: ''
      description: |-
        यदि कोई मनुष्य सिंह की गुफा में पहुंच जाए तो वहां संभव है कि उसे हाथी के मस्तक का मोती (गजमुक्ता) प्राप्त हो जाए लेकिन यदि कोई गीदड़ की गुफा में जाएगा तो वहां उसे किसी बछड़े की पूंछ का अथवा गधे की खाल का टुकड़ा ही प्राप्त होगा ।
    en:
      title: 'Chapter 7 - Verse 18'
      subtitle: ''
      image: ''
      description: |-
        By going to the den of a lion pearls from the head of an elephant may be obtained; but by visiting the hole of a jackal nothing but the tail of a calf or a bit of the hide of an ass may found.
- id: '19'
  type: leaf
  paginated: true
  meta:
    hi:
      title: 'अध्याय ७ - श्लोक १९'
      subtitle: ''
      image: ''
      description: |-
        विद्या के बिना मनुष्य का जीवन कुत्ते की उस पूंछ के समान है, जिससे न तो वह अपने शरीर के गुप्त भागों को ढक सकता है और न ही काटने वाले मच्छरों आदि को उड़ा सकता है ।
    en:
      title: 'Chapter 7 - Verse 19'
      subtitle: ''
      image: ''
      description: |-
        The life of an uneducated man is as useless as the tail of a dog which neither covers its rear end, nor protects it from the bites of insects.
- id: '20'
  type: leaf
  paginated: true
  meta:
    hi:
      title: 'अध्याय ७ - श्लोक २०'
      subtitle: ''
      image: ''
      description: |-
        वाणी की पवित्रता, मन की शुद्धि, इंद्रियों का संयम, प्राणिमात्र पर दया, धन की पवित्रता, मोक्ष प्राप्त करने वाले के लक्षण होते हैं ।
    en:
      title: 'Chapter 7 - Verse 20'
      subtitle: ''
      image: ''
      description: |-
        Purity of speech, of the mind, of the senses, and the of a compassionate heart are needed by one who desires to rise to the divine platform.
- id: '21'
  type: leaf
  paginated: true
  meta:
    hi:
      title: 'अध्याय ७ - श्लोक २१'
      subtitle: ''
      image: ''
      description: |-
        जैसे फूल में सुगंध होती है, तिलों में तेल होता है, सूखी लकड़ी में अग्नि होती है, दूध में घी और ईख में गुड़ तथा मिठास होती है, वैसे ही शरीर में आत्मा और परमात्मा विद्यमान है । बुद्धिमान मनुष्य को विवेक का सहारा लेकर आत्मा और परमात्मा को जानने का प्रयत्न करना चाहिए ।
    en:
      title: 'Chapter 7 - Verse 21'
      subtitle: ''
      image: ''
      description: |-
        As you seek fragrance in a flower, oil in the sesamum seed, fire in wood, ghee in milk, and jaggery (guda) in sugarcane; so seek the spirit that is in the body by means of discrimination.
