- id: '1-3'
  type: 'leaf'
  paginated: true
  meta:
    hi:
      title: 'अध्याय १६ - श्लोक १-३'
      subtitle: ''
      image: ''
      description: |-
        भगवान् ने कहा - हे भरतपुत्र! निर्भयता, आत्मशुद्धि, आध्यात्मिक ज्ञान का अनुशीलन, दान, आत्म-संयम, यज्ञपरायणता, वेदाध्ययन, तपस्या, सरलता, अहिंसा, सत्यता, क्रोधविहीनता, त्याग, शान्ति, छिद्रान्वेषण में अरुचि, समस्त जीवों पर करुणा, लोभविहीनता, भद्रता, लज्जा, संकल्प, तेज, क्षमा, धैर्य, पवित्रता, ईर्ष्या तथा सम्मान की अभिलाषा से मुक्ति-ये सारे दिव्य गुण हैं, जो दैवी प्रकृति से सम्पन्न देवतुल्य पुरुषों में पाये जाते हैं ।
    en:
      title: 'Chapter 16 - Verse 1-3'
      subtitle: ''
      image: ''
      description: |-
        The Supreme Personality of Godhead said: Fearlessness; purification of one’s existence; cultivation of spiritual knowledge; charity; self-control; performance of sacrifice; study of the Vedas; austerity; simplicity; nonviolence; truthfulness; freedom from anger; renunciation; tranquillity; aversion to faultfinding; compassion for all living entities; freedom from covetousness; gentleness; modesty; steady determination; vigor; forgiveness; fortitude; cleanliness; and freedom from envy and from the passion for honor – these transcendental qualities, O son of Bharata, belong to godly men endowed with divine nature.
- id: '4'
  type: 'leaf'
  paginated: true
  meta:
    hi:
      title: 'अध्याय १६ - श्लोक ४'
      subtitle: ''
      image: ''
      description: |-
        हे पृथापुत्र! दम्भ, दर्प, अभिमान, क्रोध, कठोरता तथा अज्ञान - ये आसुरी स्वभाव वालों के गुण हैं ।
    en:
      title: 'Chapter 16 - Verse 4'
      subtitle: ''
      image: ''
      description: |-
        Pride, arrogance, conceit, anger, harshness and ignorance – these qualities belong to those of demoniac nature, O son of Pṛthā.
- id: '5'
  type: 'leaf'
  paginated: true
  meta:
    hi:
      title: 'अध्याय १६ - श्लोक ५'
      subtitle: ''
      image: ''
      description: |-
        दिव्य गुण मोक्ष के लिए अनुकूल हैं और आसुरी गुण बन्धन दिलाने के लिए हैं । हे पाण्डुपुत्र! तुम चिन्ता मत करो, क्योंकि तुम दैवी गुणों से युक्त होकर जन्मे हो ।
    en:
      title: 'Chapter 16 - Verse 5'
      subtitle: ''
      image: ''
      description: |-
        The transcendental qualities are conducive to liberation, whereas the demoniac qualities make for bondage. Do not worry, O son of Pāṇḍu, for you are born with the divine qualities.
- id: '6'
  type: 'leaf'
  paginated: true
  meta:
    hi:
      title: 'अध्याय १६ - श्लोक ६'
      subtitle: ''
      image: ''
      description: |-
        हे पृथापुत्र! इस संसार में सृजित प्राणी दो प्रकार के हैं - दैवी तथा आसुरी । मैं पहले ही विस्तार से तुम्हें दैवी गुण बतला चुका हूँ । अब मुझसे आसुरी गुणों के विषय में सुनो ।
    en:
      title: 'Chapter 16 - Verse 6'
      subtitle: ''
      image: ''
      description: |-
        O son of Pṛthā, in this world there are two kinds of created beings. One is called divine and the other demoniac. I have already explained to you at length the divine qualities. Now hear from Me of the demoniac.
- id: '7'
  type: 'leaf'
  paginated: true
  meta:
    hi:
      title: 'अध्याय १६ - श्लोक ७'
      subtitle: ''
      image: ''
      description: |-
        जो आसुरी हैं, वे यह नहीं जानते कि क्या करना चाहिए और क्या नहीं करना चाहिए । उनमें न तो पवित्रता, न उचित आचरण और न ही सत्य पाया जाता है ।
    en:
      title: 'Chapter 16 - Verse 7'
      subtitle: ''
      image: ''
      description: |-
        Those who are demoniac do not know what is to be done and what is not to be done. Neither cleanliness nor proper behavior nor truth is found in them.
- id: '8'
  type: 'leaf'
  paginated: true
  meta:
    hi:
      title: 'अध्याय १६ - श्लोक ८'
      subtitle: ''
      image: ''
      description: |-
        वे कहते हैं कि यह जगत् मिथ्या है, इसका कोई आधार नहीं है और इसका नियमन किसी ईश्वर द्वारा नहीं होता । उनका कहना है कि यह कामेच्छा से उत्पन्न होता है और काम के अतिरिक्त कोई अन्य कारण नहीं है ।
    en:
      title: 'Chapter 16 - Verse 8'
      subtitle: ''
      image: ''
      description: |-
        They say that this world is unreal, with no foundation, no God in control. They say it is produced of sex desire and has no cause other than lust.
- id: '9'
  type: 'leaf'
  paginated: true
  meta:
    hi:
      title: 'अध्याय १६ - श्लोक ९'
      subtitle: ''
      image: ''
      description: |-
        ऐसे निष्कर्षों का अनुगमन करते हुए आसुरी लोग, जिन्होंने आत्म-ज्ञान खो दिया है और जो बुद्धिहीन हैं, ऐसे अनुपयोगी एवं भयावह कार्यों में प्रवृत्त होते हैं जो संसार का विनाश करने के लिए होता है ।
    en:
      title: 'Chapter 16 - Verse 9'
      subtitle: ''
      image: ''
      description: |-
        Following such conclusions, the demoniac, who are lost to themselves and who have no intelligence, engage in unbeneficial, horrible works meant to destroy the world.
- id: '10'
  type: 'leaf'
  paginated: true
  meta:
    hi:
      title: 'अध्याय १६ - श्लोक १०'
      subtitle: ''
      image: ''
      description: |-
        कभी न संतुष्ट होने वाले काम का आश्रय लेकर तथा गर्व के मद एवं मिथ्या प्रतिष्ठा में डूबे हुए आसुरी लोग इस तरह मोहग्रस्त होकर सदैव क्षणभंगुर वस्तुओं के द्वारा अपवित्र कर्म का व्रत लिए रहते हैं ।
    en:
      title: 'Chapter 16 - Verse 10'
      subtitle: ''
      image: ''
      description: |-
        Taking shelter of insatiable lust and absorbed in the conceit of pride and false prestige, the demoniac, thus illusioned, are always sworn to unclean work, attracted by the impermanent.
- id: '11-12'
  type: 'leaf'
  paginated: true
  meta:
    hi:
      title: 'अध्याय १६ - श्लोक ११-१२'
      subtitle: ''
      image: ''
      description: |-
        उनका विश्वास है कि इन्द्रियों की तुष्टि ही मानव सभ्यता की मूल आवश्यकता है । इस प्रकार मरणकाल तक उनको अपार चिन्ता होती रहती है । वे लाखों इच्छाओं के जाल में बँधकर तथा काम और क्रोध में लीन होकर इन्द्रियतृप्ति के लिए अवैध ढंग से धनसंग्रह करते हैं ।
    en:
      title: 'Chapter 16 - Verse 11-12'
      subtitle: ''
      image: ''
      description: |-
        They believe that to gratify the senses is the prime necessity of human civilization. Thus until the end of life their anxiety is immeasurable. Bound by a network of hundreds of thousands of desires and absorbed in lust and anger, they secure money by illegal means for sense gratification.
- id: '13-15'
  type: 'leaf'
  paginated: true
  meta:
    hi:
      title: 'अध्याय १६ - श्लोक १३-१५'
      subtitle: ''
      image: ''
      description: |-
        आसुरी व्यक्ति सोचता है, आज मेरे पास इतना धन है और अपनी योजनाओं से मैं और अधिक धन कमाऊँगा । इस समय मेरे पास इतना है किन्तु भविष्य में यह बढ़कर और अधिक हो जायेगा । वह मेरा शत्रु है और मैंने उसे मार दिया है और मेरे अन्य शत्रु भी मार दिए जाएंगे । मैं सभी वस्तुओं का स्वामी हूँ । मैं भोक्ता हूँ । मैं सिद्ध, शक्तिमान तथा सुखी हूँ । मैं सबसे धनी व्यक्ति हूँ और मेरे आसपास मेरे कुलीन सम्बन्धी हैं । कोई अन्य मेरे समान शक्तिमान तथा सुखी नहीं है । मैं यज्ञ करूँगा, दान दूँगा और इस तरह आनन्द मनाऊँगा । इस प्रकार ऐसे व्यक्ति अज्ञानवश मोहग्रस्त होते रहते हैं ।
    en:
      title: 'Chapter 16 - Verse 13-15'
      subtitle: ''
      image: ''
      description: |-
        The demoniac person thinks: “So much wealth do I have today, and I will gain more according to my schemes. So much is mine now, and it will increase in the future, more and more. He is my enemy, and I have killed him, and my other enemies will also be killed. I am the lord of everything. I am the enjoyer. I am perfect, powerful and happy. I am the richest man, surrounded by aristocratic relatives. There is none so powerful and happy as I am. I shall perform sacrifices, I shall give some charity, and thus I shall rejoice.” In this way, such persons are deluded by ignorance.
- id: '16'
  type: 'leaf'
  paginated: true
  meta:
    hi:
      title: 'अध्याय १६ - श्लोक १६'
      subtitle: ''
      image: ''
      description: |-
        इस प्रकार अनेक चिन्ताओं से उद्विग्न होकर तथा मोहजाल में बँधकर वे इन्द्रियभोग में अत्यधिक आसक्त हो जाते हैं और नरक में गिरते हैं ।
    en:
      title: 'Chapter 16 - Verse 16'
      subtitle: ''
      image: ''
      description: |-
        Thus perplexed by various anxieties and bound by a network of illusions, they become too strongly attached to sense enjoyment and fall down into hell.
- id: '17'
  type: 'leaf'
  paginated: true
  meta:
    hi:
      title: 'अध्याय १६ - श्लोक १७'
      subtitle: ''
      image: ''
      description: |-
        अपने को श्रेष्ठ मानने वाले तथा सदैव घमंड करने वाले, सम्पत्ति तथा मिथ्या प्रतिष्ठा से मोहग्रस्त लोग किसी विधि-विधान का पालन न करते हुए कभी-कभी नाममात्र के लिए बड़े ही गर्व के साथ यज्ञ करते हैं ।
    en:
      title: 'Chapter 16 - Verse 17'
      subtitle: ''
      image: ''
      description: |-
        Self-complacent and always impudent, deluded by wealth and false prestige, they sometimes proudly perform sacrifices in name only, without following any rules or regulations.
- id: '18'
  type: 'leaf'
  paginated: true
  meta:
    hi:
      title: 'अध्याय १६ - श्लोक १८'
      subtitle: ''
      image: ''
      description: |-
        मिथ्या अहंकार, बल, दर्प, काम तथा क्रोध से मोहित होकर आसुरी व्यक्ति अपने शरीर में तथा अन्यों के शरीर में स्थित भगवान् से ईर्ष्या और वास्तविक धर्म की निन्दा करने लगते हैं ।
    en:
      title: 'Chapter 16 - Verse 18'
      subtitle: ''
      image: ''
      description: |-
        Bewildered by false ego, strength, pride, lust and anger, the demons become envious of the Supreme Personality of Godhead, who is situated in their own bodies and in the bodies of others, and blaspheme against the real religion.
- id: '19'
  type: 'leaf'
  paginated: true
  meta:
    hi:
      title: 'अध्याय १६ - श्लोक १९'
      subtitle: ''
      image: ''
      description: |-
        जो लोग ईर्ष्यालु तथा क्रूर हैं और नराधम हैं, उन्हें मैं निरन्तर विभिन्न आसुरी योनियों में, भवसागर में डालता रहता हूँ ।
    en:
      title: 'Chapter 16 - Verse 19'
      subtitle: ''
      image: ''
      description: |-
        Those who are envious and mischievous, who are the lowest among men, I perpetually cast into the ocean of material existence, into various demoniac species of life.
- id: '20'
  type: 'leaf'
  paginated: true
  meta:
    hi:
      title: 'अध्याय १६ - श्लोक २०'
      subtitle: ''
      image: ''
      description: |-
        हे कुन्तीपुत्र! ऐसे व्यक्ति आसुरी योनि में बारम्बार जन्म ग्रहण करते हुए कभी भी मुझ तक पहुँच नहीं पाते । वे धीरे-धीरे अत्यन्त अधम गति को प्राप्त होते हैं ।
    en:
      title: 'Chapter 16 - Verse 20'
      subtitle: ''
      image: ''
      description: |-
        Attaining repeated birth amongst the species of demoniac life, O son of Kuntī, such persons can never approach Me. Gradually they sink down to the most abominable type of existence.
- id: '21'
  type: 'leaf'
  paginated: true
  meta:
    hi:
      title: 'अध्याय १६ - श्लोक २१'
      subtitle: ''
      image: ''
      description: |-
        इस नरक के तीन द्वार हैं - काम, क्रोध तथा लोभ । प्रत्येक बुद्धिमान व्यक्ति को चाहिए कि इन्हें त्याग दे, क्योंकि इनसे आत्मा का पतन होता है ।
    en:
      title: 'Chapter 16 - Verse 21'
      subtitle: ''
      image: ''
      description: |-
        There are three gates leading to this hell – lust, anger and greed. Every sane man should give these up, for they lead to the degradation of the soul.
- id: '22'
  type: 'leaf'
  paginated: true
  meta:
    hi:
      title: 'अध्याय १६ - श्लोक २२'
      subtitle: ''
      image: ''
      description: |-
        हे कुन्तीपुत्र! जो व्यक्ति इन तीनों नरक-द्वारों से बच पाता है, वह आत्म-साक्षात्कार के लिए कल्याणकारी कार्य करता है और इस प्रकार क्रमशः परम गति को प्राप्त होता है ।
    en:
      title: 'Chapter 16 - Verse 22'
      subtitle: ''
      image: ''
      description: |-
        The man who has escaped these three gates of hell, O son of Kuntī, performs acts conducive to self-realization and thus gradually attains the supreme destination.
- id: '23'
  type: 'leaf'
  paginated: true
  meta:
    hi:
      title: 'अध्याय १६ - श्लोक २३'
      subtitle: ''
      image: ''
      description: |-
        जो शास्त्रों के आदेशों की अवहेलना करता है और मनमाने ढंग से कार्य करता है, उसे न तो सिद्धि, न सुख, न ही परमगति की प्राप्ति हो पाती है ।
    en:
      title: 'Chapter 16 - Verse 23'
      subtitle: ''
      image: ''
      description: |-
        He who discards scriptural injunctions and acts according to his own whims attains neither perfection, nor happiness, nor the supreme destination.
- id: '24'
  type: 'leaf'
  paginated: true
  meta:
    hi:
      title: 'अध्याय १६ - श्लोक २४'
      subtitle: ''
      image: ''
      description: |-
        अतएव मनुष्य को यह जानना चाहिए कि शास्त्रों के विधान के अनुसार क्या कर्तव्य है और क्या अकर्तव्य है । उसे ऐसे विधि-विधानों को जानकर कर्म करना चाहिए जिससे वह क्रमशः ऊपर उठ सके ।
    en:
      title: 'Chapter 16 - Verse 24'
      subtitle: ''
      image: ''
      description: |-
        One should therefore understand what is duty and what is not duty by the regulations of the scriptures. Knowing such rules and regulations, one should act so that he may gradually be elevated.
