- id: '1'
  type: leaf
  paginated: true
  meta:
    hi:
      title: 'अध्याय १२ - श्लोक १'
      subtitle: ''
      image: ''
      description: |-
        जिसके घर में आनंद हो, जिसके पुत्र बुद्धिमान हों, जिसकी पत्नी मृदुभाषिणी हो, जिसके पास परिश्रम हो, ईमानदारी से पैदा किया हुआ धन हो, अच्छे मित्र हों, अपनी पत्नी के प्रति प्रेम और अनुराग हो, नौकर-चाकर आज्ञा का पालन करने वाले हों । जिस घर में अतिथियों का आदर-सम्मान होता है, कल्याणकारी परमेश्वर की उपासना होती है, घर में प्रतिदिन अच्छे मीठे भोजन और मधुर पेयों की व्यवस्था होती है, सदा सज्जन पुरुषों का संग अथवा संगति करने का अवसर मिलता है, ऐसा गृहस्थ आश्रम धन्य है, प्रशंसा के योग्य है ।
    en:
      title: 'Chapter 12 - Verse 1'
      subtitle: ''
      image: ''
      description: |-
        He is a blessed Gṛhastha (householder) in whose house there is a blissful atmosphere, whose sons are wise, whose wife speaks sweetly, whose wealth is enough to satisfy his desires, who finds pleasure in the company of his wife, whose servants are obedient, in whose house hospitality is shown, the auspicious Supreme Lord is worshiped daily, delicious food and drink is partaken, and who finds joy in the company of devotees, such a householder is blessed, worthy of praise.
- id: '2'
  type: leaf
  paginated: true
  meta:
    hi:
      title: 'अध्याय १२ - श्लोक २'
      subtitle: ''
      image: ''
      description: |-
        दयालु और करुणा से युक्त मनुष्य दुखी ब्राह्मणों को श्रद्धा से जो कुछ भी दान देता है, हे राजन्! वह दान देने वाले को केवल उतना ही प्राप्त नहीं होता है, प्रभु की कृपा से उसमें काफी वृद्धि होती है और वह दान देने वालों को भली-प्रकार मिलता जाता है ।
    en:
      title: 'Chapter 12 - Verse 2'
      subtitle: ''
      image: ''
      description: |-
        One who devotedly gives a little to a Brāhmaṇa who is in distress is recompensed abundantly. Hence, O King, what is given to a good Brāhmaṇa is got back not in an equal quantity, but in an infinitely higher degree.
- id: '3'
  type: leaf
  paginated: true
  meta:
    hi:
      title: 'अध्याय १२ - श्लोक ३'
      subtitle: ''
      image: ''
      description: |-
        अपने बन्धु-बान्धवों के साथ वही व्यक्ति सुख से रह सकता है, जो उनके साथ सज्जनता और नम्रता का व्यवहार करता है, दूसरे लोगों पर दया और दुर्जनों के प्रति भी उनके अनुकूल व्यवहार करता है, सज्जन लोगों से जो प्रेम रखता है, दुष्टों के प्रति जो कठोर होता है और विद्वानों के साथ सरलता से पेश आता है । जो शक्तिशाली लोगों के साथ शूरवीरता और पराक्रम से काम लेता है, गुरु, माता-पिता और आचार्य के प्रति जो सहनशीलतापूर्ण व्यवहार रखता है तथा स्त्रियों के प्रति अधिक विश्वास न करके जो उनके प्रति चतुराईपूर्ण व्यवहार करता है, वही कुशलतापूर्वक इस संसार में रह सकता है ।
    en:
      title: 'Chapter 12 - Verse 3'
      subtitle: ''
      image: ''
      description: |-
        Those men who are happy in this world, who are generous towards their relatives, kind to strangers, indifferent to the wicked, loving to the good, shrewd in their dealings with the base, frank with the learned, courageous with enemies, humble with elders and tactful with the wife.
- id: '4'
  type: leaf
  paginated: true
  meta:
    hi:
      title: 'अध्याय १२ - श्लोक ४'
      subtitle: ''
      image: ''
      description: |-
        जिसके दोनों हाथ कभी दान आदि के कार्य में नहीं लगे अर्थात जिसने जीवन में कभी दान न दिया हो, कानों से वेद आदि शास्त्रों का श्रवण नहीं किया अर्थात उनसे द्वेष करता रहा हो, अपने दोनों नेत्रों से सज्जन पुरुषों के दर्शन नहीं किए, पैरों से तीर्थयात्रा नहीं की, माता-पिता तथा आचार्य की सेवा के लिए जो उनके पास कभी नहीं गया, जिसने अधर्म के मार्ग से कमाए हुए धन से अपना पेट भरा, इतने पर भी जो अभिमान से सिर ऊंचा उठाकर चलता है, अरे लोमड़ी! उसे मत खा, नहीं तो तू दूषित हो जाएगी ।
    en:
      title: 'Chapter 12 - Verse 4'
      subtitle: ''
      image: ''
      description: |-
        O jackal, leave aside the body of that man at once, whose hands have never given in charity, whose ears did not listen to the scriptures like Vedas etc, whose eyes have not beheld a pure devotee of the Lord, whose feet have never traversed to holy places, whose belly is filled with things obtained by crooked practices, and whose head is held high in vanity. Do not eat it, O jackal, otherwise you will become polluted.
- id: '5'
  type: leaf
  paginated: true
  meta:
    hi:
      title: 'अध्याय १२ - श्लोक ५'
      subtitle: ''
      image: ''
      description: |-
        धिक्कार है उन्हें जिन्हें भगवान् श्री कृष्ण जो माँ यशोदा के लाडले है उन के चरण कमलों में कोई भक्ति नहीं । जिन्हें श्रीमति राधारानी की महिमा का वर्णन करने में कोई आसक्ति नहीं । जिनके कान श्री भगवान की लीला की कथा सुनने के लिए उत्सुक नहीं । मृदंग की ध्वनि धिक् तम धिक् तम करके ऐसे लोगो का धिक्कार करती है ।
    en:
      title: 'Chapter 12 - Verse 5'
      subtitle: ''
      image: ''
      description: |-
        'Shame upon those who have no devotion to the lotus feet of Śrī Kṛṣṇa, the son of mother Yaśodā; who have no attachment for the describing the glories of Śrīmatī Rādhārānī; whose ears are not eager to listen to the stories of the Lord's līlā.' Such is the exclamation of the Mṛdaṃga (a percussion instrument) sound of dhik-tam dhik-tam dhigatam at kīrtana.
- id: '6'
  type: leaf
  paginated: true
  meta:
    hi:
      title: 'अध्याय १२ - श्लोक ६'
      subtitle: ''
      image: ''
      description: |-
        बसंत ऋतु क्या करेगी यदि करील नामक पौधे पर पत्ते नहीं आते । सूर्य का क्या दोष यदि उल्लू दिन में देख नहीं सकता । बादलो का क्या दोष यदि बारिश की बूंदे चातक पक्षी की चोंच में नहीं गिरती । उसे कोई कैसे बदल सकता है जो किसी के मूल में है ।
    en:
      title: 'Chapter 12 - Verse 6'
      subtitle: ''
      image: ''
      description: |-
        What fault of spring that the bamboo shoot has no leaves? What fault of the sun if the owl cannot see during the daytime? Is it the fault of the clouds if no raindrops fall into the mouth of the Cātaka bird? Who can erase what Lord Brahmā has inscribed upon our foreheads at the time of birth?
- id: '7'
  type: leaf
  paginated: true
  meta:
    hi:
      title: 'अध्याय १२ - श्लोक ७'
      subtitle: ''
      image: ''
      description: |-
        सज्जनों के सत्संग से दुर्जन मनुष्य भी सज्जन हो सकता है, परंतु सज्जन पुरुषों में दुष्टों की संगति से दुष्टता वैसे ही नहीं आती जैसे फूल से उत्पन्न होने वाली सुगंध मिट्टी में तो आ जाती है, परंतु मिट्टी की गंध फूल में नहीं आ पाती है ।
    en:
      title: 'Chapter 12 - Verse 7'
      subtitle: ''
      image: ''
      description: |-
        A wicked man may develop saintly qualities in the company of a devotee, but a devotee does not become impious in the company of a wicked person. The earth is scented by a flower that falls upon it, but the flower does not contact the odour of the earth.
- id: '8'
  type: leaf
  paginated: true
  meta:
    hi:
      title: 'अध्याय १२ - श्लोक ८'
      subtitle: ''
      image: ''
      description: |-
        सज्जन पुरुष के दर्शन से पुण्य प्राप्त होता है, क्योंकि साधु पुरुष अपने आपमें साक्षात् तीर्थस्वरूप होते हैं । तीर्थ तो अपने समय के अनुसार ही फल देता है, परंतु साधुओं का संग करने से जल्दी ही मन की आशाएं पूर्ण हो जाती हैं ।
    en:
      title: 'Chapter 12 - Verse 8'
      subtitle: ''
      image: ''
      description: |-
        One indeed becomes blessed by having darshan of a devotee; for the devotee has the ability to purify immediately, whereas the sacred tirtha gives purity only after prolonged contact.
- id: '9'
  type: leaf
  paginated: true
  meta:
    hi:
      title: 'अध्याय १२ - श्लोक ९'
      subtitle: ''
      image: ''
      description: |-
        कोई राही अथवा यात्री किसी नगर में पहुंचकर किसी ब्राह्मण से पूछता है, "हे ब्राह्मण! मुझे बताओ कि इस नगर में कौन सबसे अधिक महान है ?" उस ब्राह्मण ने उत्तर दिया, "ताड़ के वृक्षों का झुंड ।" यात्री ने फिर प्रश्न किया, "इस नगर में दाता कौन है ?" उसे उत्तर मिला, "धोबी ही यहां का सबसे बड़ा दाता है, जो प्रातःकाल कपड़े धोने अथवा रंगने के लिए ले जाता है और सायंकाल के समय लौटा देता है ।" यात्री ने फिर पूछा, "इस नगर में चतुर व्यक्ति कौन है ?" तो ब्राह्मण ने उत्तर दिया, "इस नगर के सभी व्यक्ति दूसरों का धन और उनकी स्त्री का हरण करने में चतुर हैं ।" यात्री ने फिर पूछा "ऐसी अवस्था में तुम्हारा जीवन यहां कैसे बीतता है ?" ब्राह्मण ने उत्तर दिया, "मैं विष में पैदा होने वाले कीड़े के समान हूं, जो उसी में उत्पन्न होता है लेकिन फिर भी विष के प्रभाव से मुक्त रहता है । विष का उस पर कोई असर नहीं होता । मैं उसी प्रकार इन लोगों के साथ अपना जीवन बिता रहा हूं ।" ।
    en:
      title: 'Chapter 12 - Verse 9'
      subtitle: ''
      image: ''
      description: |-
        A stranger asked a Brāhmaṇa, 'Tell me, who is great in this city?' The Brāhmaṇa replied, 'The cluster of palmyra trees is great.' Then the traveller asked, 'Who is the most charitable person?' The Brāhmaṇa answered, 'The washerman who takes the clothes in the morning and gives them back in the evening is the most charitable.' He then asked, 'Who is the ablest man?' The Brāhmaṇa answered, 'Everyone is expert in robbing others of their wives and wealth.' The man then asked the Brāhmaṇa, 'How do you manage to live in such a city?' The Brāhmaṇa replied, 'As a worm survives while even in a filthy place so do I survive here!'
- id: '10'
  type: leaf
  paginated: true
  meta:
    hi:
      title: 'अध्याय १२ - श्लोक १०'
      subtitle: ''
      image: ''
      description: |-
        जिन घरों में ब्राह्मणों के पांव धोने वाले जल से कीचड़ न हुआ हो, जहां वेद आदि शास्त्रों के पाठ न होते हों, जिसमें स्वाहा और स्वधा इन शब्दों का उच्चारण न होता हो, वे घर श्मशान के समान हैं ।
    en:
      title: 'Chapter 12 - Verse 10'
      subtitle: ''
      image: ''
      description: |-
        The house in which the lotus feet of Brāhmaṇas are not washed, in which Vedic mantras are not loudly recited, and in which the holy rites of Svāhā (sacrificial offerings to the Supreme Lord) and Svadhā (offerings to the ancestors) are not performed, is like a crematorium.
- id: '11'
  type: leaf
  paginated: true
  meta:
    hi:
      title: 'अध्याय १२ - श्लोक ११'
      subtitle: ''
      image: ''
      description: |-
        किसी सांसारिक पुरुष ने किसी संत-महात्मा को अत्यंत आनंद की स्थिति में देखकर उनसे उनके बंधु-बांधवों के बारे में पूछा, तो संत ने उत्तर दिया, "सत्य ही मेरी माता है और ज्ञान मेरा पिता है, धर्म ही मेरा भाई है और दया मेरी बहन है, शांति मेरी पत्नी है और क्षमा मेरा पुत्र है, यह छह ही मेरे परिवार के सदस्य हैं, मेरे बन्धु-बान्धव हैं, मेरे रिश्तेदार हैं ।" ।
    en:
      title: 'Chapter 12 - Verse 11'
      subtitle: ''
      image: ''
      description: |-
        (It is said that a sadhu, when asked about his family, replied thusly): 'truth is my mother, and my father is spiritual knowledge; Dharma (righteous conduct) is my brother, and mercy is my sister, inner peace is my wife, and forgiveness is my son: these six makes my family.'
- id: '12'
  type: leaf
  paginated: true
  meta:
    hi:
      title: 'अध्याय १२ - श्लोक १२'
      subtitle: ''
      image: ''
      description: |-
        यह शरीर अनित्य है अर्थात नाशवान है, धन-सम्पत्ति भी सदा किसी के पास स्थिर नहीं रहती, मृत्यु सदैव प्रत्येक के पास रहती है, इसलिए प्रत्येक व्यक्ति को धर्माचरण करना चाहिए ।
    en:
      title: 'Chapter 12 - Verse 12'
      subtitle: ''
      image: ''
      description: |-
        Our bodies are perishable, wealth is not at all permanent and death is always nearby. Therefore we must immediately engage in acts of merit.
- id: '13'
  type: leaf
  paginated: true
  meta:
    hi:
      title: 'अध्याय १२ - श्लोक १३'
      subtitle: ''
      image: ''
      description: |-
        अर्जुन श्रीकृष्ण से कहते हैं - "किसी ब्राह्मण के लिए भोजन का निमंत्रण मिलना ही उत्सव है । गौओं के लिए ताजी नई घास प्राप्त होना ही उत्सव के समान है । पति में उत्साह की वृद्धि होते रहना ही स्त्रियों के लिए उत्सव के समान है । और मेरे लिए तो श्रीकृष्ण के चरणों में अनुराग ही उत्सव के समान है ।" ।
    en:
      title: 'Chapter 12 - Verse 13'
      subtitle: ''
      image: ''
      description: |-
        Arjuna says to Krishna. 'Brāhmaṇas find joy in going to feasts, cows find joy in eating their tender grass, wives find joy in the company of their husbands, and know, O Krishna, that in the same way I rejoice in battle.
- id: '14'
  type: leaf
  paginated: true
  meta:
    hi:
      title: 'अध्याय १२ - श्लोक १४'
      subtitle: ''
      image: ''
      description: |-
        जो व्यक्ति दूसरी स्त्रियों को माता के समान देखता है, दूसरों के धन को मिट्टी के ढेले के समान समझता है और संसार के सभी प्राणियों के सुख दुःख को अपने सुख दुःख के समान देखता है, उसी को सही दृष्टी प्राप्त है और वही विद्वान है ।
    en:
      title: 'Chapter 12 - Verse 14'
      subtitle: ''
      image: ''
      description: |-
        He who regards another's wife as his mother, the wealth that does not belong to him as a lump of mud, and the pleasure and pain of all other living beings as his own -- truly sees things in the right perspective, and he is a true Pandit.
- id: '15'
  type: leaf
  paginated: true
  meta:
    hi:
      title: 'अध्याय १२ - श्लोक १५'
      subtitle: ''
      image: ''
      description: |-
        धर्म में निरंतर लगे रहना, मुख से मीठे वचन बोलना, दान देने में सदैव उत्सुक रहना, मित्र के प्रति कोई भेद-भाव न रखना, गुरु के प्रति नम्रता और अपने मन में गंभीरता, अपने आचरण में पवित्रता, गुणों के ग्रहण करने में रुचि, शास्त्रों का विशेष ज्ञान, रूप में सौंदर्य और प्रभु में भक्ति आदि का होना-ये गुण सज्जन पुरुषों में ही दिखाई देते हैं ।
    en:
      title: 'Chapter 12 - Verse 15'
      subtitle: ''
      image: ''
      description: |-
        'O Rāghava, the love of virtue, pleasing speech, and an ardent desire for performing acts of charity, guileless dealings with friends, humility in the guru's presence, deep tranquillity of mind, pure conduct, discernment of virtues, realised knowledge of the sastras, beauty of form and devotion to God are all found in you.' (The great sage Vaśiṣṭha Muni, the spiritual preceptor of the dynasty of the sun, said this to Lord Rāmacandra at the time of His proposed coronation).
- id: '16'
  type: leaf
  paginated: true
  meta:
    hi:
      title: 'अध्याय १२ - श्लोक १६'
      subtitle: ''
      image: ''
      description: |-
        सबकी कामनाओं की पूर्ति करने वाला कल्पवृक्ष लकड़ी है, सुवर्ण का सुमेरु पर्वत निश्छल है, चिंताओं को दूर करने वाली मणि (चिंतामणि) एक पत्थर है, सूर्य भयंकर रूप से प्रचंड किरणों वाला है, चंद्रमा की कलाएं क्षीण होती रहती हैं, समुद्र खारा है, कामदेव का कोई शरीर नहीं, दानशील बलि दैत्य हैं, कामधेनु अर्थात सबकी इच्छा पूर्ण करने वाली गाय एक पशु है, मैं इन सबको आपके समान अर्थात आपके बराबर नहीं समझता । हे प्रभु राम! आपकी तुलना किसके साथ की जाए ? अर्थात् आप अतुलनीय हैं ।
    en:
      title: 'Chapter 12 - Verse 16'
      subtitle: ''
      image: ''
      description: |-
        The desire tree (Kalpavṛkṣa) is wood; the golden Mount Sumeru is motionless; the wish-fulfilling gem Ciṃtāmaṇi is just a stone; the sun is scorching; the moon is prone to wane; the boundless ocean is saline; the God of lust lost his body (due to Shiva's wrath); charitable King Bali, was born into a clan of demons; and Kāmadhenu (the cow of heaven) is a mere beast. O Lord Rāma! I cannot compare you to any one of these (taking their merits into account).
- id: '17'
  type: leaf
  paginated: true
  meta:
    hi:
      title: 'अध्याय १२ - श्लोक १७'
      subtitle: ''
      image: ''
      description: |-
        व्यक्ति सभी स्थानों से कुछ न कुछ सीख सकता है । उसे राजपुत्रों से नम्रता और सुशीलता, विद्वानों से प्रिय वचन बोलना, जुआरियों से मिथ्या-भाषण अर्थात सही स्थिति का पता न लगने देना और स्त्रियों से छल करना सीखना चाहिए ।
    en:
      title: 'Chapter 12 - Verse 17'
      subtitle: ''
      image: ''
      description: |-
        Courtesy should be learned from princes, the art of conversation from pandits, lying should be learned from gamblers and deceitful ways should be learned from women.
- id: '18'
  type: leaf
  paginated: true
  meta:
    hi:
      title: 'अध्याय १२ - श्लोक १८'
      subtitle: ''
      image: ''
      description: |-
        जो व्यक्ति बिना विचारे और बिना देखे शक्ति से अधिक खर्च करता है, निर्बल होने पर भी जो लड़ाई-झगड़े में रुचि रखता है, अपनी पत्नी को दुर्लक्षित करने वाला है, जो अपने आचरण पर ध्यान नहीं देता है, वह जल्दी ही नष्ट हो जाता है ।
    en:
      title: 'Chapter 12 - Verse 18'
      subtitle: ''
      image: ''
      description: |-
        The unthinking spender, the homeless urchin, the quarrel monger, the man who neglects his wife and is heedless in his actions -- all these will soon come to ruination.
- id: '19'
  type: leaf
  paginated: true
  meta:
    hi:
      title: 'अध्याय १२ - श्लोक १९'
      subtitle: ''
      image: ''
      description: |-
        बुद्धिमान मनुष्य को भोजन प्राप्ति के संबंध में चिंता नहीं करनी चाहिए, उसे केवल धर्म-कर्म के संबंध में चिंतन करना चाहिए, क्योंकि मनुष्य के जन्म के समय ही भोजन का प्रबंध हो जाता है ।
    en:
      title: 'Chapter 12 - Verse 19'
      subtitle: ''
      image: ''
      description: |-
        The wise man should not be anxious about his food; he should be anxious to be engaged only in Dharma. the food of each man is created for him at his birth.
- id: '20'
  type: leaf
  paginated: true
  meta:
    hi:
      title: 'अध्याय १२ - श्लोक २०'
      subtitle: ''
      image: ''
      description: |-
        जैसे बूंद-बूंद से घड़ा भर जाता है, उसी प्रकार निरंतर इकट्ठा करते रहने से विद्या, धर्म और धन की प्राप्ति होती है ।
    en:
      title: 'Chapter 12 - Verse 20'
      subtitle: ''
      image: ''
      description: |-
        As centesimal droppings will fill a pot so also are knowledge, Dharma and wealth gradually obtained.
- id: '21'
  type: leaf
  paginated: true
  meta:
    hi:
      title: 'अध्याय १२ - श्लोक २१'
      subtitle: ''
      image: ''
      description: |-
        जो व्यक्ति दुष्ट है, वह परिपक्व अवस्था का हो जाने पर भी दुष्ट ही बना रहता है, जैसे इंद्रायण का फल पक जाने पर भी मीठा नहीं होता, कड़वा ही बना रहता है ।
    en:
      title: 'Chapter 12 - Verse 21'
      subtitle: ''
      image: ''
      description: |-
        The man who remains a fool even if he has reached maturity, is really a fool, just as the Indra-Varuṇa's fruit does not become sweet no matter how ripe it might become.
