- id: '1'
  type: leaf
  paginated: true
  meta:
    hi:
      title: 'अध्याय १४ - श्लोक १'
      subtitle: ''
      image: ''
      description: |-
        इस पृथ्वी पर तीन ही रत्न हैं - जल, अन्न और हितकारी वचन, परंतु मूर्ख लोग पत्थर के टुकड़े को रत्न कहते हैं ।
    en:
      title: 'Chapter 14 - Verse 1'
      subtitle: ''
      image: ''
      description: |-
        There are three gems upon this earth; food, water, and pleasing words -- fools (Mūḍhas) consider pieces of rocks as gems.
- id: '2'
  type: leaf
  paginated: true
  meta:
    hi:
      title: 'अध्याय १४ - श्लोक २'
      subtitle: ''
      image: ''
      description: |-
        दरिद्रता, रोग, दुख, बंधन तथा आपत्तियां - ये सब मनुष्य के अधर्म रूपी वृक्ष के फल हैं ।
    en:
      title: 'Chapter 14 - Verse 2'
      subtitle: ''
      image: ''
      description: |-
        Poverty, disease, sorrow, imprisonment and other evils are the fruits borne by the tree of one's own sins.
- id: '3'
  type: leaf
  paginated: true
  meta:
    hi:
      title: 'अध्याय १४ - श्लोक ३'
      subtitle: ''
      image: ''
      description: |-
        धन भी पुनः प्राप्त हो सकता है, मित्र भी मिल सकते हैं, पत्नी भी फिर से मिल सकती है । ये सब वस्तुएं मनुष्य को बार-बार प्राप्त हो सकती हैं, परंतु यह शरीर बार-बार प्राप्त नहीं हो सकता ।
    en:
      title: 'Chapter 14 - Verse 3'
      subtitle: ''
      image: ''
      description: |-
        Wealth, a friend, a wife, and a kingdom may be regained; but this body when lost may never be acquired again.
- id: '4'
  type: leaf
  paginated: true
  meta:
    hi:
      title: 'अध्याय १४ - श्लोक ४'
      subtitle: ''
      image: ''
      description: |-
        निश्चित रूप से बहुत से मनुष्य मिलकर शत्रु को जीत सकते हैं । मनुष्यों का समुदाय अर्थात उनका सगंठन शत्रु को जीतने में उसी प्रकार सफल रहता है, जिस प्रकार इकट्ठे किए हुए तिनके जल की धारा को रोक देते हैं अर्थात घास-फूस का छप्पर वर्षा के पानी से रक्षा करता है ।
    en:
      title: 'Chapter 14 - Verse 4'
      subtitle: ''
      image: ''
      description: |-
        The enemy can be overcome by the union of large numbers, just as grass through its collectiveness wards off erosion caused by heavy rainfall.
- id: '5'
  type: leaf
  paginated: true
  meta:
    hi:
      title: 'अध्याय १४ - श्लोक ५'
      subtitle: ''
      image: ''
      description: |-
        जल पर तेल, दुष्ट व्यक्ति के पास गुप्त वार्ता, सुपात्र व्यक्ति को दिया गया दान, बुद्धिमान का शास्त्रज्ञान ये सभी बातें ऐसी हैं, जो पूरी होने पर वस्तु की शक्ति अर्थात विशेषता से बिना किसी प्रयास के स्वयं फैल जाती हैं, इनका विस्तार हो जाता है ।
    en:
      title: 'Chapter 14 - Verse 5'
      subtitle: ''
      image: ''
      description: |-
        Oil on water, a secret communicated to a base man, a gift given to a worthy receiver, and scriptural instruction given to an intelligent man spread out by virtue of their nature.
- id: '6'
  type: leaf
  paginated: true
  meta:
    hi:
      title: 'अध्याय १४ - श्लोक ६'
      subtitle: ''
      image: ''
      description: |-
        धार्मिक कथा आदि के सुनने के समय, श्मशान भूमि में और रोगी होने पर, मनुष्य के मन में जो सद्बुद्धि उत्पन्न होती है, यदि वह सदैव स्थिर है तो मनुष्य संसार के बंधनों से छूट सकता है ।
    en:
      title: 'Chapter 14 - Verse 6'
      subtitle: ''
      image: ''
      description: |-
        If men always retain the state of mind they experience when hearing religious instruction, when present at a crematorium ground, and when in sickness -- then who could not attain liberation?
- id: '7'
  type: leaf
  paginated: true
  meta:
    hi:
      title: 'अध्याय १४ - श्लोक ७'
      subtitle: ''
      image: ''
      description: |-
        दुष्कर्म करने के बाद पश्चात्ताप करने वाले मनुष्य की बुद्धि जिस प्रकार की होती है, वैसी बुद्धि यदि पाप करने से पहले भी हो जाए तो सभी को मुक्ति प्राप्त हो सकती है ।
    en:
      title: 'Chapter 14 - Verse 7'
      subtitle: ''
      image: ''
      description: |-
        If a man should feel before, as he feels after, repentance -- then who would not attain perfection?
- id: '8'
  type: leaf
  paginated: true
  meta:
    hi:
      title: 'अध्याय १४ - श्लोक ८'
      subtitle: ''
      image: ''
      description: |-
        दान, तपस्या, वीरता, विज्ञान, विनम्रता और नीतिवान होने में मनुष्य को सबसे बड़ा होने का अभिमान नहीं करना चाहिए, क्योंकि पृथ्वी अनेक अमूल्य रत्नों से भरी हुई है ।
    en:
      title: 'Chapter 14 - Verse 8'
      subtitle: ''
      image: ''
      description: |-
        We should not feel pride in our charity, austerity, valour, scriptural knowledge, modesty and morality for the world is full of the rarest gems.
- id: '9'
  type: leaf
  paginated: true
  meta:
    hi:
      title: 'अध्याय १४ - श्लोक ९'
      subtitle: ''
      image: ''
      description: |-
        जो जिसके हृदय में बसा हुआ है, वह यदि बहुत दूर है तो भी उसे दूर नहीं कहा जा सकता और जो जिसके हृदय में समाया हुआ नहीं है, वह बहुत निकट रहने पर भी दूर प्रतीत होता है ।
    en:
      title: 'Chapter 14 - Verse 9'
      subtitle: ''
      image: ''
      description: |-
        He who lives in our mind is near though he may actually be far away; but he who is not in our heart is far though he may really be nearby.
- id: '10'
  type: leaf
  paginated: true
  meta:
    hi:
      title: 'अध्याय १४ - श्लोक १०'
      subtitle: ''
      image: ''
      description: |-
        यदि हम किसी से कुछ पाना चाहते है तो उससे सदा मीठी बात करनी चाहिए, जैसे शिकारी हिरण को पकड़ने से पहले मीठी आवाज में गीत गाता है ।
    en:
      title: 'Chapter 14 - Verse 10'
      subtitle: ''
      image: ''
      description: |-
        We should always speak what would please the man of whom we expect a favour, like the hunter who sings sweetly when he desires to shoot a deer.
- id: '11'
  type: leaf
  paginated: true
  meta:
    hi:
      title: 'अध्याय १४ - श्लोक ११'
      subtitle: ''
      image: ''
      description: |-
        राजा, अग्नि, गुरु और स्त्री इनके पास हर समय नहीं रहना चाहिए । ऐसा करने से मनुष्य को हानि हो सकती है । परंतु इनसे दूर रहने से भी मनुष्य को कोई लाभ नहीं होता । इसलिए इनसे व्यवहार करते समय व्यक्ति को बहुत सोच-समझकर बीच का रास्ता अपनाना चाहिए - इसी को मध्यम मार्ग कहते हैं ।
    en:
      title: 'Chapter 14 - Verse 11'
      subtitle: ''
      image: ''
      description: |-
        It is ruinous to be familiar with the king, fire, the religious preceptor, and a woman. To be altogether indifferent of them is to be deprived of the opportunity to benefit ourselves, hence our association with them must be from a safe distance.
- id: '12'
  type: leaf
  paginated: true
  meta:
    hi:
      title: 'अध्याय १४ - श्लोक १२'
      subtitle: ''
      image: ''
      description: |-
        अग्नि, जल, स्त्रियां, मूर्ख, सांप और राजपरिवार का सेवन करते समय मनुष्य को सदैव सावधान रहना चाहिए, क्योंकि ये छह कभी भी मृत्यु का कारण हो सकते हैं ।
    en:
      title: 'Chapter 14 - Verse 12'
      subtitle: ''
      image: ''
      description: |-
        We should always deal cautiously with fire, water, women, foolish people, serpents, and members of a royal family; for they may, when the occasion presents itself, at once bring about our death.
- id: '13'
  type: leaf
  paginated: true
  meta:
    hi:
      title: 'अध्याय १४ - श्लोक १३'
      subtitle: ''
      image: ''
      description: |-
        संसार में वही जीवित रहता है, जिसमें गुण और धर्म जीवित रहता है । गुणों और धर्म से रहित मनुष्य का जीवन व्यर्थ है ।
    en:
      title: 'Chapter 14 - Verse 13'
      subtitle: ''
      image: ''
      description: |-
        He should be considered to be living who is virtuous and pious, but the life of a man who is destitute of religion and virtues is void of any blessing.
- id: '14'
  type: leaf
  paginated: true
  meta:
    hi:
      title: 'अध्याय १४ - श्लोक १४'
      subtitle: ''
      image: ''
      description: |-
        यदि आप दुनिया को एक काम करके जितना चाहते हो तो इनहें अपने काबू में रखो । इन्हें इधर उधर ना भागने दें ।

        पांच इन्द्रियों के विषय (जो दिखाई देता है, जो सुनाई देता है, जिसकी गंध आती है, जिसका स्वाद आता है, जिसका स्पर्श होता है), पांच इन्द्रिय (आँख, कान, नाक, जिव्हा, त्वचा) पांच कर्मेन्द्रिय (हाथ, पाँव, मुह, जननेंद्रिय, गुदा)
    en:
      title: 'Chapter 14 - Verse 14'
      subtitle: ''
      image: ''
      description: |-
        If you wish to gain control of the world by the performance of a single deed, then keep the following fifteen, which are prone to wander here and there, from getting the upper hand of you: the five sense objects (objects of sight, sound, smell, taste, and touch); the five sense organs (ears, eyes, nose, tongue and skin) and organs of activity (hands, legs, mouth, genitals and anus).
- id: '15'
  type: leaf
  paginated: true
  meta:
    hi:
      title: 'अध्याय १४ - श्लोक १५'
      subtitle: ''
      image: ''
      description: |-
        वही पंडित है जो वही बात बोलता है जो प्रसंग के अनुरूप हो । जो अपनी शक्ति के अनुरूप दुसरो की प्रेम से सेवा करता है । जिसे अपने क्रोध की मर्यादा ज्ञात है ।
    en:
      title: 'Chapter 14 - Verse 15'
      subtitle: ''
      image: ''
      description: |-
        He is a Pandit (man of knowledge) who speaks what is suitable to the occasion, who renders loving service according to his ability, and who knows the limits of his anger.
- id: '16'
  type: leaf
  paginated: true
  meta:
    hi:
      title: 'अध्याय १४ - श्लोक १६'
      subtitle: ''
      image: ''
      description: |-
        एक ही चीज को देखने वाले प्राणी तीन प्रकार से देखते हैं । योगी उसे अति-निंदित शव के रूप में देखते हैं, कामी लोग सुंदर नारी के रूप में देखते हैं और कुत्ता उसे एक मांस के लोथड़े के रूप में देखता है । भेद दृष्टि का है, वस्तु तो एक ही है ।
    en:
      title: 'Chapter 14 - Verse 16'
      subtitle: ''
      image: ''
      description: |-
        One single object appears in three different ways: to the man who practices austerity it appears as a corpse, to the sensual it appears as a woman, and to the dogs as a lump of flesh.
- id: '17'
  type: leaf
  paginated: true
  meta:
    hi:
      title: 'अध्याय १४ - श्लोक १७'
      subtitle: ''
      image: ''
      description: |-
        बुद्धिमान व्यक्ति को चाहिए कि सिद्ध की हुई औषधि, अपने द्वारा किए जाने वाले धर्माचरण, घर के दोष, स्त्री के साथ संभोग, कुभोजन तथा सुने हुए निंदित वचन किसी के सामने प्रकट न करे ।
    en:
      title: 'Chapter 14 - Verse 17'
      subtitle: ''
      image: ''
      description: |-
        A wise man should not divulge the formula of a medicine which he has well prepared; an act of charity which he has performed; domestic conflicts; private affairs with his wife; poorly prepared food he may have been offered; or slang he may have heard.
- id: '18'
  type: leaf
  paginated: true
  meta:
    hi:
      title: 'अध्याय १४ - श्लोक १८'
      subtitle: ''
      image: ''
      description: |-
        जब तक सभी को आनंद देने वाली बसंत ऋतु आरंभ नहीं होती, तब तक कोयल मौन रहकर अपने दिन बिता देती है अर्थात बसंत ऋतु के आने पर ही कोयल की कूक सुनाई देती है ।
    en:
      title: 'Chapter 14 - Verse 18'
      subtitle: ''
      image: ''
      description: |-
        The cuckoos remain silent for a long time (for several seasons) until they are able to sing sweetly (in the Spring ) so as to give joy to all.
- id: '19'
  type: leaf
  paginated: true
  meta:
    hi:
      title: 'अध्याय १४ - श्लोक १९'
      subtitle: ''
      image: ''
      description: |-
        जीवन को सही से बिताने के लिए धर्म का आचरण, धन पैदा करना, अन्नों का संचय, गुरु के वचनों का पालन, अनेक प्रकार की औषधियों का संग्रह विधिपूर्वक और यत्न से करना चाहिए ।
    en:
      title: 'Chapter 14 - Verse 19'
      subtitle: ''
      image: ''
      description: |-
        We should secure and keep the following: the blessings of meritorious deeds, wealth, grain, the words of the spiritual master, and rare medicines. Otherwise life becomes impossible.
- id: '20'
  type: leaf
  paginated: true
  meta:
    hi:
      title: 'अध्याय १४ - श्लोक २०'
      subtitle: ''
      image: ''
      description: |-
        हे मनुष्य! दुष्टों के संग को त्याग दे और सज्जन पुरुषों का संग कर । दिन-रात अच्छे कार्य कर, सदैव संसार को नाशवान समझकर परमेश्वर का ध्यान कर ।
    en:
      title: 'Chapter 14 - Verse 20'
      subtitle: ''
      image: ''
      description: |-
        Avoid wicked company and associate with saintly persons. Acquire virtue day and night, and always meditate on that which is eternal forgetting that which is temporary.
