- id: 'a'
  type: 'leaf'
  paginated: true
  meta:
    hi:
      title: 'चाणक्य नीति'
      subtitle: ''
      image: ''
      description: ''
    en:
      title: 'Chanakya Neeti'
      subtitle: ''
      image: ''
      description: ''
- id: 'b'
  type: 'tree'
  paginated: false
  meta:
    hi:
      title: 'चाणक्य जीवन गाथा'
      subtitle: ''
      image: ''
      description: ''
- id: '1'
  type: 'tree'
  paginated: false
  meta:
    hi:
      title: '१. प्रथमोऽध्यायः'
      subtitle: 'पहला अध्याय'
      image: ''
      description: ''
    en:
      title: 'Chapter 1'
      subtitle: ''
      image: ''
      description: ''
- id: '2'
  type: 'tree'
  paginated: false
  meta:
    hi:
      title: '२. द्वितीयोऽध्यायः'
      subtitle: 'दूसरा अध्याय'
      image: ''
      description: ''
    en:
      title: 'Chapter 2'
      subtitle: ''
      image: ''
      description: ''
- id: '3'
  type: 'tree'
  paginated: false
  meta:
    hi:
      title: '३. तृतीयोऽध्यायः'
      subtitle: 'तीसरा अध्याय'
      image: ''
      description: ''
    en:
      title: 'Chapter 3'
      subtitle: ''
      image: ''
      description: ''
- id: '4'
  type: 'tree'
  paginated: false
  meta:
    hi:
      title: '४. चतुर्थोऽध्यायः'
      subtitle: 'चौथा अध्याय'
      image: ''
      description: ''
    en:
      title: 'Chapter 4'
      subtitle: ''
      image: ''
      description: ''
- id: '5'
  type: 'tree'
  paginated: false
  meta:
    hi:
      title: '५. पंचामोऽध्यायः'
      subtitle: 'पांचवां अध्याय'
      image: ''
      description: ''
    en:
      title: 'Chapter 5'
      subtitle: ''
      image: ''
      description: ''
- id: '6'
  type: 'tree'
  paginated: false
  meta:
    hi:
      title: '६. षष्ठोऽध्यायः'
      subtitle: 'छठा अध्याय'
      image: ''
      description: ''
    en:
      title: 'Chapter 6'
      subtitle: ''
      image: ''
      description: ''
- id: '7'
  type: 'tree'
  paginated: false
  meta:
    hi:
      title: '७. सप्तामोऽध्यायः'
      subtitle: 'सातवां अध्याय'
      image: ''
      description: ''
    en:
      title: 'Chapter 7'
      subtitle: ''
      image: ''
      description: ''
- id: '8'
  type: 'tree'
  paginated: false
  meta:
    hi:
      title: '८. अष्टमोऽध्यायः'
      subtitle: 'आठवां अध्याय'
      image: ''
      description: ''
    en:
      title: 'Chapter 8'
      subtitle: ''
      image: ''
      description: ''
- id: '9'
  type: 'tree'
  paginated: false
  meta:
    hi:
      title: '९. नवमोऽध्यायः'
      subtitle: 'नौवां अध्याय'
      image: ''
      description: ''
    en:
      title: 'Chapter 9'
      subtitle: ''
      image: ''
      description: ''
- id: '10'
  type: 'tree'
  paginated: false
  meta:
    hi:
      title: '१०. दशमोऽध्यायः'
      subtitle: 'दसवां अध्याय'
      image: ''
      description: ''
    en:
      title: 'Chapter 10'
      subtitle: ''
      image: ''
      description: ''
- id: '11'
  type: 'tree'
  paginated: false
  meta:
    hi:
      title: '११. एकादशोऽध्यायः'
      subtitle: 'ग्यारहवां अध्याय'
      image: ''
      description: ''
    en:
      title: 'Chapter 11'
      subtitle: ''
      image: ''
      description: ''
- id: '12'
  type: 'tree'
  paginated: false
  meta:
    hi:
      title: '१२. द्वादशोऽध्यायः'
      subtitle: 'बारहवां अध्याय'
      image: ''
      description: ''
    en:
      title: 'Chapter 12'
      subtitle: ''
      image: ''
      description: ''
- id: '13'
  type: 'tree'
  paginated: false
  meta:
    hi:
      title: '१३. त्रयोदशोऽध्यायः'
      subtitle: 'तेरहवां अध्याय'
      image: ''
      description: ''
    en:
      title: 'Chapter 13'
      subtitle: ''
      image: ''
      description: ''
- id: '14'
  type: 'tree'
  paginated: false
  meta:
    hi:
      title: '१४. चतुर्दशोऽध्यायः'
      subtitle: 'चौदहवां अध्याय'
      image: ''
      description: ''
    en:
      title: 'Chapter 14'
      subtitle: ''
      image: ''
      description: ''
- id: '15'
  type: 'tree'
  paginated: false
  meta:
    hi:
      title: '१५. पंचदशोऽध्यायः'
      subtitle: 'पंद्रहवां अध्याय'
      image: ''
      description: ''
    en:
      title: 'Chapter 15'
      subtitle: ''
      image: ''
      description: ''
- id: '16'
  type: 'tree'
  paginated: false
  meta:
    hi:
      title: '१६. षोडशोऽध्यायः'
      subtitle: 'सोलहवां अध्याय'
      image: ''
      description: ''
    en:
      title: 'Chapter 16'
      subtitle: ''
      image: ''
      description: ''
- id: '17'
  type: 'tree'
  paginated: false
  meta:
    hi:
      title: '१७. सप्तदशोऽध्यायः'
      subtitle: 'सत्रहवां अध्याय'
      image: ''
      description: ''
    en:
      title: 'Chapter 17'
      subtitle: ''
      image: ''
      description: ''