- id: '1'
  type: leaf
  paginated: true
  meta:
    hi:
      title: 'अध्याय ४ - श्लोक १'
      subtitle: ''
      image: ''
      description: |-
        जीव जब मां के गर्भ में आता है तभी उसकी आयु, कर्म, धन, विद्या और मृत्यु–यह पांचों बातें निश्चित हो जाती हैं ।
    en:
      title: 'Chapter 4 - Verse 1'
      subtitle: ''
      image: ''
      description: |-
        These five: the life-span, the type of work, wealth, learning and the time of one's death are determined while one is in the womb.
- id: '2'
  type: leaf
  paginated: true
  meta:
    hi:
      title: 'अध्याय ४ - श्लोक २'
      subtitle: ''
      image: ''
      description: |-
        पुत्र, मित्र और बन्धु-बान्धव साधु लोगों से विमुख हो जाते हैं क्योंकि उन्हें ऐसे लोगों का आचरण मूर्खतापूर्ण लगता है, परंतु जो लोग साधुओं के अनुसार अपना जीवन बिताते हैं, उनका संग करते हैं, उनके अनुकूल आचरण करते हैं, उनके इस कार्य से जो पुण्य प्राप्त होता है, उससे सारा वंश-परिवार कृतकृत्य हो जाता है ।
    en:
      title: 'Chapter 4 - Verse 2'
      subtitle: ''
      image: ''
      description: |-
        Offspring, friends and relatives flee from a devotee of the Lord: yet those who follow him bring merit to their families through their devotion.
- id: '3'
  type: leaf
  paginated: true
  meta:
    hi:
      title: 'अध्याय ४ - श्लोक ३'
      subtitle: ''
      image: ''
      description: |-
        जैसे मछली अपने बच्चों को देखकर, मादा कछुआ ध्यान (देखभाल) से और मादा पक्षी स्पर्श से अपने बच्चों का लालन-पालन करते हैं, उसी प्रकार सज्जनों की संगति भी दर्शन, ध्यान और स्पर्श द्वारा संसर्ग में आए व्यक्ति का पालन करती है ।
    en:
      title: 'Chapter 4 - Verse 3'
      subtitle: ''
      image: ''
      description: |-
        Fish, tortoises, and birds bring up their young by means of sight, attention and touch; so do saintly men afford protection to their associates by the same means.
- id: '4'
  type: leaf
  paginated: true
  meta:
    hi:
      title: 'अध्याय ४ - श्लोक ४'
      subtitle: ''
      image: ''
      description: |-
        जब तक यह शरीर स्वस्थ तथा नीरोग है और जब तक मृत्यु नहीं आती तब तक व्यक्ति को अपने कल्याण के लिए धर्मयुक्त आचरण- अर्थात पुण्य कर्म करने चाहिए क्योंकि करने-कराने का संबंध तो जीवन के साथ ही है । जब मृत्यु हो जाएगी, उस समय वह कुछ भी करने में असमर्थ हो जाएगा अर्थात कुछ भी नहीं कर सकेगा ।
    en:
      title: 'Chapter 4 - Verse 4'
      subtitle: ''
      image: ''
      description: |-
        As long as your body is healthy and under control and death is distant, try to save your soul; when death is immanent what can you do?
- id: '5'
  type: leaf
  paginated: true
  meta:
    hi:
      title: 'अध्याय ४ - श्लोक ५'
      subtitle: ''
      image: ''
      description: |-
        विद्या में कामधेनु के गुण होते हैं । उससे असमय में ही फलों की प्राप्ति होती है । विदेश में विद्या ही माता के समान रक्षा और कल्याण करती है, इसलिए विद्या को गुप्तधन कहा गया है ।
    en:
      title: 'Chapter 4 - Verse 5'
      subtitle: ''
      image: ''
      description: |-
        Learning is like a cow of desire. It, like her, yields in all seasons. Like a mother, it feeds you on your journey. Therefore learning is a hidden treasure.
- id: '6'
  type: leaf
  paginated: true
  meta:
    hi:
      title: 'अध्याय ४ - श्लोक ६'
      subtitle: ''
      image: ''
      description: |-
        सैकड़ों गुणरहित और मूर्ख पुत्रों के बजाय एक गुणवान और विद्वान पुत्र का होना अच्छा है, क्योंकि हजारों तारों की अपेक्षा एक चंद्रमा से ही रात्रि प्रकाशित होती है ।
    en:
      title: 'Chapter 4 - Verse 6'
      subtitle: ''
      image: ''
      description: |-
        A single son endowed with good qualities is far better than a hundred devoid of them. For the moon, though one, dispels the darkness, which the stars, though numerous, can not.
- id: '7'
  type: leaf
  paginated: true
  meta:
    hi:
      title: 'अध्याय ४ - श्लोक ७'
      subtitle: ''
      image: ''
      description: |-
        दीर्घ आयु वाले मूर्ख पुत्र की अपेक्षा पैदा होते ही मर जाने वाला पुत्र अधिक श्रेष्ठ होता है, क्योंकि पैदा होते ही मर जाने वाला पुत्र थोड़े समय के लिए ही दुख का कारण होता है, जबकि लंबी आयु वाला मूर्ख पुत्र मृत्युपर्यन्त दुख देता रहता है ।
    en:
      title: 'Chapter 4 - Verse 7'
      subtitle: ''
      image: ''
      description: |-
        A still-born son as superior to a foolish son endowed with a long life. The first causes grief for but a moment while the latter like a blazing fire consumes his parents in grief for life.
- id: '8'
  type: leaf
  paginated: true
  meta:
    hi:
      title: 'अध्याय ४ - श्लोक ८'
      subtitle: ''
      image: ''
      description: |-
        अशिक्षित तथा अनुपयुक्त स्थान या ग्राम में रहना, नीच व्यक्ति की सेवा, अरुचिकर और पौष्टिकता से रहित भोजन करना, झगड़ालू स्त्री, मूर्ख पुत्र और विधवा कन्या, ये छह बातें ऐसी हैं जो बिना अग्नि के ही शरीर को जलाती रहती हैं ।
    en:
      title: 'Chapter 4 - Verse 8'
      subtitle: ''
      image: ''
      description: |-
        Residing in a small village devoid of proper living facilities, serving a person born of a low family, unwholesome food, a frowning wife, a foolish son, and a widowed daughter burn the body without fire.
- id: '9'
  type: leaf
  paginated: true
  meta:
    hi:
      title: 'अध्याय ४ - श्लोक ९'
      subtitle: ''
      image: ''
      description: |-
        जिस तरह दूध न देने वाली और गर्भ न धारण करने वाली गाय से कोई लाभ नहीं, उसी प्रकार यदि पुत्र भी विद्वान और माता-पिता की सेवा करने वाला न हो तो उससे किसी प्रकार का लाभ नहीं हो सकता ।
    en:
      title: 'Chapter 4 - Verse 9'
      subtitle: ''
      image: ''
      description: |-
        What good is a cow that neither gives milk nor conceives? Similarly, what is the value of the birth of a son if he becomes neither learned nor a pure devotee of the Lord?
- id: '10'
  type: leaf
  paginated: true
  meta:
    hi:
      title: 'अध्याय ४ - श्लोक १०'
      subtitle: ''
      image: ''
      description: |-
        इस संसार में दुखी लोगों को तीन बातों से ही शान्ति प्राप्त हो सकती है-अच्छी संतान, पतिव्रता स्त्री और सज्जनों का संग ।
    en:
      title: 'Chapter 4 - Verse 10'
      subtitle: ''
      image: ''
      description: |-
        When one is consumed by the sorrows of life, three things give him relief: offspring, a wife, and the company of the Lord's devotees.
- id: '11'
  type: leaf
  paginated: true
  meta:
    hi:
      title: 'अध्याय ४ - श्लोक ११'
      subtitle: ''
      image: ''
      description: |-
        राजा एक ही बार आज्ञा देते हैं, पण्डित लोग भी एक ही बार बोलते हैं । कन्या भी एक ही बार विवाह के समय दान में दी जाती है ।
    en:
      title: 'Chapter 4 - Verse 11'
      subtitle: ''
      image: ''
      description: |-
        Kings speak for once, men of learning once, and the daughter is given in marriage once. All these things happen once and only once.
- id: '12'
  type: leaf
  paginated: true
  meta:
    hi:
      title: 'अध्याय ४ - श्लोक १२'
      subtitle: ''
      image: ''
      description: |-
        तप अथवा किसी प्रकार की साधना का कार्य एक अकेला व्यक्ति ही अच्छा करता है, यदि दो छात्र मिलकर पढ़ें तो अध्ययन अच्छा होता है और गाने के लिए यदि तीन व्यक्ति मिलकर अभ्यास करते हैं, तो अच्छा रहता है । इसी प्रकार यदि यात्रा आदि पर जाना हो तो कम-से-कम चार व्यक्तिों को जाना चाहिए । खेती आदि कार्य ठीक प्रकार से चलाने के लिए पांच व्यक्तियों की आवश्यकता होती है, जबकि युद्ध में यह संख्या जितनी हो उतना अच्छा है ।
    en:
      title: 'Chapter 4 - Verse 12'
      subtitle: ''
      image: ''
      description: |-
        Religious austerities should be practiced alone, study by two, and singing by three. A journey should be undertaken by four, agriculture by five, and war by many together.
- id: '13'
  type: leaf
  paginated: true
  meta:
    hi:
      title: 'अध्याय ४ - श्लोक १३'
      subtitle: ''
      image: ''
      description: |-
        पति के लिए वही पत्नी उपयुक्त होती है, जो मन, वचन और कर्म से एक जैसी हो और अपने कार्यों में निपुण हो, इसके साथ ही वह अपने पति से प्रेम रखने वाली तथा सत्य बोलने वाली होनी चाहिए । ऐसी स्त्री को ही श्रेष्ठ पत्नी माना जा सकता है ।
    en:
      title: 'Chapter 4 - Verse 13'
      subtitle: ''
      image: ''
      description: |-
        She is a true wife who is clean (suci), expert, chaste, pleasing to the husband, and truthful.
- id: '14'
  type: leaf
  paginated: true
  meta:
    hi:
      title: 'अध्याय ४ - श्लोक १४'
      subtitle: ''
      image: ''
      description: |-
        जिस घर में बेटा नहीं होता, वह घर शून्य माना जाता है, जिसके कोई बन्धु-बान्धव नहीं होते उसके लिए सारी दिशाएं, सारा संसार ही शून्य होता है । मूर्ख व्यक्ति का हृदय शून्य होता है और दरिद्र व्यक्ति के लिए तो सभी कुछ शून्य है ।
    en:
      title: 'Chapter 4 - Verse 14'
      subtitle: ''
      image: ''
      description: |-
        The house of a childless person is a void, all directions are void to one who has no relatives, the heart of a fool is also void, but to a poverty stricken man all is void.
- id: '15'
  type: leaf
  paginated: true
  meta:
    hi:
      title: 'अध्याय ४ - श्लोक १५'
      subtitle: ''
      image: ''
      description: |-
        अभ्यास के बिना शास्त्र विष होता है, अजीर्ण अर्थात भोजन के ठीक प्रकार से पचे बिना फिर भोजन करना विष के समान होता है, निर्धन और दरिद्र व्यक्ति के लिए समाज में रहना विष के समान होता है और बूढ़े पुरुष के लिए युवती विष के समान होती है ।
    en:
      title: 'Chapter 4 - Verse 15'
      subtitle: ''
      image: ''
      description: |-
        Scriptural lessons not put into practice are poison; a meal is poison to him who suffers from indigestion; a social gathering is poison to a poverty stricken person; and a young wife is poison to an aged man.
- id: '16'
  type: leaf
  paginated: true
  meta:
    hi:
      title: 'अध्याय ४ - श्लोक १६'
      subtitle: ''
      image: ''
      description: |-
        व्यक्ति को चाहिए कि वह ऐसे धर्म का त्याग कर दे जिसमें दया और ममता आदि का अभाव हो, इसी प्रकार विद्या से हीन गुरु का भी त्याग कर देना चाहिए । सदा क्रोध करने वाली स्त्री का त्याग भी श्रेयस्कर है और जिन बन्धु-बान्धवों में प्रेम अथवा स्नेह का अभाव हो, उनका भी त्याग कर देना चाहिए ।
    en:
      title: 'Chapter 4 - Verse 16'
      subtitle: ''
      image: ''
      description: |-
        That man who is without religion and mercy should be rejected. A guru without spiritual knowledge should be rejected. The wife with an offensive face should be given up, and so should relatives who are without affection.
- id: '17'
  type: leaf
  paginated: true
  meta:
    hi:
      title: 'अध्याय ४ - श्लोक १७'
      subtitle: ''
      image: ''
      description: |-
        जो मनुष्य अधिक पैदल चलता अथवा यात्रा में रहता है, वह जल्दी बूढ़ा हो जाता है । यदि घोड़ों को हर समय बांधकर रखा जाएगा तो वे भी जल्दी बूढ़े हो जाते हैं । स्त्रियों से यदि संभोग न किया जाए तो वे जल्दी बूढ़ी हो जाती हैं । इसी प्रकार मनुष्य के कपड़े धूप के कारण जल्दी फट जाते हैं अर्थात धूप उन्हें जल्दी बूढ़ा कर देती है ।
    en:
      title: 'Chapter 4 - Verse 17'
      subtitle: ''
      image: ''
      description: |-
        Constant travel brings old age upon a man; a horse becomes old by being constantly tied up; lack of sexual contact with her husband brings old age upon a woman; and garments become old through being left in the sun.
- id: '18'
  type: leaf
  paginated: true
  meta:
    hi:
      title: 'अध्याय ४ - श्लोक १८'
      subtitle: ''
      image: ''
      description: |-
        समझदार व्यक्ति को चाहिए कि इन बातों के संबंध में सदैव सोचता रहे जैसे कि मेरा समय कैसा है ? मेरे मित्र कितने हैं ? मैं जिस स्थान पर रहता हूं, वह कैसा है ? मेरी आय और व्यय कितना है ? मैं कौन हूं ? मेरी शक्ति क्या है अर्थात मैं क्या करने में समर्थ हूं ? ११८ ॥
    en:
      title: 'Chapter 4 - Verse 18'
      subtitle: ''
      image: ''
      description: |-
        Consider again and again the following: the right time, the right friends, the right place, the right means of income, the right ways of spending, and from whom you derive your power.
- id: '19'
  type: leaf
  paginated: true
  meta:
    hi:
      title: 'अध्याय ४ - श्लोक १९'
      subtitle: ''
      image: ''
      description: |-
        जन्म देने वाला, यज्ञोपवीत कराने वाला गुरु, विद्या दान देने वाला अध्यापक, अन्न देने वाला और भय से मुक्त रखने वाला, यह पांच व्यक्ति पितर माने गए हैं ।
    en:
      title: 'Chapter 4 - Verse 19'
      subtitle: ''
      image: ''
      description: |-
        One who gives birth, one who brings closer (to the Lord, to spirituality - by means of initiating through the sacred thread ceremony), he who gives knowledge, he who gives food, he who protects from fear - these 5 are deemed as fathers.
- id: '20'
  type: leaf
  paginated: true
  meta:
    hi:
      title: 'अध्याय ४ - श्लोक २०'
      subtitle: ''
      image: ''
      description: |-
        राजा की पत्नी, गुरु की पत्नी, मित्र की पत्नी, पत्नी की माता अर्थात सास और जन्म देने वाली अपनी माता, ये पांच माताएं मानी गई हैं, अर्थात् इनका सम्मान माता के समान करना चाहिए । न्याय करते समय भी इन संबंधों को 'मां' की परिभाषा में ही स्वीकार किया जाता है ।
    en:
      title: 'Chapter 4 - Verse 20'
      subtitle: ''
      image: ''
      description: |-
        The King's wife, the Teacher's wife, a friend's  wife, one's own mother and wife's mother (mother-in-law), all these five categories of women are termed as a mother by the traditional usage and are honoured accordingly.
- id: '21'
  type: leaf
  paginated: true
  meta:
    hi:
      title: 'अध्याय ४ - श्लोक २१'
      subtitle: ''
      image: ''
      description: |-
        ब्राह्मण, क्षत्रिय और वैश्य को द्विजाति कहा गया है, इनका देवता यज्ञ है । मुनियों का देवता उनके हृदय में निवास करता है । मंद बुद्धि वालों के लिए मूर्ति ही देवता होती है । जो व्यक्ति समदर्शी हैं, जिनकी समान दृष्टि है, वे परमेश्वर को सर्वत्र विद्यमान मानते हैं ।
    en:
      title: 'Chapter 4 - Verse 21'
      subtitle: ''
      image: ''
      description: |-
        For the twice-born the fire (Agni) is a representative of God. The Supreme Lord resides in the heart of His devotees. Those of average intelligence (alpa-buddhi or kanista-adhikari) see God only in His srimurti, but those of broad vision see the Supreme Lord everywhere.
