- id: '1-2'
  type: 'leaf'
  paginated: true
  meta:
    hi:
      title: 'अध्याय १३ - श्लोक १-२'
      subtitle: ''
      image: ''
      description: |-
        अर्जुन ने कहा हे - हे कृष्ण! मैं प्रकृति एवं पुरुष (भोक्ता), क्षेत्र एवं क्षेत्रज्ञ तथा ज्ञान एवं ज्ञेय के विषय में जानने का इच्छुक हूँ ।

        श्री भगवान् ने कहा - हे कुन्तीपुत्र! यह शरीर क्षेत्र कहलाता है और इस क्षेत्र को जानने वाला क्षेत्रज्ञ है ।
    en:
      title: 'Chapter 13 - Verse 1-2'
      subtitle: ''
      image: ''
      description: |-
        Arjuna said: O my dear Kṛṣṇa, I wish to know about prakṛti [nature], puruṣa [the enjoyer], and the field and the knower of the field, and of knowledge and the object of knowledge. The Supreme Personality of Godhead said: This body, O son of Kuntī, is called the field, and one who knows this body is called the knower of the field.
- id: '3'
  type: 'leaf'
  paginated: true
  meta:
    hi:
      title: 'अध्याय १३ - श्लोक ३'
      subtitle: ''
      image: ''
      description: |-
        हे भरतवंशी! तुम्हें ज्ञात होना चाहिए कि मैं भी समस्त शरीरों में ज्ञाता भी हूँ और इस शरीर तथा इसके ज्ञाता को जान लेना ज्ञान कहलाता है । ऐसा मेरा मत है ।
    en:
      title: 'Chapter 13 - Verse 3'
      subtitle: ''
      image: ''
      description: |-
        O scion of Bharata, you should understand that I am also the knower in all bodies, and to understand this body and its knower is called knowledge. That is My opinion.
- id: '4'
  type: 'leaf'
  paginated: true
  meta:
    hi:
      title: 'अध्याय १३ - श्लोक ४'
      subtitle: ''
      image: ''
      description: |-
        अब तुम मुझसे यह सब संक्षेप में सुनो कि कर्मक्षेत्र क्या है, यह किस प्रकार बना है, इसमें क्या परिवर्तन होते हैं, यह कहाँ से उत्पन्न होता है, इस कर्मक्षेत्र को जानने वाला कौन है और उसके क्या प्रभाव हैं ।
    en:
      title: 'Chapter 13 - Verse 4'
      subtitle: ''
      image: ''
      description: |-
        Now please hear My brief description of this field of activity and how it is constituted, what its changes are, whence it is produced, who that knower of the field of activities is, and what his influences are.
- id: '5'
  type: 'leaf'
  paginated: true
  meta:
    hi:
      title: 'अध्याय १३ - श्लोक ५'
      subtitle: ''
      image: ''
      description: |-
        विभिन्न वैदिक ग्रंथों में विभिन्न ऋषियों ने कार्यकलापों के क्षेत्र तथा उन कार्यकलापों के ज्ञाता के ज्ञान का वर्णन किया है । इसे विशेष रूप से वेदान्त सूत्र में कार्य-कारण के समस्त तर्क समेत प्रस्तुत किया गया है ।
    en:
      title: 'Chapter 13 - Verse 5'
      subtitle: ''
      image: ''
      description: |-
        That knowledge of the field of activities and of the knower of activities is described by various sages in various Vedic writings. It is especially presented in Vedānta-sūtra with all reasoning as to cause and effect.
- id: '6-7'
  type: 'leaf'
  paginated: true
  meta:
    hi:
      title: 'अध्याय १३ - श्लोक ६-७'
      subtitle: ''
      image: ''
      description: |-
        पंच महाभूत, अहंकार, बुद्धि, अव्यक्त (तीनों गुणों की अप्रकट अवस्था), दसों इन्द्रियाँ तथा मन, पाँच इन्द्रियविषय, इच्छा, द्वेष, सुख, दुख, संघात, जीवन के लक्षण तथा धैर्य - इन सब को संक्षेप में कर्म का क्षेत्र तथा उसकी अन्तःक्रियाएँ (विकार) कहा जाता है ।
    en:
      title: 'Chapter 13 - Verse 6-7'
      subtitle: ''
      image: ''
      description: |-
        The five great elements, false ego, intelligence, the unmanifested, the ten senses and the mind, the five sense objects, desire, hatred, happiness, distress, the aggregate, the life symptoms, and convictions – all these are considered, in summary, to be the field of activities and its interactions.
- id: '8-9-10-11-12'
  type: 'leaf'
  paginated: true
  meta:
    hi:
      title: 'अध्याय १३ - श्लोक ८-९-१०-११-१२'
      subtitle: ''
      image: ''
      description: |-
        विनम्रता, दम्भहीनता, अहिंसा, सहिष्णुता, सरलता, प्रामाणिक गुरु के पास जाना, पवित्रता, स्थिरता, आत्मसंयम, इन्द्रियतृप्ति के विषयों का परित्याग, अहंकार का अभाव, जन्म, मृत्यु, वृद्धावस्था तथा रोग के दोषों की अनुभूति, वैराग्य, सन्तान, स्त्री, घर तथा अन्य वस्तुओं की ममता से मुक्ति, अच्छी तथा बुरी घटनाओं के प्रति समभाव, मेरे प्रति निरन्तर अनन्य भक्ति, एकान्त स्थान में रहने की इच्छा, जन समूह से विलगाव, आत्म-साक्षात्कार की महत्ता को स्वीकारना, तथा परम सत्य की दार्शनिक खोज - इन सबको मैं ज्ञान घोषित करता हूँ और इनके अतिरिक्त जो भी है, वह सब अज्ञान है ।
    en:
      title: 'Chapter 13 - Verse 8-9-10-11-12'
      subtitle: ''
      image: ''
      description: |-
        Humility; pridelessness; nonviolence; tolerance; simplicity; approaching a bona fide spiritual master; cleanliness; steadiness; self-control; renunciation of the objects of sense gratification; absence of false ego; the perception of the evil of birth, death, old age and disease; detachment; freedom from entanglement with children, wife, home and the rest; even-mindedness amid pleasant and unpleasant events; constant and unalloyed devotion to Me; aspiring to live in a solitary place; detachment from the general mass of people; accepting the importance of self-realization; and philosophical search for the Absolute Truth – all these I declare to be knowledge, and besides this whatever there may be is ignorance.
- id: '13'
  type: 'leaf'
  paginated: true
  meta:
    hi:
      title: 'अध्याय १३ - श्लोक १३'
      subtitle: ''
      image: ''
      description: |-
        अब मैं तुम्हें ज्ञेय के विषय में बतलाऊँगा, जिसे जानकर तुम नित्य ब्रह्म का आस्वादन कर सकोगे । यह ब्रह्म या आत्मा, जो अनादि है और मेरे अधीन है, इस भौतिक जगत् के कार्य-कारण से परे स्थित है ।
    en:
      title: 'Chapter 13 - Verse 13'
      subtitle: ''
      image: ''
      description: |-
        I shall now explain the knowable, knowing which you will taste the eternal. Brahman, the spirit, beginningless and subordinate to Me, lies beyond the cause and effect of this material world.
- id: '14'
  type: 'leaf'
  paginated: true
  meta:
    hi:
      title: 'अध्याय १३ - श्लोक १४'
      subtitle: ''
      image: ''
      description: |-
        उनके हाथ, पाँव, आखें, सिर तथा मुँह तथा उनके कान सर्वत्र हैं । इस प्रकार परमात्मा सभी वस्तुओं में व्याप्त होकर अवस्थित है ।
    en:
      title: 'Chapter 13 - Verse 14'
      subtitle: ''
      image: ''
      description: |-
        Everywhere are His hands and legs, His eyes, heads and faces, and He has ears everywhere. In this way the Supersoul exists, pervading everything.
- id: '15'
  type: 'leaf'
  paginated: true
  meta:
    hi:
      title: 'अध्याय १३ - श्लोक १५'
      subtitle: ''
      image: ''
      description: |-
        परमात्मा समस्त इन्द्रियों के मूल स्रोत हैं, फिर भी वे इन्द्रियों से रहित हैं । वे समस्त जीवों के पालनकर्ता होकर भी अनासक्त हैं । वे प्रकृति के गुणों से परे हैं, फिर भी वे भौतिक प्रकृति के समस्त गुणों के स्वामी हैं ।
    en:
      title: 'Chapter 13 - Verse 15'
      subtitle: ''
      image: ''
      description: |-
        The Supersoul is the original source of all senses, yet He is without senses. He is unattached, although He is the maintainer of all living beings. He transcends the modes of nature, and at the same time He is the master of all the modes of material nature.
- id: '16'
  type: 'leaf'
  paginated: true
  meta:
    hi:
      title: 'अध्याय १३ - श्लोक १६'
      subtitle: ''
      image: ''
      description: |-
        परमसत्य जड़ तथा जंगम समस्त जीवों के बाहर तथा भीतर स्थित हैं । सूक्ष्म होने के कारण वे भौतिक इन्द्रियों के द्वारा जानने या देखने से परे हैं । यद्यपि वे अत्यन्त दूर रहते हैं, किन्तु हम सबों के निकट भी हैं ।
    en:
      title: 'Chapter 13 - Verse 16'
      subtitle: ''
      image: ''
      description: |-
        The Supreme Truth exists outside and inside of all living beings, the moving and the nonmoving. Because He is subtle, He is beyond the power of the material senses to see or to know. Although far, far away, He is also near to all.
- id: '17'
  type: 'leaf'
  paginated: true
  meta:
    hi:
      title: 'अध्याय १३ - श्लोक १७'
      subtitle: ''
      image: ''
      description: |-
        यद्यपि परमात्मा समस्त जीवों के मध्य विभाजित प्रतीत होता है, लेकिन वह कभी भी विभाजित नहीं है । वह एक रूप में स्थित है । यद्यपि वह प्रत्येक जीव का पालनकर्ता है, लेकिन यह समझना चाहिए कि वह सबों का संहारकर्ता है और सबों को जन्म देता है ।
    en:
      title: 'Chapter 13 - Verse 17'
      subtitle: ''
      image: ''
      description: |-
        Although the Supersoul appears to be divided among all beings, He is never divided. He is situated as one. Although He is the maintainer of every living entity, it is to be understood that He devours and develops all.
- id: '18'
  type: 'leaf'
  paginated: true
  meta:
    hi:
      title: 'अध्याय १३ - श्लोक १८'
      subtitle: ''
      image: ''
      description: |-
        वे समस्त प्रकाशमान वस्तुओं के प्रकाशस्त्रोत हैं । वे भौतिक अंधकार से परे हैं और अगोचर हैं । वे ज्ञान हैं, ज्ञेय हैं और ज्ञान के लक्ष्य हैं । वे सबके हृदय में स्थित हैं ।
    en:
      title: 'Chapter 13 - Verse 18'
      subtitle: ''
      image: ''
      description: |-
        He is the source of light in all luminous objects. He is beyond the darkness of matter and is unmanifested. He is knowledge, He is the object of knowledge, and He is the goal of knowledge. He is situated in everyone’s heart.
- id: '19'
  type: 'leaf'
  paginated: true
  meta:
    hi:
      title: 'अध्याय १३ - श्लोक १९'
      subtitle: ''
      image: ''
      description: |-
        इस प्रकार मैंने कर्म क्षेत्र (शरीर), ज्ञान तथा ज्ञेय का संक्षेप में वर्णन किया है । इसे केवल मेरे भक्त ही पूरी तरह समझ सकते हैं और इस तरह मेरे स्वभाव को प्राप्त होते हैं ।
    en:
      title: 'Chapter 13 - Verse 19'
      subtitle: ''
      image: ''
      description: |-
        Thus the field of activities [the body], knowledge and the knowable have been summarily described by Me. Only My devotees can understand this thoroughly and thus attain to My nature.
- id: '20'
  type: 'leaf'
  paginated: true
  meta:
    hi:
      title: 'अध्याय १३ - श्लोक २०'
      subtitle: ''
      image: ''
      description: |-
        प्रकृति तथा जीवों को अनादि समझना चाहिए । उनके विकार तथा गुण प्रकृतिजन्य हैं ।
    en:
      title: 'Chapter 13 - Verse 20'
      subtitle: ''
      image: ''
      description: |-
        Material nature and the living entities should be understood to be beginningless. Their transformations and the modes of matter are products of material nature.
- id: '21'
  type: 'leaf'
  paginated: true
  meta:
    hi:
      title: 'अध्याय १३ - श्लोक २१'
      subtitle: ''
      image: ''
      description: |-
        प्रकृति समस्त भौतिक कारणों तथा कार्यों (परिणामों) की हेतु कही जाती है, और जीव (पुरुष) इस संसार में विविध सुख-दुख के भोग का कारण कहा जाता है ।
    en:
      title: 'Chapter 13 - Verse 21'
      subtitle: ''
      image: ''
      description: |-
        Nature is said to be the cause of all material causes and effects, whereas the living entity is the cause of the various sufferings and enjoyments in this world.
- id: '22'
  type: 'leaf'
  paginated: true
  meta:
    hi:
      title: 'अध्याय १३ - श्लोक २२'
      subtitle: ''
      image: ''
      description: |-
        इस प्रकार जीव प्रकृति के तीनों गुणों का भोग करता हुआ प्रकृति में ही जीवन बिताता है । यह उस प्रकृति के साथ उसकी संगति के कारण है । इस तरह उसे उत्तम तथा अधम योनियाँ मिलती रहती हैं ।
    en:
      title: 'Chapter 13 - Verse 22'
      subtitle: ''
      image: ''
      description: |-
        The living entity in material nature thus follows the ways of life, enjoying the three modes of nature. This is due to his association with that material nature. Thus he meets with good and evil among various species.
- id: '23'
  type: 'leaf'
  paginated: true
  meta:
    hi:
      title: 'अध्याय १३ - श्लोक २३'
      subtitle: ''
      image: ''
      description: |-
        तो भी इस शरीर में एक अन्य दिव्य भोक्ता है, जो ईश्वर है, परम स्वामी है और साक्षी तथा अनुमति देने वाले के रूप में विद्यमान है और जो परमात्मा कहलाता है ।
    en:
      title: 'Chapter 13 - Verse 23'
      subtitle: ''
      image: ''
      description: |-
        Yet in this body there is another, a transcendental enjoyer, who is the Lord, the supreme proprietor, who exists as the overseer and permitter, and who is known as the Supersoul.
- id: '24'
  type: 'leaf'
  paginated: true
  meta:
    hi:
      title: 'अध्याय १३ - श्लोक २४'
      subtitle: ''
      image: ''
      description: |-
        जो व्यक्ति प्रकृति, जीव तथा प्रकृति के गुणों की अन्तःक्रिया से सम्बन्धित इस विचारधारा को समझ लेता है, उसे मुक्ति की प्राप्ति सुनिश्चित है । उसकी वर्तमान स्थिति चाहे जैसी हो, यहाँ पर उसका पुनर्जन्म नहीं होगा ।
    en:
      title: 'Chapter 13 - Verse 24'
      subtitle: ''
      image: ''
      description: |-
        One who understands this philosophy concerning material nature, the living entity and the interaction of the modes of nature is sure to attain liberation. He will not take birth here again, regardless of his present position.
- id: '25'
  type: 'leaf'
  paginated: true
  meta:
    hi:
      title: 'अध्याय १३ - श्लोक २५'
      subtitle: ''
      image: ''
      description: |-
        कुछ लोग परमात्मा को ध्यान के द्वारा अपने भीतर देखते हैं, तो दूसरे लोग ज्ञान के अनुशीलन द्वारा और कुछ ऐसे हैं जो निष्काम कर्मयोग द्वारा देखते हैं ।
    en:
      title: 'Chapter 13 - Verse 25'
      subtitle: ''
      image: ''
      description: |-
        Some perceive the Supersoul within themselves through meditation, others through the cultivation of knowledge, and still others through working without fruitive desires.
- id: '26'
  type: 'leaf'
  paginated: true
  meta:
    hi:
      title: 'अध्याय १३ - श्लोक २६'
      subtitle: ''
      image: ''
      description: |-
        ऐसे भी लोग हैं जो यद्यपि आध्यात्मिक ज्ञान से अवगत नहीं होते पर अन्यों से परम पुरुष के विषय में सुनकर उनकी पूजा करने लगते हैं । ये लोग भी प्रामाणिक पुरुषों से श्रवण करने की मनोवृत्ति होने के कारण जन्म तथा मृत्यु के पथ को पार कर जाते हैं ।
    en:
      title: 'Chapter 13 - Verse 26'
      subtitle: ''
      image: ''
      description: |-
        Again there are those who, although not conversant in spiritual knowledge, begin to worship the Supreme Person upon hearing about Him from others. Because of their tendency to hear from authorities, they also transcend the path of birth and death.
- id: '27'
  type: 'leaf'
  paginated: true
  meta:
    hi:
      title: 'अध्याय १३ - श्लोक २७'
      subtitle: ''
      image: ''
      description: |-
        हे भरतवंशियों में श्रेष्ठ! यह जान लो कि चर तथा अचर जो भी तुम्हें अस्तित्व में दिख रहा है, वह कर्मक्षेत्र तथा क्षेत्र के ज्ञाता का संयोग मात्र है ।
    en:
      title: 'Chapter 13 - Verse 27'
      subtitle: ''
      image: ''
      description: |-
        O chief of the Bhāratas, know that whatever you see in existence, both the moving and the nonmoving, is only a combination of the field of activities and the knower of the field.
- id: '28'
  type: 'leaf'
  paginated: true
  meta:
    hi:
      title: 'अध्याय १३ - श्लोक २८'
      subtitle: ''
      image: ''
      description: |-
        जो परमात्मा को समस्त शरीरों में आत्मा के साथ देखता है और जो यह समझता है कि इस नश्वर शरीर के भीतर न तो आत्मा, न ही परमात्मा कभी भी विनष्ट होता है, वही वास्तव में देखता है ।
    en:
      title: 'Chapter 13 - Verse 28'
      subtitle: ''
      image: ''
      description: |-
        One who sees the Supersoul accompanying the individual soul in all bodies, and who understands that neither the soul nor the Supersoul within the destructible body is ever destroyed, actually sees.
- id: '29'
  type: 'leaf'
  paginated: true
  meta:
    hi:
      title: 'अध्याय १३ - श्लोक २९'
      subtitle: ''
      image: ''
      description: |-
        जो व्यक्ति परमात्मा को सर्वत्र तथा प्रत्येक जीव में समान रूप से वर्तमान देखता है, वह अपने मन के द्वारा अपने आपको भ्रष्ट नहीं करता । इस प्रकार वह दिव्य गन्तव्य को प्राप्त करता है ।
    en:
      title: 'Chapter 13 - Verse 29'
      subtitle: ''
      image: ''
      description: |-
        One who sees the Supersoul equally present everywhere, in every living being, does not degrade himself by his mind. Thus he approaches the transcendental destination.
- id: '30'
  type: 'leaf'
  paginated: true
  meta:
    hi:
      title: 'अध्याय १३ - श्लोक ३०'
      subtitle: ''
      image: ''
      description: |-
        जो यह देखता है कि सारे कार्य शरीर द्वारा सम्पन्न किये जाते हैं, जिसकी उत्पत्ति प्रकृति से हुई है, और जो देखता है कि आत्मा कुछ भी नहीं करता, वही यथार्थ में देखता है ।
    en:
      title: 'Chapter 13 - Verse 30'
      subtitle: ''
      image: ''
      description: |-
        One who can see that all activities are performed by the body, which is created of material nature, and sees that the self does nothing, actually sees.
- id: '31'
  type: 'leaf'
  paginated: true
  meta:
    hi:
      title: 'अध्याय १३ - श्लोक ३१'
      subtitle: ''
      image: ''
      description: |-
        जब विवेकवान् व्यक्ति विभिन्न भौतिक शरीरों के कारण विभिन्न स्वरूपों को देखना बन्द कर देता है, और यह देखता है कि किस प्रकार से जीव सर्वत्र फैले हुए हैं, तो वह ब्रह्म-बोध को प्राप्त होता है ।
    en:
      title: 'Chapter 13 - Verse 31'
      subtitle: ''
      image: ''
      description: |-
        When a sensible man ceases to see different identities due to different material bodies and he sees how beings are expanded everywhere, he attains to the Brahman conception.
- id: '32'
  type: 'leaf'
  paginated: true
  meta:
    hi:
      title: 'अध्याय १३ - श्लोक ३२'
      subtitle: ''
      image: ''
      description: |-
        शाश्वत दृष्टिसम्पन्न लोग यह देख सकते हैं कि अविनाशी आत्मा दिव्य, शाश्वत तथा गुणों से अतीत है । हे अर्जुन! भौतिक शरीर के साथ सम्पर्क होते हुए भी आत्मा न तो कुछ करता है और न लिप्त होता है ।
    en:
      title: 'Chapter 13 - Verse 32'
      subtitle: ''
      image: ''
      description: |-
        Those with the vision of eternity can see that the imperishable soul is transcendental, eternal, and beyond the modes of nature. Despite contact with the material body, O Arjuna, the soul neither does anything nor is entangled.
- id: '33'
  type: 'leaf'
  paginated: true
  meta:
    hi:
      title: 'अध्याय १३ - श्लोक ३३'
      subtitle: ''
      image: ''
      description: |-
        यद्यपि आकाश सर्वव्यापी है, किन्तु अपनी सूक्ष्म प्रकृति के कारण, किसी वस्तु से लिप्त नहीं होता । इसी तरह ब्रह्मदृष्टि में स्थित आत्मा, शरीर में स्थित रहते हुए भी, शरीर से लिप्त नहीं होता ।
    en:
      title: 'Chapter 13 - Verse 33'
      subtitle: ''
      image: ''
      description: |-
        The sky, due to its subtle nature, does not mix with anything, although it is all-pervading. Similarly, the soul situated in Brahman vision does not mix with the body, though situated in that body.
- id: '34'
  type: 'leaf'
  paginated: true
  meta:
    hi:
      title: 'अध्याय १३ - श्लोक ३४'
      subtitle: ''
      image: ''
      description: |-
        हे भरतपुत्र! जिस प्रकार सूर्य अकेले इस सारे ब्रह्माण्ड को प्रकाशित करता है, उसी प्रकार शरीर के भीतर स्थित एक आत्मा सारे शरीर को चेतना से प्रकाशित करता है ।
    en:
      title: 'Chapter 13 - Verse 34'
      subtitle: ''
      image: ''
      description: |-
        O son of Bharata, as the sun alone illuminates all this universe, so does the living entity, one within the body, illuminate the entire body by consciousness.
- id: '35'
  type: 'leaf'
  paginated: true
  meta:
    hi:
      title: 'अध्याय १३ - श्लोक ३५'
      subtitle: ''
      image: ''
      description: |-
        जो लोग ज्ञान के चक्षुओं से शरीर तथा शरीर के ज्ञाता के अन्तर को देखते हैं और भव-बन्धन से मुक्ति की विधि को भी जानते हैं, उन्हें परमलक्ष्य प्राप्त होता है ।
    en:
      title: 'Chapter 13 - Verse 35'
      subtitle: ''
      image: ''
      description: |-
        Those who see with eyes of knowledge the difference between the body and the knower of the body, and can also understand the process of liberation from bondage in material nature, attain to the supreme goal.
