- id: '1'
  type: leaf
  paginated: true
  meta:
    hi:
      title: 'अध्याय १ - श्लोक १'
      subtitle: ''
      image: ''
      description: |-
        दान देने की इच्छा, मधुर भाषण, धैर्य और उचित अथवा अनुचित का ज्ञान, ये चार गुण मनुष्य में सहज-स्वभाव से ही होते हैं, अभ्यास से इन्हें प्राप्त नहीं किया जा सकता ॥ 1 ॥
    en:
      title: 'Chapter 1 - Verse 1'
      subtitle: ''
      image: ''
      description: ''
- id: '2'
  type: leaf
  paginated: true
  meta:
    hi:
      title: 'अध्याय २ - श्लोक २'
      subtitle: ''
      image: ''
      description: |-
        जो मनुष्य अपने समुदाय के लोगों को छोड़कर दूसरों के समुदाय का सहारा लेता है, वह उसी प्रकार नष्ट हो जाता है जैसे दूसरे के धर्म का आश्रय लेने वाला राजा ॥ 2 ॥
    en:
      title: 'Chapter 2 - Verse 2'
      subtitle: ''
      image: ''
      description: ''
- id: '3'
  type: leaf
  paginated: true
  meta:
    hi:
      title: 'अध्याय ३ - श्लोक ३'
      subtitle: ''
      image: ''
      description: |-
        हाथी लंबे-चौड़े शरीर वाला होता है परंतु उसे बहुत छोटे से अंकुश द्वारा वश में किया जाता है । दीपक जलने पर अंधकार नष्ट हो जाता है तो क्या अंधकार दीपक के आकार का होता है ? हथौड़े की चोट करने से बड़े-बड़े पर्वत गिर पड़ते हैं, तो क्या पर्वत का आकारप्रकार हथौड़े से छोटा होता है ? प्रत्येक वस्तु अपने तेज के कारण ही बलवान होती है, लंबाचौड़ा शरीर कोई मायने नहीं रखता है ॥ 3 ॥
    en:
      title: 'Chapter 3 - Verse 3'
      subtitle: ''
      image: ''
      description: ''
- id: '4'
  type: leaf
  paginated: true
  meta:
    hi:
      title: 'अध्याय ४ - श्लोक ४'
      subtitle: ''
      image: ''
      description: |-
        लोग ऐसा मानते हैं कि कलियुग के दस हजार वर्ष समाप्त होने के बाद परमात्मा पृथ्वी का त्याग कर देते हैं । उससे आधे अर्थात पांच हजार वर्ष समाप्त होने पर गंगा का जल पृथ्वी को छोड़ देता है और उसके आधे वर्ष समाप्त होने पर गांव का देवता गांव छोड़कर चला जाता है ॥ 4 ॥
    en:
      title: 'Chapter 4 - Verse 4'
      subtitle: ''
      image: ''
      description: ''
- id: '5'
  type: leaf
  paginated: true
  meta:
    hi:
      title: 'अध्याय ५ - श्लोक ५'
      subtitle: ''
      image: ''
      description: |-
        जिस व्यक्ति की घर में अधिक आसक्ति है, घर में अधिक मोह और लगाव है, उसे विद्या की प्राप्ति नहीं हो सकती । जो लोग मांस खाते हैं उनमें दया नहीं, जो धन के लोभी होते हैं, उनमें सत्य नहीं होता तथा दुराचारी, व्यभिचारी और भोगविलास में लगे रहने वाले मनुष्य में पवित्रता का अभाव रहता है ॥ 5 ॥
    en:
      title: 'Chapter 5 - Verse 5'
      subtitle: ''
      image: ''
      description: ''
- id: '6'
  type: leaf
  paginated: true
  meta:
    hi:
      title: 'अध्याय ६ - श्लोक ६'
      subtitle: ''
      image: ''
      description: |-
        जिस प्रकार नीम के वृक्ष को दूध और घी से सींचने पर भी उसमें मिठास पैदा नहीं होती, उसी प्रकार दुर्जन व्यक्ति अनेक प्रकार से समझाने-बुझाने पर भी सज्जन नहीं हो पाता ॥ 6 ॥
    en:
      title: 'Chapter 6 - Verse 6'
      subtitle: ''
      image: ''
      description: ''
- id: '7'
  type: leaf
  paginated: true
  meta:
    hi:
      title: 'अध्याय ७ - श्लोक ७'
      subtitle: ''
      image: ''
      description: |-
        जिस दुष्ट का अंतःकरण कामवासना आदि मलों से भरा हुआ है, ऐसा मनुष्य यदि सैकड़ों बार भी तीर्थ-स्नान करे तो भी पवित्र नहीं हो सकता, बिलकुल उसी तरह जिस प्रकार शराब रखने का बर्तन आग पर जलाने से भी शुद्ध नहीं हो सकता ॥ 7 ॥
    en:
      title: 'Chapter 7 - Verse 7'
      subtitle: ''
      image: ''
      description: ''
- id: '8'
  type: leaf
  paginated: true
  meta:
    hi:
      title: 'अध्याय ८ - श्लोक ८'
      subtitle: ''
      image: ''
      description: |-
        जिसे किसी के गुणों की श्रेष्ठता का ज्ञान नहीं, वह सदा उनकी निंदा करता रहता है । उसके ऐसा करने से किसी को आश्चर्य नहीं होता, जैसे भीलनी हाथी के मस्तक में उत्पन्न होने वाली गजमुक्ता को छोड़कर घुघचियों की माला ही धारण करती है ॥ 8 ॥
    en:
      title: 'Chapter 8 - Verse 8'
      subtitle: ''
      image: ''
      description: ''
- id: '9'
  type: leaf
  paginated: true
  meta:
    hi:
      title: 'अध्याय ९ - श्लोक ९'
      subtitle: ''
      image: ''
      description: |-
        जो व्यक्ति पूरे वर्ष तक मौन रहकर चुपचाप भोजन करता है, वह एक करोड़ वर्ष तक स्वर्ग में आदर-सम्मान प्राप्त करता है ॥ 9 ॥
    en:
      title: 'Chapter 9 - Verse 9'
      subtitle: ''
      image: ''
      description: ''
- id: '10'
  type: leaf
  paginated: true
  meta:
    hi:
      title: 'अध्याय १० - श्लोक १०'
      subtitle: ''
      image: ''
      description: |-
        विद्यार्थी के लिए आवश्यक है कि वह काम, क्रोध, लोभ, स्वादिष्ट पदार्थों की इच्छा, शृंगार, खेल-तमाशे, अधिक सोना और चापलूसी करना आदि इन आठ बातों का त्याग कर दे ॥ 10 ॥
    en:
      title: 'Chapter 10 - Verse 10'
      subtitle: ''
      image: ''
      description: ''
- id: '11'
  type: leaf
  paginated: true
  meta:
    hi:
      title: 'अध्याय ११ - श्लोक ११'
      subtitle: ''
      image: ''
      description: |-
        जो बिना खेती की हुई भूमि से उत्पन्न होने वाले फल और कंदमूल आदि को खाकर निर्वाह करता है और सदा जंगल में रहकर ही प्रसन्न रहता है और जो प्रतिदिन श्राद्ध करता है, ऐसा ब्राह्मण ऋषि कहलाता है ॥ 11 ॥
    en:
      title: 'Chapter 11 - Verse 11'
      subtitle: ''
      image: ''
      description: ''
- id: '12'
  type: leaf
  paginated: true
  meta:
    hi:
      title: 'अध्याय १२ - श्लोक १२'
      subtitle: ''
      image: ''
      description: |-
        एक समय भोजन करने से जो संतुष्ट है, जो नित्य अपने कर्तव्यों को पूरा करता रहता है, स्त्री का संग ऋतुकाल में, केवल संतान की उत्पत्ति करने के लिए ही करता है, उपभोग के लिए नहीं, ऐसे ब्राह्मण को ही द्विज कहा जाता है ॥ 12 ॥
    en:
      title: 'Chapter 12 - Verse 12'
      subtitle: ''
      image: ''
      description: ''
- id: '13'
  type: leaf
  paginated: true
  meta:
    hi:
      title: 'अध्याय १३ - श्लोक १३'
      subtitle: ''
      image: ''
      description: |-
        सदा सांसारिक कार्यों में संलग्न, पशुओं के पालक, व्यापार और खेती आदि करने वाले ब्राह्मण को वैश्य कहा जाता है ॥ 13 ॥
    en:
      title: 'Chapter 13 - Verse 13'
      subtitle: ''
      image: ''
      description: ''
- id: '14'
  type: leaf
  paginated: true
  meta:
    hi:
      title: 'अध्याय १४ - श्लोक १४'
      subtitle: ''
      image: ''
      description: |-
        जो ब्राह्मण वृक्षों की लाख, तेल, नील, कपड़े आदि रंगने का रंग, शहद, घी, शराब, मांस आदि चीजों का व्यापार करता है, उसे शूद्र कहते हैं ॥ 14 ॥
    en:
      title: 'Chapter 14 - Verse 14'
      subtitle: ''
      image: ''
      description: ''
- id: '15'
  type: leaf
  paginated: true
  meta:
    hi:
      title: 'अध्याय १५ - श्लोक १५'
      subtitle: ''
      image: ''
      description: |-
        जो दूसरों के कार्य को बिगाड़ता है, ढोंगी है, अपना ही स्वार्थ सिद्ध करने में लगा रहता है, दूसरों को धोखा देता है, सबसे द्वेष करता है, ऊपर से देखने में अत्यंत नम्र और अंदर से पैनी छुरी के समान है, ऐसे ब्राह्मण को बिलाव कहा गया है ॥ 15 ॥
    en:
      title: 'Chapter 15 - Verse 15'
      subtitle: ''
      image: ''
      description: ''
- id: '16'
  type: leaf
  paginated: true
  meta:
    hi:
      title: 'अध्याय १६ - श्लोक १६'
      subtitle: ''
      image: ''
      description: |-
        जो ब्राह्मण पानी के स्थानों, बावड़ी, कुआं, तालाब, बाग-बगीचों और मंदिरों में तोड़फोड़ करने में किसी प्रकार का भय न अनुभव करते हों, उन्हें म्लेच्छ कहा जाता है ॥ 16 ॥
    en:
      title: 'Chapter 16 - Verse 16'
      subtitle: ''
      image: ''
      description: ''
- id: '17'
  type: leaf
  paginated: true
  meta:
    hi:
      title: 'अध्याय १७ - श्लोक १७'
      subtitle: ''
      image: ''
      description: |-
        जो देवताओं और गरु के धन को चरा लेता है. दसरों की स्त्रियों के साथ सहवास करता है और जो सभी तरह के प्राणियों के साथ अपना जीवन गुजार लेता है, उस ब्राह्मण को चाण्डाल कहा जाता है ॥ 17 ॥
    en:
      title: 'Chapter 17 - Verse 17'
      subtitle: ''
      image: ''
      description: ''
- id: '18'
  type: leaf
  paginated: true
  meta:
    hi:
      title: 'अध्याय १८ - श्लोक १८'
      subtitle: ''
      image: ''
      description: |-
        शहद का संग्रह करने में आदर्श मधुमक्खियों को भी पश्चात्ताप करना पड़ता है, क्योंकि शहद का दान न करने से शहद नष्ट हो जाता है । इसी प्रकार कुछ लोग धन का दान नहीं करते और जब वह नष्ट होने लगता है तो पश्चात्ताप करते हैं, जबकि कुछ लोग अपने धन का दान के रूप में उचित प्रयोग करते रहते हैं । राजा बलि, कर्ण और विक्रमादित्य दान करने के कारण ही आज तक समाज में सम्मान के पात्र हैं ॥ 18 ॥
    en:
      title: 'Chapter 18 - Verse 18'
      subtitle: ''
      image: ''
      description: ''
