- id: '1'
  type: 'leaf'
  paginated: true
  meta:
    hi:
      title: 'भाग - १'
      subtitle: 'मङ्गलाचरण'
      image: ''
      description: ''
    en:
      title: 'Part - 1'
      subtitle: 'Invocations'
      image: ''
      description: ''
- id: '2'
  type: 'leaf'
  paginated: true
  meta:
    hi:
      title: 'भाग - २'
      subtitle: 'रामराज्याभिषेक की तैयारी, देवताओं की व्याकुलता तथा सरस्वतीजी से उनकी प्रार्थना'
      image: ''
      description: ''
    en:
      title: 'Part - 2'
      subtitle: 'Preparations for Śrī Rāma''s installation as the Prince Regent of Ayodhyā; the god''s concern over the same and their approaching Goddess Sarasvatī for help'
      image: ''
      description: ''
- id: '3'
  type: 'leaf'
  paginated: true
  meta:
    hi:
      title: 'भाग - ३'
      subtitle: 'सरस्वती का मन्थरा की बुद्धि फेरना, कैकेयी मन्थरा-संवाद'
      image: ''
      description: ''
    en:
      title: 'Part - 3'
      subtitle: 'Sarasvatī perverts the mind of Mantharā (a handmaid of queen Kaikeyī); a dialogue between Kaikeyī and Mantharā'
      image: ''
      description: ''
- id: '4'
  type: 'leaf'
  paginated: true
  meta:
    hi:
      title: 'भाग - ४'
      subtitle: 'कैकेयी का कोपभवन में जाना'
      image: ''
      description: ''
    en:
      title: 'Part - 4'
      subtitle: 'Kaikeyī enters the sulking-chamber'
      image: ''
      description: ''
- id: '5'
  type: 'leaf'
  paginated: true
  meta:
    hi:
      title: 'भाग - ५'
      subtitle: 'दशरथ-कैकेयी-संवाद और दशरथ-शोक, सुमन्त्र का महल में जाना और वहाँ से लौटकर श्रीरामजी को महल में भेजना'
      image: ''
      description: ''
    en:
      title: 'Part - 5'
      subtitle: 'Dialogue between king Daśaratha and Kaikeyī; Daśaratha''s lamentation; Sumantra goes to the palace and, returning from it, sends Śrī Rāma to His father'
      image: ''
      description: ''
- id: '6'
  type: 'leaf'
  paginated: true
  meta:
    hi:
      title: 'भाग - ६'
      subtitle: 'श्रीराम-कैकेयी-संवाद'
      image: ''
      description: ''
    en:
      title: 'Part - 6'
      subtitle: 'Dialogue between Śrī Rāma and mother Kaikeyī'
      image: ''
      description: ''
- id: '7'
  type: 'leaf'
  paginated: true
  meta:
    hi:
      title: 'भाग - ७'
      subtitle: 'श्रीराम-दशरथ-संवाद, अवध वासियों का विषाद, कैकेयी को समझाना'
      image: ''
      description: ''
    en:
      title: 'Part - 7'
      subtitle: 'Dialogue between Śrī Rāma and His father; the sadness of the people of Ayodhyā; their remonstrances with Kaikeyī'
      image: ''
      description: ''
- id: '8'
  type: 'leaf'
  paginated: true
  meta:
    hi:
      title: 'भाग - ८'
      subtitle: 'श्रीराम-कौसल्या-संवाद'
      image: ''
      description: ''
    en:
      title: 'Part - 8'
      subtitle: 'Dialogue between Śrī Rāma and mother Kausalyā'
      image: ''
      description: ''
- id: '9'
  type: 'leaf'
  paginated: true
  meta:
    hi:
      title: 'भाग - ९'
      subtitle: 'श्रीसीता-राम-संवाद'
      image: ''
      description: ''
    en:
      title: 'Part - 9'
      subtitle: 'Dialogue between Sītā and Śrī Rāma'
      image: ''
      description: ''
- id: '10'
  type: 'leaf'
  paginated: true
  meta:
    hi:
      title: 'भाग - १०'
      subtitle: 'श्रीराम-कौसल्या-सीता-संवाद'
      image: ''
      description: ''
    en:
      title: 'Part - 10'
      subtitle: 'Dialogue between Śrī Rāma, Kausalyā and Sītā'
      image: ''
      description: ''
- id: '11'
  type: 'leaf'
  paginated: true
  meta:
    hi:
      title: 'भाग - ११'
      subtitle: 'श्रीराम-लक्ष्मण-संवाद'
      image: ''
      description: ''
    en:
      title: 'Part - 11'
      subtitle: 'Dialogue between Śrī Rāma and Lakṣmaṇa'
      image: ''
      description: ''
- id: '12'
  type: 'leaf'
  paginated: true
  meta:
    hi:
      title: 'भाग - १२'
      subtitle: 'श्रीलक्ष्मण-सुमित्रा-संवाद'
      image: ''
      description: ''
    en:
      title: 'Part - 12'
      subtitle: 'Dialogue between Lakṣmaṇa and mother Sumitrā'
      image: ''
      description: ''
- id: '13'
  type: 'leaf'
  paginated: true
  meta:
    hi:
      title: 'भाग - १३'
      subtitle: 'श्रीरामजी, लक्ष्मणजी, सीताजी का महाराज दशरथ के पास विदा माँगने जाना, दशरथजी का सीताजी को समझाना'
      image: ''
      description: ''
    en:
      title: 'Part - 13'
      subtitle: 'Śrī Rāma, Lakṣmaṇa and Sītā call on king Daśaratha to take leave of him; Daśaratha''s advice to Sītā'
      image: ''
      description: ''
- id: '14'
  type: 'leaf'
  paginated: true
  meta:
    hi:
      title: 'भाग - १४'
      subtitle: 'श्रीराम-सीता-लक्ष्मण का वन-गमन और नगर-निवासियों को सोये छोड़कर आगे बढ़ना'
      image: ''
      description: ''
    en:
      title: 'Part - 14'
      subtitle: 'Śrī Rāma, Sītā and Lakṣmaṇa proceed to the woods and slip past the citizens buried in slumber'
      image: ''
      description: ''
- id: '15'
  type: 'leaf'
  paginated: true
  meta:
    hi:
      title: 'भाग - १५'
      subtitle: 'श्रीराम का श्रृङ्गवेरपुर पहुँचना, निषाद के द्वारा सेवा'
      image: ''
      description: ''
    en:
      title: 'Part - 15'
      subtitle: 'Śrī Rāma''s arrival at srngaverapura; the Niṣāda chief''s services'
      image: ''
      description: ''
- id: '16'
  type: 'leaf'
  paginated: true
  meta:
    hi:
      title: 'भाग - १६'
      subtitle: 'लक्ष्मण-निषाद-संवाद, श्रीराम-सीता से सुमन्त्र का संवाद, सुमन्त्र का लौटना'
      image: ''
      description: ''
    en:
      title: 'Part - 16'
      subtitle: 'Dialogue between Lakṣmaṇa and the Niṣāda; Sumantra''s dialogue with Śrī Rāma and Sītā and his returning to Ayodhyā'
      image: ''
      description: ''
- id: '17'
  type: 'leaf'
  paginated: true
  meta:
    hi:
      title: 'भाग - १७'
      subtitle: 'केवट का प्रेम और गङ्गा-पार जाना'
      image: ''
      description: ''
    en:
      title: 'Part - 17'
      subtitle: 'The boatman''s love and the passage across the Gaṅgā'
      image: ''
      description: ''
- id: '18'
  type: 'leaf'
  paginated: true
  meta:
    hi:
      title: 'भाग - १८'
      subtitle: 'प्रयाग पहुँचना, भरद्वाज-संवाद, यमुनातीर निवासियों का प्रेम'
      image: ''
      description: ''
    en:
      title: 'Part - 18'
      subtitle: 'Arrival at Prayāga and dialogue between Śrī Rāma and the sage Bharadvāja; the love of the people inhabiting the bank of the Yamunā'
      image: ''
      description: ''
- id: '19'
  type: 'leaf'
  paginated: true
  meta:
    hi:
      title: 'भाग - १९'
      subtitle: 'तापस-प्रकरण'
      image: ''
      description: ''
    en:
      title: 'Part - 19'
      subtitle: 'The episode of an ascetic'
      image: ''
      description: ''
- id: '20'
  type: 'leaf'
  paginated: true
  meta:
    hi:
      title: 'भाग - २०'
      subtitle: 'यमुना को प्रणाम, वनवासियों का प्रेम'
      image: ''
      description: ''
    en:
      title: 'Part - 20'
      subtitle: 'Śrī Rāma greets the Yamunā; love of the villagers'
      image: ''
      description: ''
- id: '21'
  type: 'leaf'
  paginated: true
  meta:
    hi:
      title: 'भाग - २१'
      subtitle: 'श्रीराम-वाल्मीकि-संवाद'
      image: ''
      description: ''
    en:
      title: 'Part - 21'
      subtitle: 'Dialogue between Śrī Rāma and the sage Vālmīki'
      image: ''
      description: ''
- id: '22'
  type: 'leaf'
  paginated: true
  meta:
    hi:
      title: 'भाग - २२'
      subtitle: 'चित्रकूट में निवास, कोल-भीलों के द्वारा सेवा'
      image: ''
      description: ''
    en:
      title: 'Part - 22'
      subtitle: 'Śrī Rāma takes up His abode at Citrakūṭa; the services of the Kolas and Bhīlas'
      image: ''
      description: ''
- id: '23'
  type: 'leaf'
  paginated: true
  meta:
    hi:
      title: 'भाग - २३'
      subtitle: 'सुमन्त्र का अयोध्या को लौटना और सर्वत्र शोक देखना'
      image: ''
      description: ''
    en:
      title: 'Part - 23'
      subtitle: 'Sumantra returns to Ayodhyā and finds the city a picture of grief'
      image: ''
      description: ''
- id: '24'
  type: 'leaf'
  paginated: true
  meta:
    hi:
      title: 'भाग - २४'
      subtitle: 'दशरथ-सुमन्त्र-संवाद, दशरथ-मरण'
      image: ''
      description: ''
    en:
      title: 'Part - 24'
      subtitle: 'Dialogue between king Daśaratha and Sumantra, Daśaratha''s passing away'
      image: ''
      description: ''
- id: '25'
  type: 'leaf'
  paginated: true
  meta:
    hi:
      title: 'भाग - २५'
      subtitle: 'मुनि वसिष्ठ का भरत को बुलाने के लिये दूत भेजना'
      image: ''
      description: ''
    en:
      title: 'Part - 25'
      subtitle: 'The sage Vasiṣṭha sends envoys to call Bharata'
      image: ''
      description: ''
- id: '26'
  type: 'leaf'
  paginated: true
  meta:
    hi:
      title: 'भाग - २६'
      subtitle: 'श्रीभरत-शत्रुघ्न का आगमन और शोक'
      image: ''
      description: ''
    en:
      title: 'Part - 26'
      subtitle: 'Arrival and lamentation of Bharata and Śatrughna'
      image: ''
      description: ''
- id: '27'
  type: 'leaf'
  paginated: true
  meta:
    hi:
      title: 'भाग - २७'
      subtitle: 'भरत-कौसल्या-संवाद और दशरथजी की अन्त्येष्टि क्रिया'
      image: ''
      description: ''
    en:
      title: 'Part - 27'
      subtitle: 'Dialogue between Bharata and mother Kausalyā and king Daśaratha''s cremation'
      image: ''
      description: ''
- id: '28'
  type: 'leaf'
  paginated: true
  meta:
    hi:
      title: 'भाग - २८'
      subtitle: 'वसिष्ठ-भरत-संवाद, श्रीरामजी को लाने के लिये चित्रकूट जाने की तैयारी'
      image: ''
      description: ''
    en:
      title: 'Part - 28'
      subtitle: 'Dialogue between the sage Vasiṣṭha and Bharata; Bharata prepares for a journey to Citrakūṭa in order to bring Śrī Rāma back to Ayodhyā'
      image: ''
      description: ''
- id: '29'
  type: 'leaf'
  paginated: true
  meta:
    hi:
      title: 'भाग - २९'
      subtitle: 'अयोध्यावासियों सहित श्रीभरत-शत्रुघ्न आदि का वन-गमन'
      image: ''
      description: ''
    en:
      title: 'Part - 29'
      subtitle: 'Departure of Bharata and Śatrughna with the citizens of Ayodhyā to the woods'
      image: ''
      description: ''
- id: '30'
  type: 'leaf'
  paginated: true
  meta:
    hi:
      title: 'भाग - ३०'
      subtitle: 'निषाद की शङ्का और सावधानी'
      image: ''
      description: ''
    en:
      title: 'Part - 30'
      subtitle: 'The Niṣāda''s suspicion and precautions'
      image: ''
      description: ''
- id: '31'
  type: 'leaf'
  paginated: true
  meta:
    hi:
      title: 'भाग - ३१'
      subtitle: 'भरत-निषाद-मिलन और संवाद और भरतजी का तथा नगरवासियों का प्रेम'
      image: ''
      description: ''
    en:
      title: 'Part - 31'
      subtitle: 'Bharata''s meeting and dialogue with the Niṣāda chief; the love of Bharata and the citizens of Ayodhyā for Śrī Rāma'
      image: ''
      description: ''
- id: '32'
  type: 'leaf'
  paginated: true
  meta:
    hi:
      title: 'भाग - ३२'
      subtitle: 'भरतजी का प्रयाग जाना और भरत-भरद्वाज-संवाद'
      image: ''
      description: ''
    en:
      title: 'Part - 32'
      subtitle: 'Bharata''s arrival at Prayāga and dialogue between Bharata and the sage Bharadvāja'
      image: ''
      description: ''
- id: '33'
  type: 'leaf'
  paginated: true
  meta:
    hi:
      title: 'भाग - ३३'
      subtitle: 'भरद्वाज द्वारा भरत का सत्कार'
      image: ''
      description: ''
    en:
      title: 'Part - 33'
      subtitle: 'Bharadvāja shows hospitality to Bharata'
      image: ''
      description: ''
- id: '34'
  type: 'leaf'
  paginated: true
  meta:
    hi:
      title: 'भाग - ३४'
      subtitle: 'इन्द्र-बृहस्पति-संवाद'
      image: ''
      description: ''
    en:
      title: 'Part - 34'
      subtitle: 'Dialogue between Indra and his preceptor (the sage Bṛhaspati)'
      image: ''
      description: ''
- id: '35'
  type: 'leaf'
  paginated: true
  meta:
    hi:
      title: 'भाग - ३५'
      subtitle: 'भरतजी चित्रकूट के मार्ग में'
      image: ''
      description: ''
    en:
      title: 'Part - 35'
      subtitle: 'Bharata on his way to Citrakūṭa'
      image: ''
      description: ''
- id: '36'
  type: 'leaf'
  paginated: true
  meta:
    hi:
      title: 'भाग - ३६'
      subtitle: 'श्रीसीताजी का स्वप्न, श्रीरामजी को कोल-किरातों द्वारा भरतजी के आगमन की सूचना, रामजीका शोक, लक्ष्मणजी का क्रोध'
      image: ''
      description: ''
    en:
      title: 'Part - 36'
      subtitle: 'Sitas dream; the Kolas and Kirātas bring news of Bharata''s arrival to Śrī Rāma; Śrī Rāma''s concern at the report; Lakṣmaṇa''s outburst of passion'
      image: ''
      description: ''
- id: '37'
  type: 'leaf'
  paginated: true
  meta:
    hi:
      title: 'भाग - ३७'
      subtitle: 'श्रीरामजी का लक्ष्मणजी को समझाना एवं भरतजी की महिमा कहना'
      image: ''
      description: ''
    en:
      title: 'Part - 37'
      subtitle: 'Śrī Rāma admonishes Lakṣmaṇa and dwells on Bharata''s greatness'
      image: ''
      description: ''
- id: '38'
  type: 'leaf'
  paginated: true
  meta:
    hi:
      title: 'भाग - ३८'
      subtitle: 'भरतजी का मन्दाकिनी-स्नान, चित्रकूट में पहुँचना, भरतादि सबका परस्पर मिलाप, पिता का शोक और श्राद्ध'
      image: ''
      description: ''
    en:
      title: 'Part - 38'
      subtitle: 'Bharata takes a dip in the Mandākinī and arrives at Citrakūṭa; Bharata and others meet one another, mourn the king''s death and perform his Śrāddha (obsequies)'
      image: ''
      description: ''
- id: '39'
  type: 'leaf'
  paginated: true
  meta:
    hi:
      title: 'भाग - ३९'
      subtitle: 'वनवासियों द्वारा भरतजी की मण्डली का सत्कार, कैकेयी का पश्चात्ताप'
      image: ''
      description: ''
    en:
      title: 'Part - 39'
      subtitle: 'Hospitality of the foresters towards Bharata and his party; Kaikeyī''s remorse'
      image: ''
      description: ''
- id: '40'
  type: 'leaf'
  paginated: true
  meta:
    hi:
      title: 'भाग - ४०'
      subtitle: 'श्रीवसिष्ठजी का भाषण'
      image: ''
      description: ''
    en:
      title: 'Part - 40'
      subtitle: 'Vasiṣṭha''s speech'
      image: ''
      description: ''
- id: '41'
  type: 'leaf'
  paginated: true
  meta:
    hi:
      title: 'भाग - ४१'
      subtitle: 'श्रीराम-भरतादि का संवाद'
      image: ''
      description: ''
    en:
      title: 'Part - 41'
      subtitle: 'Dialogue between Śrī Rāma, Bharata and others'
      image: ''
      description: ''
- id: '42'
  type: 'leaf'
  paginated: true
  meta:
    hi:
      title: 'भाग - ४२'
      subtitle: 'जनकजी का पहुँचना, कोल-किरातादि की भेंट, सबका परस्पर मिलाप'
      image: ''
      description: ''
    en:
      title: 'Part - 42'
      subtitle: 'King Janaka''s arrival at Citrakūṭa; the Kolas and Kirātas offer presents to the visitors and all meet one another'
      image: ''
      description: ''
- id: '43'
  type: 'leaf'
  paginated: true
  meta:
    hi:
      title: 'भाग - ४३'
      subtitle: 'कौसल्या-सुनयना-संवाद, श्रीसीताजी का शील'
      image: ''
      description: ''
    en:
      title: 'Part - 43'
      subtitle: 'Dialogue between queens Kausalyā and Sunayanā (king Janaka''s wife); Sītā''s amiability'
      image: ''
      description: ''
- id: '44'
  type: 'leaf'
  paginated: true
  meta:
    hi:
      title: 'भाग - ४४'
      subtitle: 'जनक-सुनयना-संवाद, भरतजी की महिमा'
      image: ''
      description: ''
    en:
      title: 'Part - 44'
      subtitle: 'Dialogue between king Janaka and his wife; Bharata''s glory'
      image: ''
      description: ''
- id: '45'
  type: 'leaf'
  paginated: true
  meta:
    hi:
      title: 'भाग - ४५'
      subtitle: 'जनक-वसिष्ठादि-संवाद, इन्द्र की चिन्ता, सरस्वती का इन्द्र को समझाना'
      image: ''
      description: ''
    en:
      title: 'Part - 45'
      subtitle: 'Dialogue between king Janaka and Bharata; Indra''s anxiety; Goddess Sarasvatī''s admonition to Indra'
      image: ''
      description: ''
- id: '46'
  type: 'leaf'
  paginated: true
  meta:
    hi:
      title: 'भाग - ४६'
      subtitle: 'श्रीराम-भरत-संवाद'
      image: ''
      description: ''
    en:
      title: 'Part - 46'
      subtitle: 'Dialogue between the sage Vasiṣṭha, Śrī Rāma and Bharata'
      image: ''
      description: ''
- id: '47'
  type: 'leaf'
  paginated: true
  meta:
    hi:
      title: 'भाग - ४७'
      subtitle: 'भरतजी का तीर्थ-जल-स्थापन तथा चित्रकूट भ्रमण'
      image: ''
      description: ''
    en:
      title: 'Part - 47'
      subtitle: 'Bharata deposits the sacred waters; his perambulation through Citrakūṭa'
      image: ''
      description: ''
- id: '48'
  type: 'leaf'
  paginated: true
  meta:
    hi:
      title: 'भाग - ४८'
      subtitle: 'श्रीराम-भरत-संवाद, पादुका-प्रदान, भरतजी की विदाई'
      image: ''
      description: ''
    en:
      title: 'Part - 48'
      subtitle: 'Dialogue between Śrī Rāma and Bharata; the gift of sandals; Bharata''s farewell'
      image: ''
      description: ''
- id: '49'
  type: 'leaf'
  paginated: true
  meta:
    hi:
      title: 'भाग - ४९'
      subtitle: 'भरतजी का अयोध्या लौटना, भरतजी द्वारा पादुका की स्थापना, नन्दिग्राम में निवास और श्रीभरतजी के चरित्र-श्रवण की महिमा'
      image: ''
      description: ''
    en:
      title: 'Part - 49'
      subtitle: 'Returning to Ayodhyā, Bharata enthrones the sandals and takes up his residence at Nandigrama; the virtue of listening to Bharata''s story'
      image: ''
      description: ''
