- id: '1'
  type: leaf
  paginated: true
  meta:
    hi:
      title: 'अध्याय १६ - श्लोक १'
      subtitle: ''
      image: ''
      description: |-
        ऐसा मनुष्य जो न तो मोक्ष पाने के लिए ईश्वर का ध्यान करता है, न स्वर्ग पाने के लिए धर्म का संचय करता है और न कभी स्वप्न में भी स्त्री के स्तनों का आलिंगन कर सम्भोग करता है । ऐसा मनुष्य केवल जन्म लेकर अपनी माँ का यौवन ही ख़राब करता है, ऐसे मनुष्य का जीवन व्यर्थ है ।
    en:
      title: 'Chapter 16 - Verse 1'
      subtitle: ''
      image: ''
      description: |-
        The life of a person is complete scrap and waste who do not pray to the supreme personality of Godhead to attain salvation, not perform a good deed to earn an entry into heaven, and one who has not even dreamt of enjoying a woman. Such a person is compared to an axe on his mother’s youthful beauty, by taking birth from her womb and did not achieve anything in the world.
- id: '2'
  type: leaf
  paginated: true
  meta:
    hi:
      title: 'अध्याय १६ - श्लोक २'
      subtitle: ''
      image: ''
      description: |-
        वेश्याओं (लम्पट स्त्री) की किसी एक से प्रीति नहीं होती । वे बातचीत तो किसी अन्य व्यक्ति से करती हैं, परंतु हाव-भाव पूर्वक देखती किसी अन्य व्यक्ति को हैं और अपने हृदय में चिंतन किसी अन्य व्यक्ति का करती हैं ।
    en:
      title: 'Chapter 16 - Verse 2'
      subtitle: ''
      image: ''
      description: |-
        The heart of a prostitute (lustful woman) is not united; it is divided. While she is talking with one man, she looks lustfully at another and thinks fondly of a third in her heart.
- id: '3'
  type: leaf
  paginated: true
  meta:
    hi:
      title: 'अध्याय १६ - श्लोक ३'
      subtitle: ''
      image: ''
      description: |-
        जो मूर्ख यह समझता है कि कामुक स्त्री केवल उसी से प्रेम करती है, वह उसके वश में होकर कठपुतली के समान उसके इशारों पर नाचता रहता है ।
    en:
      title: 'Chapter 16 - Verse 3'
      subtitle: ''
      image: ''
      description: |-
        The fool (mudha) who fancies that a charming young lady loves him, becomes her slave and he dances like a shakuntal bird tied to a string.
- id: '4'
  type: leaf
  paginated: true
  meta:
    hi:
      title: 'अध्याय १६ - श्लोक ४'
      subtitle: ''
      image: ''
      description: |-
        इस संसार में ऐसा कोई व्यक्ति नहीं, जिसे धन और ऐश्वर्य की प्राप्ति होने पर अभिमान न हुआ हो ? कोई भी विषय भोगों में लिप्त व्यक्ति ऐसा नहीं हुआ, जिसे कष्ट न भोगने पड़े हों । संसार में ऐसा कौन-सा व्यक्ति है, जो सुंदर स्त्रियों के वश में न हुआ हो ? मांगने वाले व्यक्ति को कब सम्मान मिला है और कौन व्यक्ति ऐसा है, जो दुष्ट लोगों के चक्कर में फंसकर कुशलतापूर्वक संसार में रह सकता हो ।
    en:
      title: 'Chapter 16 - Verse 4'
      subtitle: ''
      image: ''
      description: |-
        Who is there who, having become rich, has not become proud? Which licentious (Free) man has put an end to his calamities (A grievous disaster)? Which man in this world has not been overcome by a woman? Who is always loved by the king? Who is there who has not been overcome by the ravages of time? Which beggar has attained glory? Who has become happy by contracting the vices of the wicked?
- id: '5'
  type: leaf
  paginated: true
  meta:
    hi:
      title: 'अध्याय १६ - श्लोक ५'
      subtitle: ''
      image: ''
      description: |-
        आज तक न तो सोने के मृग की रचना हुई है और न ही किसी ने सोने का मृग देखा है, फिर भी श्रीरामचन्द्र स्वर्ण मृग को पकड़ने के लिए उतावले हो गए । यह बात ठीक ही है कि जब मनुष्य के बुरे दिन आते हैं, तो उसकी बुद्धि उल्टी बातें सोचने लगती है ।
    en:
      title: 'Chapter 16 - Verse 5'
      subtitle: ''
      image: ''
      description: |-
        Till date neither the golden deer has been created nor has anyone seen the golden deer, yet Śrī Rāmacandra became impatient to catch the golden deer. It is true that when a man's bad days come, then he starts thinking opposite things.
- id: '6'
  type: leaf
  paginated: true
  meta:
    hi:
      title: 'अध्याय १६ - श्लोक ६'
      subtitle: ''
      image: ''
      description: |-
        मनुष्य अपने अच्छे गुणों के कारण ही श्रेष्ठता को प्राप्त होता है, ऊंचे आसन पर बैठने के कारण नहीं । राजभवन की सबसे ऊंची चोटी पर बैठने पर भी कौआ कभी गरुड़ नहीं बन सकता ।
    en:
      title: 'Chapter 16 - Verse 6'
      subtitle: ''
      image: ''
      description: |-
        A man attains greatness by his merits, not simply by occupying an exalted seat. We cannot call a crow an eagle (garuda) simply because he sits on the top of a tall building.
- id: '7'
  type: leaf
  paginated: true
  meta:
    hi:
      title: 'अध्याय १६ - श्लोक ७'
      subtitle: ''
      image: ''
      description: |-
        सभी स्थानों पर मनुष्य का आदर-सत्कार उसके गुणों के कारण ही होता है । गुणहीन मनुष्य के पास यदि धन के भण्डार भी हों तो भी उसका सम्मान नहीं होता । बहुत थोड़े से प्रकाश वाला, परंतु दाग-धब्बों से रहित दूज का चांद जिस प्रकार पूजा जाता है अथवा शुभ समझा जाता है, पूर्णिमा के चंद्रमा को वैसा सम्मान प्राप्त नहीं होता ।
    en:
      title: 'Chapter 16 - Verse 7'
      subtitle: ''
      image: ''
      description: |-
        Human beings are respected everywhere because of their qualities. Even if a virtuous person has a wealth, he is not respected. The way the moon of Dooj (crescent moon) is worshiped or considered auspicious, the full moon does not get the same respect as the moon of Dooj, which has very little light, but is free from stains.
- id: '8'
  type: leaf
  paginated: true
  meta:
    hi:
      title: 'अध्याय १६ - श्लोक ८'
      subtitle: ''
      image: ''
      description: |-
        जिस मनुष्य के गुणों की तारीफ दूसरे लोग करते हैं, वह गुणों से रहित होने पर भी गुणी मान लिया जाता है, परंतु यदि इंद्र भी अपने मुख से अपनी प्रशंसा करे तो उन्हें छोटा ही माना जाएगा ।
    en:
      title: 'Chapter 16 - Verse 8'
      subtitle: ''
      image: ''
      description: |-
        The man who is praised by others as great is regarded as worthy though he may be really void of all merit. But the man who sings his own praises lowers himself in the estimation of others though he should be Indra (the possessor of all excellences).
- id: '9'
  type: leaf
  paginated: true
  meta:
    hi:
      title: 'अध्याय १६ - श्लोक ९'
      subtitle: ''
      image: ''
      description: |-
        जिस प्रकार सोने के आभूषण में जड़ा हुआ रत्न और भी सुंदर दिखाई देता है, उसी प्रकार व्यक्ति को चाहिए कि विवेकपूर्वक अपने में गुणों का विकास करके अपने व्यक्तित्व को और भी अधिक सुंदर बनाए तथा सदैव गुणों को ग्रहण करे ।
    en:
      title: 'Chapter 16 - Verse 9'
      subtitle: ''
      image: ''
      description: |-
        If good qualities should characterise a man of discrimination, the brilliance of his qualities will be recognised just as a gem which is essentially bright really shines when fixed in an ornament of gold.
- id: '10'
  type: leaf
  paginated: true
  meta:
    hi:
      title: 'अध्याय १६ - श्लोक १०'
      subtitle: ''
      image: ''
      description: |-
        गुणों में सर्वज्ञ-परमात्मा के समान होने पर भी निराश्रित व्यक्ति दुखी होता रहता है, जैसे अत्यन्त मूल्यवान हीरा भी सोने में जड़े जाने की आशा करता है, उसी प्रकार गुणी मनुष्यों को भी किसी सहारे की अपेक्षा रहती है अर्थात गुणी व्यक्ति भी आश्रय के बिना समाज में वह सम्मान प्राप्त नहीं कर पाता, जिसकी उसको अपेक्षा होती है ।
    en:
      title: 'Chapter 16 - Verse 10'
      subtitle: ''
      image: ''
      description: |-
        Even one who by his qualities appears to be all knowing suffers without patronage; the gem, though precious, requires a gold setting.
- id: '11'
  type: leaf
  paginated: true
  meta:
    hi:
      title: 'अध्याय १६ - श्लोक ११'
      subtitle: ''
      image: ''
      description: |-
        जो धन दूसरों को हानि और पीड़ा पहुंचाकर, धर्म विरुद्ध कार्य करके, शत्रु के सामने गिड़गिड़ा कर प्राप्त होता हो, वह धन मुझे नहीं चाहिए । ऐसा धन मेरे पास न आए तो अच्छा है ।
    en:
      title: 'Chapter 16 - Verse 11'
      subtitle: ''
      image: ''
      description: |-
        I do not desire that wealth which is to be attained by causing harm and suffering to others, or by transgressing the rules of virtue, or by flattering an enemy.
- id: '12'
  type: leaf
  paginated: true
  meta:
    hi:
      title: 'अध्याय १६ - श्लोक १२'
      subtitle: ''
      image: ''
      description: |-
        ऐसे धन का भी कोई लाभ नहीं, जो केवल एक ही मनुष्य के काम आए । धन-संपत्ति तो वही श्रेष्ठ है, जिसका लाभ राह चलते लोग भी उठाते हैं अर्थात अन्य लोगों के भी काम आए ।
    en:
      title: 'Chapter 16 - Verse 12'
      subtitle: ''
      image: ''
      description: |-
        There is no value of such money, which is useful for only one person. Wealth is best, when it can be useful for other people too.
- id: '13'
  type: leaf
  paginated: true
  meta:
    hi:
      title: 'अध्याय १६ - श्लोक १३'
      subtitle: ''
      image: ''
      description: |-
        इस संसार में कोई भी प्राणी ऐसा नहीं है जो धन का विभिन्न प्रकार से उपभोग करने पर तृप्त हुआ हो । इस धन का उपभोग इस जीवन के कार्यों, स्त्रियों के सेवन और विभिन्न प्रकार के भोजन आदि पर करने से भी मनुष्य अतृप्त रहेगा और अतृप्त रहते हुए ही इस संसार से चला जाएगा अर्थात धन को किसी भी प्रकार से उपभोग में लाया जाए, मनुष्य तृप्त नहीं होता ।
    en:
      title: 'Chapter 16 - Verse 13'
      subtitle: ''
      image: ''
      description: |-
        There is no person in this world who is satisfied by consuming money in various ways. By consuming this wealth on the works of this life, enjoyment of women and different types of food etc., man will remain unsatisfied and will leave this world only while remaining unsatisfied, that is, money spent on sense enjoyment in any way, would not bring satisfaction.
- id: '14'
  type: leaf
  paginated: true
  meta:
    hi:
      title: 'अध्याय १६ - श्लोक १४'
      subtitle: ''
      image: ''
      description: |-
        सभी प्रकार के अन्न, जल, वस्त्र, भूमिदान आदि, सभी प्रकार के ब्रह्म यज्ञ, देव-यज्ञ और बलि यज्ञ आदि सभी कर्म नष्ट हो जाते हैं अर्थात यह सभी वस्तुएं नष्ट होने वाली हैं, परंतु सुपात्र व्यक्ति को दिया हुआ दान और प्राणिमात्र को दिया गया अभयदान कभी भी नष्ट नहीं होता ।
    en:
      title: 'Chapter 16 - Verse 14'
      subtitle: ''
      image: ''
      description: |-
        All charities and sacrifices (performed for fruitive gain) bring only temporary results, but gifts made to deserving persons and protection offered to all creatures shall never perish.
- id: '15'
  type: leaf
  paginated: true
  meta:
    hi:
      title: 'अध्याय १६ - श्लोक १५'
      subtitle: ''
      image: ''
      description: |-
        संसार में एक तिनका अत्यंत हल्का होता है । तिनके से भी अधिक हल्की रुई होती है, परंतु याचक को तो सबसे अधिक हल्का माना गया है अर्थात व्यक्ति जब कोई चीज किसी से मांग बैठता है, तो वह सभी चीजों से हल्का अर्थात तुच्छ माना जाता है ।
    en:
      title: 'Chapter 16 - Verse 15'
      subtitle: ''
      image: ''
      description: |-
        A blade of grass is light, cotton is lighter, the beggar is infinitely lighter still. Why then does not the wind carry him away? Because it fears that he may ask alms of him.
- id: '16'
  type: leaf
  paginated: true
  meta:
    hi:
      title: 'अध्याय १६ - श्लोक १६'
      subtitle: ''
      image: ''
      description: |-
        अपमानित होकर जीने के बजाय मर जाना अधिक अच्छा है, क्योंकि मृत्यु से तो क्षणभर का ही कष्ट होता है, जबकि अपमानित होने पर व्यक्ति दिन-प्रतिदिन मरता रहता है ।
    en:
      title: 'Chapter 16 - Verse 16'
      subtitle: ''
      image: ''
      description: |-
        It is better to die than to preserve this life by incurring disgrace. The loss of life causes a moment's grief, but disgrace brings grief every day of one's life.
- id: '17'
  type: leaf
  paginated: true
  meta:
    hi:
      title: 'अध्याय १६ - श्लोक १७'
      subtitle: ''
      image: ''
      description: |-
        मधुर बोली वाले से सभी प्राणी प्रसन्न रहते हैं, अतः व्यक्ति को सदैव प्रिय वचन ही बोलने चाहिए, उसे चाहिए कि वह वाणी में अमृतरूपी मधुरता घोलकर बोले । व्यक्ति को वाणी से दरिद्र नहीं होना चाहिए ।
    en:
      title: 'Chapter 16 - Verse 17'
      subtitle: ''
      image: ''
      description: |-
        All the creatures are pleased by loving words; and therefore we should address words that are pleasing to all, for there is no lack of sweet words.
- id: '18'
  type: leaf
  paginated: true
  meta:
    hi:
      title: 'अध्याय १६ - श्लोक १८'
      subtitle: ''
      image: ''
      description: |-
        संसार एक कड़वा वृक्ष है, इसके दो फल ही अमृत जैसे मीठे होते हैं । एक मधुर वाणी और दूसरी सज्जनों की संगति ।
    en:
      title: 'Chapter 16 - Verse 18'
      subtitle: ''
      image: ''
      description: |-
        There are two nectarean fruits hanging from the tree of this world: one is the hearing of sweet words and the other, the society of saintly men.
- id: '19'
  type: leaf
  paginated: true
  meta:
    hi:
      title: 'अध्याय १६ - श्लोक १९'
      subtitle: ''
      image: ''
      description: |-
        अनेक जन्मों में मनुष्य ने दान, अध्ययन और तप आदि जिन बातों का अभ्यास किया, उसी अभ्यास के कारण वह बार-बार उन्हें दोहराया करता है ।
    en:
      title: 'Chapter 16 - Verse 19'
      subtitle: ''
      image: ''
      description: |-
        The good habits of charity, learning and austerity practised during many past lives continue to be cultivated in this birth by virtue of the link (yoga) of this present life to the previous ones.
- id: '20'
  type: leaf
  paginated: true
  meta:
    hi:
      title: 'अध्याय १६ - श्लोक २०'
      subtitle: ''
      image: ''
      description: |-
        जो विद्या पुस्तकों तक ही सीमित है और जो धन दूसरों के पास पड़ा है, आवश्यकता पड़ने पर न तो वह विद्या काम आती है और न ही वह धन उपयोगी हो पाता है ।
    en:
      title: 'Chapter 16 - Verse 20'
      subtitle: ''
      image: ''
      description: |-
        One whose knowledge is confined to books and whose wealth is in the possession of others, can use neither his knowledge nor wealth when the need for them arises.
