- id: '1'
  type: leaf
  paginated: true
  meta:
    hi:
      title: 'अध्याय ५ - श्लोक १'
      subtitle: ''
      image: ''
      description: |-
        ब्राह्मण, क्षत्रिय और वैश्य आदि द्विजों के लिए अग्निहोत्र गुरु के समान आदरणीय है, चारों वर्गों में ब्राह्मण सबसे अधिक श्रेष्ठ और आदरणीय है । स्त्रियों के लिए पति ही गुरु है और घर में आया हुआ अतिथि सभी के आदर-सत्कार के योग्य माना गया है ॥ 1 ॥
    en:
      title: 'Chapter 5 - Verse 1'
      subtitle: ''
      image: ''
      description: ''
- id: '2'
  type: leaf
  paginated: true
  meta:
    hi:
      title: 'अध्याय ५ - श्लोक २'
      subtitle: ''
      image: ''
      description: |-
        जिस प्रकार सोने की परीक्षा चार प्रकार से की जाती है उसे कसौटी पर घिसा जाता है, काटकर देखा जाता है, तपाया जाता है और कूटकर उसकी जांच की जाती है, उसी प्रकार मनुष्य कितना श्रेष्ठ है इसकी पहचान भी इन चार बातों से होती है ॥ 2 ॥
    en:
      title: 'Chapter 5 - Verse 2'
      subtitle: ''
      image: ''
      description: ''
- id: '3'
  type: leaf
  paginated: true
  meta:
    hi:
      title: 'अध्याय ५ - श्लोक ३'
      subtitle: ''
      image: ''
      description: |-
        संकट प्रत्येक मनुष्य पर आते हैं, परंतु बुद्धिमान व्यक्तियों को संकटों और आपत्तियों से तभी तक डरना चाहिए जब तक वे सिर पर न आ जाएं । संकट और दुख आने पर तो व्यक्ति को अपनी पूरी शक्ति से उन्हें दूर करने का प्रयत्न करना चाहिए ॥ 3 ॥
    en:
      title: 'Chapter 5 - Verse 3'
      subtitle: ''
      image: ''
      description: ''
- id: '4'
  type: leaf
  paginated: true
  meta:
    hi:
      title: 'अध्याय ५ - श्लोक ४'
      subtitle: ''
      image: ''
      description: |-
        एक ही माता के पेट और एक ही नक्षत्र में उत्पन्न हुए बालक गुण, कर्म और स्वभाव में एक समान नहीं होते, जैसे बेर वृक्ष के सभी फल और उनके कांटे एक जैसे नहीं होते, उनमें अंतर होता है ॥ 4 ॥
    en:
      title: 'Chapter 5 - Verse 4'
      subtitle: ''
      image: ''
      description: ''
- id: '5'
  type: leaf
  paginated: true
  meta:
    hi:
      title: 'अध्याय ५ - श्लोक ५'
      subtitle: ''
      image: ''
      description: |-
        कोई भी अधिकारी लोभरहित नहीं होता, शृंगार प्रेमी में कामवासना की अधिकता होती ही है । जो व्यक्ति चतुर नहीं है, वह मधुरभाषी भी नहीं हो सकता तथा साफ बात कहने वाला व्यक्ति कभी भी धोखेबाज नहीं होता ॥ 5 ॥
    en:
      title: 'Chapter 5 - Verse 5'
      subtitle: ''
      image: ''
      description: ''
- id: '6'
  type: leaf
  paginated: true
  meta:
    hi:
      title: 'अध्याय ५ - श्लोक ६'
      subtitle: ''
      image: ''
      description: |-
        मूर्ख विद्वानों से वैर भाव रखते हैं । दरिद्र और निर्धन धनवानों को अपना शत्रु समझते हैं । वेश्याएं कुलीन स्त्रियों से द्वेषभाव रखती हैं और विधवा स्त्रियां सुहागिनों को अपना शत्रु मानती हैं ॥ 6 ॥
    en:
      title: 'Chapter 5 - Verse 6'
      subtitle: ''
      image: ''
      description: ''
- id: '7'
  type: leaf
  paginated: true
  meta:
    hi:
      title: 'अध्याय ५ - श्लोक ७'
      subtitle: ''
      image: ''
      description: |-
        आलस्य के कारण विद्या नष्ट हो जाती है, दूसरे के हाथ में गई हुई स्त्रियां नष्ट हो जाती हैं, कम बीज डालने से खेत बेकार हो जाता है और सेनापति के मारे जाने पर सेना नष्ट हो जाती है ॥ 7 ॥
    en:
      title: 'Chapter 5 - Verse 7'
      subtitle: ''
      image: ''
      description: ''
- id: '8'
  type: leaf
  paginated: true
  meta:
    hi:
      title: 'अध्याय ५ - श्लोक ८'
      subtitle: ''
      image: ''
      description: |-
        विद्या की प्राप्ति निरंतर अभ्यास से होती है । अभ्यास से ही विद्या फलवती होती है । उत्तम गुण और स्वभाव से ही कुल का गौरव और यश स्थिर रहता है । श्रेष्ठ पुरुष की पहचान सद्गुणों से होती है । मनुष्य की आंखें देखकर क्रोध का ज्ञान हो जाता है ॥ 8 ॥
    en:
      title: 'Chapter 5 - Verse 8'
      subtitle: ''
      image: ''
      description: ''
- id: '9'
  type: leaf
  paginated: true
  meta:
    hi:
      title: 'अध्याय ५ - श्लोक ९'
      subtitle: ''
      image: ''
      description: |-
        धन से धर्म की रक्षा की जाती है । विद्या को योग के द्वारा बचाया जा सकता है । मधुरता के कारण राजा को बचाया जा सकता है और अच्छी स्त्रियां घर की रक्षक होती हैं ॥ 9 ॥
    en:
      title: 'Chapter 5 - Verse 9'
      subtitle: ''
      image: ''
      description: ''
- id: '10'
  type: leaf
  paginated: true
  meta:
    hi:
      title: 'अध्याय ५ - श्लोक १०'
      subtitle: ''
      image: ''
      description: |-
        विद्वान व्यक्ति के पांडित्य की निंदा करने वाले, शास्त्रों द्वारा कहे गए श्रेष्ठ आचरण को व्यर्थ बताने वाले, धीर, गंभीर और शांत रहने वाले व्यक्ति को ढोंगी और पाखंडी बताने वाले लोग हमेशा दुख उठाते हैं । इस परनिंदा रूप कार्य से कोई लाभ नहीं होता है ॥ 10 ॥
    en:
      title: 'Chapter 5 - Verse 10'
      subtitle: ''
      image: ''
      description: ''
- id: '11'
  type: leaf
  paginated: true
  meta:
    hi:
      title: 'अध्याय ५ - श्लोक ११'
      subtitle: ''
      image: ''
      description: |-
        दान देने से दरिद्रता नष्ट होती है, अच्छे आचरण से कष्ट दूर होते हैं, मनुष्य की दुर्गति समाप्त होती है, बुद्धि से अज्ञान नष्ट होता है अर्थात मूर्खता नष्ट होती है और ईश्वर की भक्ति से भय दूर होता है ॥ 11 ॥
    en:
      title: 'Chapter 5 - Verse 11'
      subtitle: ''
      image: ''
      description: ''
- id: '12'
  type: leaf
  paginated: true
  meta:
    hi:
      title: 'अध्याय ५ - श्लोक १२'
      subtitle: ''
      image: ''
      description: |-
        कामवासना के समान कोई रोग नहीं । मोह से बड़ा कोई शत्रु नहीं । क्रोध जैसी कोई आग नहीं और ज्ञान से बढ़कर इस संसार में सुख देने वाली कोई वस्तु नहीं ॥ 12 ॥
    en:
      title: 'Chapter 5 - Verse 12'
      subtitle: ''
      image: ''
      description: ''
- id: '13'
  type: leaf
  paginated: true
  meta:
    hi:
      title: 'अध्याय ५ - श्लोक १३'
      subtitle: ''
      image: ''
      description: |-
        जिस प्रकार मनुष्य अकेला ही जन्म लेता है, उसी प्रकार अकेले ही उसे पाप और पुण्य का फल भी भोगना पड़ता है । अकेले ही अनेक प्रकार के कष्ट भोगने पड़ते हैं अर्थात अकेले ही उसे नरक का दुख उठाना पड़ता है और अकेला ही वह मोक्ष को प्राप्त होता है ॥ 13 ॥
    en:
      title: 'Chapter 5 - Verse 13'
      subtitle: ''
      image: ''
      description: ''
- id: '14'
  type: leaf
  paginated: true
  meta:
    hi:
      title: 'अध्याय ५ - श्लोक १४'
      subtitle: ''
      image: ''
      description: |-
        जिसे ब्रह्मज्ञान है, उसके लिए स्वर्ग तिनके के समान अर्थात तुच्छ है । शूरवीर के लिए जीवन तिनके के समान होता है । जितेन्द्रिय अर्थात संयमी व्यक्ति के लिए स्त्री (भोग पदार्थ) तिनके के समान होती है और इच्छारहित मनुष्यों के लिए सारा संसार ही तिनके के समान है ॥ 14 ॥
    en:
      title: 'Chapter 5 - Verse 14'
      subtitle: ''
      image: ''
      description: ''
- id: '15'
  type: leaf
  paginated: true
  meta:
    hi:
      title: 'अध्याय ५ - श्लोक १५'
      subtitle: ''
      image: ''
      description: |-
        विदेश में विद्या ही मनुष्य की सच्ची मित्र होती है, घर में अच्छे स्वभाव वाली और गुणवती पत्नी ही मनुष्य की सबसे अच्छी मित्र होती है । रोगी व्यक्ति की मित्र दवाई है और जो मनुष्य मर चुका है उसका धर्म-कर्म ही उसका मित्र होता है ॥ 15 ॥
    en:
      title: 'Chapter 5 - Verse 15'
      subtitle: ''
      image: ''
      description: ''
- id: '16'
  type: leaf
  paginated: true
  meta:
    hi:
      title: 'अध्याय ५ - श्लोक १६'
      subtitle: ''
      image: ''
      description: |-
        समुद्र में बारिश होना, भोजन से तृप्त हुए मनुष्य को फिर से भोजन कराना, धनी लोगों को दान देना और दिन में दीपक जलाना आदि बातें व्यर्थ और निरर्थक होती हैं ॥ 16 ॥
    en:
      title: 'Chapter 5 - Verse 16'
      subtitle: ''
      image: ''
      description: ''
- id: '17'
  type: leaf
  paginated: true
  meta:
    hi:
      title: 'अध्याय ५ - श्लोक १७'
      subtitle: ''
      image: ''
      description: |-
        बादल के जल जैसा दूसरा कोई जल शुद्ध नहीं, आत्मबल के समान दूसरा कोई बल नहीं, नेत्र ज्योति के समान दूसरी कोई ज्योति नहीं और अन्न के समान दूसरा कोई प्रिय पदार्थ नहीं होता ॥ 17 ॥
    en:
      title: 'Chapter 5 - Verse 17'
      subtitle: ''
      image: ''
      description: ''
- id: '18'
  type: leaf
  paginated: true
  meta:
    hi:
      title: 'अध्याय ५ - श्लोक १८'
      subtitle: ''
      image: ''
      description: |-
        धनहीन व्यक्ति और अधिक धन पाना चाहता है, चौपाये अर्थात चार पैर वाले पशु चाहते हैं कि वे बोल सकें, मनुष्य स्वर्ग चाहता है और देवता मोक्ष की कामना करते हैं ॥ 18 ॥
    en:
      title: 'Chapter 5 - Verse 18'
      subtitle: ''
      image: ''
      description: ''
- id: '19'
  type: leaf
  paginated: true
  meta:
    hi:
      title: 'अध्याय ५ - श्लोक १९'
      subtitle: ''
      image: ''
      description: |-
        सत्य के कारण पृथ्वी स्थिर है, सूर्य भी सत्य के बल से प्रकाश देता है, सत्य से ही वायु बहती है, सब सत्य में ही स्थिर है ॥ 19 ॥
    en:
      title: 'Chapter 5 - Verse 19'
      subtitle: ''
      image: ''
      description: ''
- id: '20'
  type: leaf
  paginated: true
  meta:
    hi:
      title: 'अध्याय ५ - श्लोक २०'
      subtitle: ''
      image: ''
      description: |-
        इस चराचर जगत् में लक्ष्मी (धन) चलायमान है अर्थात लक्ष्मी स्थिर नहीं रहती, नष्ट हो जाती है, प्राण भी नाशवान हैं, जीवन और यौवन भी नष्ट होने वाले हैं, इस चराचर संसार में एकमात्र धर्म ही स्थिर है ॥ 20 ॥
    en:
      title: 'Chapter 5 - Verse 20'
      subtitle: ''
      image: ''
      description: ''
- id: '21'
  type: leaf
  paginated: true
  meta:
    hi:
      title: 'अध्याय ५ - श्लोक २१'
      subtitle: ''
      image: ''
      description: |-
        मनुष्य में नाई सबसे अधिक चालाक और होशियार होता है । पक्षियों में कौआ, चार पैरों वाले जानवरों में गीदड़ और स्त्रियों में मालिन अत्यधिक चतुर होती है ॥ 21 ॥
    en:
      title: 'Chapter 5 - Verse 21'
      subtitle: ''
      image: ''
      description: ''
