- id: '1'
  type: leaf
  paginated: true
  meta:
    hi:
      title: 'अध्याय १ - श्लोक १'
      subtitle: ''
      image: ''
      description: |-
        मैं तीनों लोकों - पृथ्वी, अन्तरिक्ष और पाताल के स्वामी सर्वशक्तिमान, सर्वव्यापक परमेश्वर विष्णु को सिर झुकाकर प्रणाम करता हूं । प्रभु को प्रणाम करने के बाद मैं अनेक शास्त्रों से एकत्रित किए गए राजनीति से संबंधित ज्ञान का वर्णन करूंगा ।
    en:
      title: 'Chapter 1 - Verse 1'
      subtitle: ''
      image: ''
      description: |-
        Humbly bowing down before the almighty Lord Sri Viṣṇu, the Lord of the three worlds, I recite maxims of the science of political ethics (Nīti) selected from the various Śāstra.
- id: '2'
  type: leaf
  paginated: true
  meta:
    hi:
      title: 'अध्याय १ - श्लोक २'
      subtitle: ''
      image: ''
      description: |-
        'सत्तमः' अर्थात श्रेष्ठ पुरुष, इस शास्त्र का विधिपूर्वक अध्ययन करके यह बात भली प्रकार जान जाएंगे कि वेद आदि धर्मशास्त्रों में कौन से कार्य करने योग्य बताए गए हैं और कौन से कार्य ऐसे हैं जिन्हें नहीं करना चाहिए । क्या पुण्य है और क्या पाप है तथा धर्म और अधर्म क्या है, इसकी जानकारी भी इस ग्रंथ से हो जाएगी ।
    en:
      title: 'Chapter 1 - Verse 2'
      subtitle: ''
      image: ''
      description: |-
        That man who by the study of these maxims from the satras acquires a knowledge of the most celebrated principles of duty, and understands what ought and what ought not to be followed, and what is good and what is bad, is most excellent.
- id: '3'
  type: leaf
  paginated: true
  meta:
    hi:
      title: 'अध्याय १ - श्लोक ३'
      subtitle: ''
      image: ''
      description: |-
        अब मैं मानवमात्र के कल्याण की कामना से राजनीति के उस ज्ञान का वर्णन करूंगा जिसे जानकर मनुष्य सर्वज्ञ हो जाता है ।
    en:
      title: 'Chapter 1 - Verse 3'
      subtitle: ''
      image: ''
      description: |-
        Therefore with an eye to the public good, I shall speak that which, when understood, will lead to an understanding of things in their proper perspective.
- id: '4'
  type: leaf
  paginated: true
  meta:
    hi:
      title: 'अध्याय १ - श्लोक ४'
      subtitle: ''
      image: ''
      description: |-
        मुर्ख शिष्य को उपदेश देने, दुष्ट-व्यभिचारिणी स्त्री का पालन-पोषण करने, धन के नष्ट होने तथा दुखी व्यक्ति के साथ व्यवहार रखने से बुद्धिमान व्यक्ति को भी कष्ट उठाना पड़ता है ।
    en:
      title: 'Chapter 1 - Verse 4'
      subtitle: ''
      image: ''
      description: |-
        Even a pandit comes to grief by giving instruction to a foolish disciple, by maintaining a wicked wife, and by excessive familiarity with the miserable.
- id: '5'
  type: leaf
  paginated: true
  meta:
    hi:
      title: 'अध्याय १ - श्लोक ५'
      subtitle: ''
      image: ''
      description: |-
        दुष्ट स्वभाव वाली स्त्री, दुष्ट स्वभाव वाला मित्र, सामने बोलने वाला मुंहफट नौकर और ऐसे घर में निवास जहां सांप के होने की संभावना हो, ये सब बातें मृत्यु के समान हैं ।
    en:
      title: 'Chapter 1 - Verse 5'
      subtitle: ''
      image: ''
      description: |-
        A wicked wife, a false friend, a saucy servant and living in a house with a serpent in it are nothing but death.
- id: '6'
  type: leaf
  paginated: true
  meta:
    hi:
      title: 'अध्याय १ - श्लोक ६'
      subtitle: ''
      image: ''
      description: |-
        किसी कष्ट अथवा आपत्तिकाल से बचाव के लिए धन की रक्षा करनी चाहिए और धन खर्च करके भी स्त्रियों की रक्षा करनी चाहिए, परंतु स्त्रियों और धन से भी अधिक आवश्यक यह है कि व्यक्ति अपनी रक्षा करे ।
    en:
      title: 'Chapter 1 - Verse 6'
      subtitle: ''
      image: ''
      description: |-
        One should save his money against hard times, save his wife at the sacrifice of his riches, but invariably one should save his soul even at the sacrifice of his wife and riches.
- id: '7'
  type: leaf
  paginated: true
  meta:
    hi:
      title: 'अध्याय १ - श्लोक ७'
      subtitle: ''
      image: ''
      description: |-
        आपत्तिकाल के लिए धन की रक्षा करनी चाहिए, बिना यह सोचे कि धनवान पुरुषों के पास विपत्ति का क्या काम ? क्योंकि लक्ष्मी तो चंचला है, वह संचित करने पर भी नष्ट हो जाती है ।
    en:
      title: 'Chapter 1 - Verse 7'
      subtitle: ''
      image: ''
      description: |-
        Save your wealth against future calamity. Do not say, 'What fear has a rich man of calamity?' When riches begin to forsake one even the accumulated stock dwindles away.
- id: '8'
  type: leaf
  paginated: true
  meta:
    hi:
      title: 'अध्याय १ - श्लोक ८'
      subtitle: ''
      image: ''
      description: |-
        जिस देश में आदर-सम्मान नहीं और न ही आजीविका का कोई साधन है, जहां कोई बंधु-बांधव, रिश्तेदार भी नहीं तथा किसी प्रकार की विद्या और गुणों की प्राप्ति की संभावना भी नहीं, ऐसे देश को छोड़ ही देना चाहिए । ऐसे स्थान पर रहना उचित नहीं ।
    en:
      title: 'Chapter 1 - Verse 8'
      subtitle: ''
      image: ''
      description: |-
        Do not inhabit a country where you are not respected, cannot earn your livelihood, have no friends or relatives, or cannot acquire knowledge.
- id: '9'
  type: leaf
  paginated: true
  meta:
    hi:
      title: 'अध्याय १ - श्लोक ९'
      subtitle: ''
      image: ''
      description: |-
        जहां श्रोत्रिय (अर्थात वेद को जानने वाला ब्राह्मण), धनिक, राजा, नदी और वैद्य ये पांच चीजें न हों, उस स्थान पर मनुष्य को एक दिन भी नहीं रहना चाहिए ।
    en:
      title: 'Chapter 1 - Verse 9'
      subtitle: ''
      image: ''
      description: |-
        Do not stay for a single day where there is absense of these five things: a wealthy man, a Brāhmaṇa (well versed in Vedic lore), a king, a river and a physician.
- id: '10'
  type: leaf
  paginated: true
  meta:
    hi:
      title: 'अध्याय १ - श्लोक १०'
      subtitle: ''
      image: ''
      description: |-
        जहां लोकयात्रा अर्थात जीवन को चलाने के लिए आजीविका का कोई साधन न हो, व्यापार आदि विकसित न हो, किसी प्रकार के दंड के मिलने का भय न हो, लोकलाज न हो, व्यक्तियों में शिष्टता, उदारता न हो अर्थात उनमें दान देने की प्रवृत्ति न हो, जहां ये पांच चीजें विद्यमान न हों, वहां व्यक्ति को निवास नहीं करना चाहिए ।
    en:
      title: 'Chapter 1 - Verse 10'
      subtitle: ''
      image: ''
      description: |-
        Wise men should never go into a country where there are no means of earning one's livelihood, where the people have no dread of anybody, have no sense of shame, no intelligence, or a charitable disposition.
- id: '11'
  type: leaf
  paginated: true
  meta:
    hi:
      title: 'अध्याय १ - श्लोक ११'
      subtitle: ''
      image: ''
      description: |-
        काम लेने पर नौकर-चाकरों की, दुख आने पर बंधु-बांधवों की, कष्ट आने पर मित्र की तथा धन नाश होने पर अपनी पत्नी की वास्तविकता का ज्ञान होता है ।
    en:
      title: 'Chapter 1 - Verse 11'
      subtitle: ''
      image: ''
      description: |-
        Test a servant while in the discharge of his duty, a relative in difficulty, a friend in adversity, and a wife in misfortune or on loss of money.
- id: '12'
  type: leaf
  paginated: true
  meta:
    hi:
      title: 'अध्याय १ - श्लोक १२'
      subtitle: ''
      image: ''
      description: |-
        किसी रोग से पीड़ित होने पर, दुख आने पर, अकाल पड़ने पर, शत्रु की ओर से संकट आने पर, राज सभा में, श्मशान अथवा किसी की मृत्यु के समय जो व्यक्ति साथ नहीं छोड़ता, वास्तव में वही सच्चा बन्धु माना जाता है ।
    en:
      title: 'Chapter 1 - Verse 12'
      subtitle: ''
      image: ''
      description: |-
        He is a true friend who does not forsake us in time of need, misfortune, famine, or war, in a king's court, or at the crematorium (shmashaan).
- id: '13'
  type: leaf
  paginated: true
  meta:
    hi:
      title: 'अध्याय १ - श्लोक १३'
      subtitle: ''
      image: ''
      description: |-
        जो मनुष्य निश्चित को छोड़कर अनिश्चित के पीछे भागता है, उसका कार्य या पदार्थ नष्ट हो जाता है ।
    en:
      title: 'Chapter 1 - Verse 13'
      subtitle: ''
      image: ''
      description: |-
        He who gives up what is imperishable for that which is perishable, loses that which is imperishable; and doubtlessly loses that which is perishable also.
- id: '14'
  type: leaf
  paginated: true
  meta:
    hi:
      title: 'अध्याय १ - श्लोक १४'
      subtitle: ''
      image: ''
      description: |-
        बुद्धिमान व्यक्ति को चाहिए कि वह श्रेष्ठ कुल में उत्पन्न हुई कुरूप अर्थात् सौंदर्यहीन कन्या से भी विवाह कर ले, परन्तु नीच कुल में उत्पन्न हुई सुंदर कन्या से विवाह न करे । वैसे विवाह अपने समान कुल में ही करना चाहिए ।
    en:
      title: 'Chapter 1 - Verse 14'
      subtitle: ''
      image: ''
      description: |-
        A wise man should marry a girl born in a respectable family even if she is deformed. He should not marry one of a low-class (uncultured) family, through beauty. Marriage in a family of equal status is preferable.
- id: '15'
  type: leaf
  paginated: true
  meta:
    hi:
      title: 'अध्याय १ - श्लोक १५'
      subtitle: ''
      image: ''
      description: |-
        'नखीनाम्' अर्थात बड़े-बड़े नाखूनों वाले शेर और चीते आदि प्राणियों, विशाल नदियों, 'शृंगीणाम्' अर्थात बड़े-बड़े सींग वाले सांड़ आदि पशुओं, शस्त्र धारण करने वालों, स्त्रियों तथा राजा से संबंधित कुल वाले व्यक्तियों का विश्वास कभी नहीं करना चाहिए ।
    en:
      title: 'Chapter 1 - Verse 15'
      subtitle: ''
      image: ''
      description: |-
        Do not put your trust in beasts with claws or horns, rivers, men who carry weapons, women, and members of a royal family.
- id: '16'
  type: leaf
  paginated: true
  meta:
    hi:
      title: 'अध्याय १ - श्लोक १६'
      subtitle: ''
      image: ''
      description: |-
        विष में भी यदि अमृत हो तो उसे ग्रहण कर लेना चाहिए । अपवित्र और अशुद्ध वस्तुओं में भी यदि सोना अथवा मूल्यवान वस्तु पड़ी हो तो वह भी उठा लेने के योग्य होती है । यदि नीच मनुष्य के पास कोई अच्छी विद्या, कला अथवा गुण है तो उसे सीखने में कोई हानि नहीं । इसी प्रकार दुष्ट कुल में उत्पन्न अच्छे गुणों से युक्त स्त्री रूपी रत्न को ग्रहण कर लेना चाहिए ।
    en:
      title: 'Chapter 1 - Verse 16'
      subtitle: ''
      image: ''
      description: |-
        Even from poison extract nectar, wash and take back gold if it has fallen in filth, receive the highest knowledge from a low born person; so also a girl possessing virtuous qualities even if she be born in a disreputable family.
- id: '17'
  type: leaf
  paginated: true
  meta:
    hi:
      title: 'अध्याय १ - श्लोक १७'
      subtitle: ''
      image: ''
      description: |-
        पुरुषों की अपेक्षा स्त्रियों का आहार (अर्थात भोजन) दोगुना होता है, बुद्धि चौगुनी, साहस छह गुना और कामवासना आठ गुना होती है ।
    en:
      title: 'Chapter 1 - Verse 17'
      subtitle: ''
      image: ''
      description: |-
        Compared to men, women have hunger two-fold, wisdom four-fold, courage six-fold, and eroticism eight-fold.
