- id: '1'
  type: 'leaf'
  paginated: true
  meta:
    hi:
      title: 'अध्याय १४ - श्लोक १'
      subtitle: ''
      image: ''
      description: |-
        भगवान् ने कहा - अब मैं तुमसे समस्त ज्ञानों में सर्वश्रेष्ठ इस परम ज्ञान को पुनः कहूँगा, जिसे जान लेने पर समस्त मुनियों ने परम सिद्धि प्राप्त की है ।
    en:
      title: 'Chapter 14 - Verse 1'
      subtitle: ''
      image: ''
      description: |-
        The Supreme Personality of Godhead said: Again I shall declare to you this supreme wisdom, the best of all knowledge, knowing which all the sages have attained the supreme perfection.
- id: '2'
  type: 'leaf'
  paginated: true
  meta:
    hi:
      title: 'अध्याय १४ - श्लोक २'
      subtitle: ''
      image: ''
      description: |-
        इस ज्ञान में स्थिर होकर मनुष्य मेरी जैसी दिव्य प्रकृति (स्वभाव) को प्राप्त कर सकता है । इस प्रकार स्थित हो जाने पर वह न तो सृष्टि के समय उत्पन्न होता है और न प्रलय के समय विचलित होता है ।
    en:
      title: 'Chapter 14 - Verse 2'
      subtitle: ''
      image: ''
      description: |-
        By becoming fixed in this knowledge, one can attain to the transcendental nature like My own. Thus established, one is not born at the time of creation or disturbed at the time of dissolution.
- id: '3'
  type: 'leaf'
  paginated: true
  meta:
    hi:
      title: 'अध्याय १४ - श्लोक ३'
      subtitle: ''
      image: ''
      description: |-
        हे भरतपुत्र! ब्रह्म नामक समग्र भौतिक वस्तु जन्म का स्त्रोत है और मैं इसी ब्रह्म को गर्भस्थ करता हूँ, जिससे समस्त जीवों का जन्म सम्भव होता है ।
    en:
      title: 'Chapter 14 - Verse 3'
      subtitle: ''
      image: ''
      description: |-
        The total material substance, called Brahman, is the source of birth, and it is that Brahman that I impregnate, making possible the births of all living beings, O son of Bharata.
- id: '4'
  type: 'leaf'
  paginated: true
  meta:
    hi:
      title: 'अध्याय १४ - श्लोक ४'
      subtitle: ''
      image: ''
      description: |-
        हे कुन्तीपुत्र! तुम यह समझ लो कि समस्त प्रकार की जीव-योनियाँ इस भौतिक प्रकृति में जन्म द्वारा सम्भव हैं और मैं उनका बीज-प्रदाता पिता हूँ ।
    en:
      title: 'Chapter 14 - Verse 4'
      subtitle: ''
      image: ''
      description: |-
        It should be understood that all species of life, O son of Kuntī, are made possible by birth in this material nature, and that I am the seed-giving father.
- id: '5'
  type: 'leaf'
  paginated: true
  meta:
    hi:
      title: 'अध्याय १४ - श्लोक ५'
      subtitle: ''
      image: ''
      description: |-
        भौतिक प्रकृति तीन गुणों से युक्त है । ये हैं - सतो, रजो तथा तमोगुण । हे महाबाहु अर्जुन! जब शाश्वत जीव प्रकृति के संसर्ग में आता है, तो वह इन गुणों से बँध जाता है ।
    en:
      title: 'Chapter 14 - Verse 5'
      subtitle: ''
      image: ''
      description: |-
        Material nature consists of three modes – goodness, passion and ignorance. When the eternal living entity comes in contact with nature, O mighty-armed Arjuna, he becomes conditioned by these modes.
- id: '6'
  type: 'leaf'
  paginated: true
  meta:
    hi:
      title: 'अध्याय १४ - श्लोक ६'
      subtitle: ''
      image: ''
      description: |-
        हे निष्पाप! सतोगुण अन्य गुणों की अपेक्षा अधिक शुद्ध होने के कारण प्रकाश प्रदान करने वाला और मनुष्यों को सारे पाप कर्मों से मुक्त करने वाला है । जो लोग इस गुण में स्थित होते हैं, वे सुख तथा ज्ञान के भाव से बँध जाते हैं ।
    en:
      title: 'Chapter 14 - Verse 6'
      subtitle: ''
      image: ''
      description: |-
        O sinless one, the mode of goodness, being purer than the others, is illuminating, and it frees one from all sinful reactions. Those situated in that mode become conditioned by a sense of happiness and knowledge.
- id: '7'
  type: 'leaf'
  paginated: true
  meta:
    hi:
      title: 'अध्याय १४ - श्लोक ७'
      subtitle: ''
      image: ''
      description: |-
        हे कुन्तीपुत्र! रजोगुण की उत्पत्ति असीम आकांक्षाओं तथा तृष्णाओं से होती है और इसी के कारण से यह देहधारी जीव सकाम कर्मों से बँध जाता है ।
    en:
      title: 'Chapter 14 - Verse 7'
      subtitle: ''
      image: ''
      description: |-
        The mode of passion is born of unlimited desires and longings, O son of Kuntī, and because of this the embodied living entity is bound to material fruitive actions.
- id: '8'
  type: 'leaf'
  paginated: true
  meta:
    hi:
      title: 'अध्याय १४ - श्लोक ८'
      subtitle: ''
      image: ''
      description: |-
        हे भरतपुत्र! तुम जान लो कि अज्ञान से उत्पन्न तमोगुण समस्त देहधारी जीवों का मोह है । इस गुण के प्रतिफल पागलपन (प्रमाद), आलस तथा नींद हैं, जो बद्धजीव को बाँधते हैं ।
    en:
      title: 'Chapter 14 - Verse 8'
      subtitle: ''
      image: ''
      description: |-
        O son of Bharata, know that the mode of darkness, born of ignorance, is the delusion of all embodied living entities. The results of this mode are madness, indolence and sleep, which bind the conditioned soul.
- id: '9'
  type: 'leaf'
  paginated: true
  meta:
    hi:
      title: 'अध्याय १४ - श्लोक ९'
      subtitle: ''
      image: ''
      description: |-
        हे भरतपुत्र! सतोगुण मनुष्य को सुख से बाँधता है, रजोगुण सकाम कर्म से बाँधता है और तमोगुण मनुष्य के ज्ञान को ढक कर उसे पागलपन से बाँधता है ।
    en:
      title: 'Chapter 14 - Verse 9'
      subtitle: ''
      image: ''
      description: |-
        O son of Bharata, the mode of goodness conditions one to happiness; passion conditions one to fruitive action; and ignorance, covering one’s knowledge, binds one to madness.
- id: '10'
  type: 'leaf'
  paginated: true
  meta:
    hi:
      title: 'अध्याय १४ - श्लोक १०'
      subtitle: ''
      image: ''
      description: |-
        हे भरतपुत्र! कभी-कभी सतोगुण रजोगुण तथा तमोगुण को परास्त करके प्रधान बन जाता है तो कभी रजोगुण सतो तथा तमोगुणों को परास्त कर देता है और कभी ऐसा होता है कि तमोगुण सतो तथा रजोगुणों को परास्त कर देता है । इस प्रकार श्रेष्ठता के लिए निरन्तर स्पर्धा चलती रहती है ।
    en:
      title: 'Chapter 14 - Verse 10'
      subtitle: ''
      image: ''
      description: |-
        Sometimes the mode of goodness becomes prominent, defeating the modes of passion and ignorance, O son of Bharata. Sometimes the mode of passion defeats goodness and ignorance, and at other times ignorance defeats goodness and passion. In this way there is always competition for supremacy.
- id: '11'
  type: 'leaf'
  paginated: true
  meta:
    hi:
      title: 'अध्याय १४ - श्लोक ११'
      subtitle: ''
      image: ''
      description: |-
        सतोगुण की अभिव्यक्ति को तभी अनुभव किया जा सकता है, जब शरीर के सारे द्वार ज्ञान के प्रकाश से प्रकाशित होते हैं ।
    en:
      title: 'Chapter 14 - Verse 11'
      subtitle: ''
      image: ''
      description: |-
        The manifestation of the mode of goodness can be experienced when all the gates of the body are illuminated by knowledge.
- id: '12'
  type: 'leaf'
  paginated: true
  meta:
    hi:
      title: 'अध्याय १४ - श्लोक १२'
      subtitle: ''
      image: ''
      description: |-
        हे भरतवंशियों में प्रमुख! जब रजोगुण में वृद्धि हो जाती है, तो अत्यधिक आसक्ति, सकाम कर्म, गहन उद्यम तथा अनियन्त्रित इच्छा एवं लालसा के लक्षण प्रकट होते हैं ।
    en:
      title: 'Chapter 14 - Verse 12'
      subtitle: ''
      image: ''
      description: |-
        O chief of the Bhāratas, when there is an increase in the mode of passion the symptoms of great attachment, fruitive activity, intense endeavor, and uncontrollable desire and hankering develop.
- id: '13'
  type: 'leaf'
  paginated: true
  meta:
    hi:
      title: 'अध्याय १४ - श्लोक १३'
      subtitle: ''
      image: ''
      description: |-
        जब तमोगुण में वृद्धि हो जाती है, तो हे कुरुपुत्र! अँधेरा, जड़ता, प्रमत्तता तथा मोह का प्राकट्य होता है ।
    en:
      title: 'Chapter 14 - Verse 13'
      subtitle: ''
      image: ''
      description: |-
        When there is an increase in the mode of ignorance, O son of Kuru, darkness, inertia, madness and illusion are manifested.
- id: '14'
  type: 'leaf'
  paginated: true
  meta:
    hi:
      title: 'अध्याय १४ - श्लोक १४'
      subtitle: ''
      image: ''
      description: |-
        जब कोई सतोगुण में मरता है, तो उसे महर्षियों के विशुद्ध उच्चतर लोकों की प्राप्ति होती है ।
    en:
      title: 'Chapter 14 - Verse 14'
      subtitle: ''
      image: ''
      description: |-
        When one dies in the mode of goodness, he attains to the pure higher planets of the great sages.
- id: '15'
  type: 'leaf'
  paginated: true
  meta:
    hi:
      title: 'अध्याय १४ - श्लोक १५'
      subtitle: ''
      image: ''
      description: |-
        जब कोई रजोगुण में मरता है, तो वह सकाम कर्मियों के बीच में जन्म ग्रहण करता है और जब कोई तमोगुण में मरता है, तो वह पशुयोनि में जन्म धारण करता है ।
    en:
      title: 'Chapter 14 - Verse 15'
      subtitle: ''
      image: ''
      description: |-
        When one dies in the mode of passion, he takes birth among those engaged in fruitive activities; and when one dies in the mode of ignorance, he takes birth in the animal kingdom.
- id: '16'
  type: 'leaf'
  paginated: true
  meta:
    hi:
      title: 'अध्याय १४ - श्लोक १६'
      subtitle: ''
      image: ''
      description: |-
        पुण्यकर्म का फल शुद्ध होता है और सात्त्विक कहलाता है । लेकिन रजोगुण में सम्पन्न कर्म का फल दुख होता है और तमोगुण में किये गये कर्म मूर्खता में प्रतिफलित होते हैं ।
    en:
      title: 'Chapter 14 - Verse 16'
      subtitle: ''
      image: ''
      description: |-
        The result of pious action is pure and is said to be in the mode of goodness. But action done in the mode of passion results in misery, and action performed in the mode of ignorance results in foolishness.
- id: '17'
  type: 'leaf'
  paginated: true
  meta:
    hi:
      title: 'अध्याय १४ - श्लोक १७'
      subtitle: ''
      image: ''
      description: |-
        सतोगुण से वास्तविक ज्ञान उत्पन्न होता है, रजोगुण से लोभ उत्पन्न होता है और तमोगुण से अज्ञान, प्रमाद और मोह उत्पन्न होते हैं ।
    en:
      title: 'Chapter 14 - Verse 17'
      subtitle: ''
      image: ''
      description: |-
        From the mode of goodness, real knowledge develops; from the mode of passion, greed develops; and from the mode of ignorance develop foolishness, madness and illusion.
- id: '18'
  type: 'leaf'
  paginated: true
  meta:
    hi:
      title: 'अध्याय १४ - श्लोक १८'
      subtitle: ''
      image: ''
      description: |-
        सतोगुणी व्यक्ति क्रमशः उच्च लोकों को ऊपर जाते हैं, रजोगुणी इसी पृथ्वीलोक में रह जाते हैं, और जो अत्यन्त गर्हित तमोगुण में स्थित हैं, वे नीचे नरक लोकों को जाते हैं ।‌
    en:
      title: 'Chapter 14 - Verse 18'
      subtitle: ''
      image: ''
      description: |-
        Those situated in the mode of goodness gradually go upward to the higher planets; those in the mode of passion live on the earthly planets; and those in the abominable mode of ignorance go down to the hellish worlds.
- id: '19'
  type: 'leaf'
  paginated: true
  meta:
    hi:
      title: 'अध्याय १४ - श्लोक १९'
      subtitle: ''
      image: ''
      description: |-
        जब कोई यह अच्छी तरह जान लेता है कि समस्त कार्यों में प्रकृति के तीनों गुणों के अतिरिक्त अन्य कोई कर्ता नहीं है और जब वह परमेश्वर को जान लेता है, जो इन तीनों गुणों से परे है, तो वह मेरे दिव्य स्वभाव को प्राप्त होता है ।
    en:
      title: 'Chapter 14 - Verse 19'
      subtitle: ''
      image: ''
      description: |-
        When one properly sees that in all activities no other performer is at work than these modes of nature and he knows the Supreme Lord, who is transcendental to all these modes, he attains My spiritual nature.
- id: '20'
  type: 'leaf'
  paginated: true
  meta:
    hi:
      title: 'अध्याय १४ - श्लोक २०'
      subtitle: ''
      image: ''
      description: |-
        जब देहधारी जीव भौतिक शरीर से सम्बद्ध इन तीनों गुणों को लाँघने में समर्थ होता है, तो वह जन्म, मृत्यु, बुढ़ापा तथा उनके कष्टों से मुक्त हो सकता है और इसी जीवन में अमृत का भोग कर सकता है ।
    en:
      title: 'Chapter 14 - Verse 20'
      subtitle: ''
      image: ''
      description: |-
        When the embodied being is able to transcend these three modes associated with the material body, he can become free from birth, death, old age and their distresses and can enjoy nectar even in this life.
- id: '21'
  type: 'leaf'
  paginated: true
  meta:
    hi:
      title: 'अध्याय १४ - श्लोक २१'
      subtitle: ''
      image: ''
      description: |-
        अर्जुन ने पूछा - हे भगवान्! जो इन तीनों गुणों से परे है, वह किन लक्षणों के द्वारा जाना जाता है ? उसका आचरण कैसा होता है ? और वह प्रकृति के गुणों को किस प्रकार लाँघता है ?
    en:
      title: 'Chapter 14 - Verse 21'
      subtitle: ''
      image: ''
      description: |-
        Arjuna inquired: O my dear Lord, by which symptoms is one known who is transcendental to these three modes? What is his behavior? And how does he transcend the modes of nature?
- id: '22-23-24-25'
  type: 'leaf'
  paginated: true
  meta:
    hi:
      title: 'अध्याय १४ - श्लोक २२-२३-२४-२५'
      subtitle: ''
      image: ''
      description: |-
        भगवान् ने कहा - हे पाण्डुपुत्र! जो प्रकाश, आसक्ति तथा मोह के उपस्थित होने पर न तो उनसे घृणा करता है और न लुप्त हो जाने पर उनकी इच्छा करता है, जो भौतिक गुणों की इन समस्त प्रतिक्रियाओं से निश्चल तथा अविचलित रहता है और यह जानकर कि केवल गुण ही क्रियाशील हैं, उदासीन तथा दिव्य बना रहता है, जो अपने आप में स्थित है और सुख तथा दुख को एकसमान मानता है, जो मिट्टी के ढेले, पत्थर एवं स्वर्ण के टुकड़े को समान दृष्टि से देखता है, जो अनुकूल तथा प्रतिकूल के प्रति समान बना रहता है, जो धीर है और प्रशंसा तथा बुराई, मान तथा अपमान में समान भाव से रहता है, जो शत्रु तथा मित्र के साथ समान व्यवहार करता है और जिसने सारे भौतिक कार्यों का परित्याग कर दिया है, ऐसे व्यक्ति को प्रकृति के गुणों से अतीत कहते हैं ।
    en:
      title: 'Chapter 14 - Verse 22-23-24-25'
      subtitle: ''
      image: ''
      description: |-
        The Supreme Personality of Godhead said: O son of Pāṇḍu, he who does not hate illumination, attachment and delusion when they are present or long for them when they disappear; who is unwavering and undisturbed through all these reactions of the material qualities, remaining neutral and transcendental, knowing that the modes alone are active; who is situated in the self and regards alike happiness and distress; who looks upon a lump of earth, a stone and a piece of gold with an equal eye; who is equal toward the desirable and the undesirable; who is steady, situated equally well in praise and blame, honor and dishonor; who treats alike both friend and enemy; and who has renounced all material activities – such a person is said to have transcended the modes of nature.
- id: '26'
  type: 'leaf'
  paginated: true
  meta:
    hi:
      title: 'अध्याय १४ - श्लोक २६'
      subtitle: ''
      image: ''
      description: |-
        जो समस्त परिस्थितियों में अविचलित भाव से पूर्ण भक्ति में प्रवृत्त होता है, वह तुरन्त ही प्रकृति के गुणों को लाँघ जाता है और इस प्रकार ब्रह्म के स्तर तक पहुँच जाता है ।
    en:
      title: 'Chapter 14 - Verse 26'
      subtitle: ''
      image: ''
      description: |-
        One who engages in full devotional service, unfailing in all circumstances, at once transcends the modes of material nature and thus comes to the level of Brahman.
- id: '27'
  type: 'leaf'
  paginated: true
  meta:
    hi:
      title: 'अध्याय १४ - श्लोक २७'
      subtitle: ''
      image: ''
      description: |-
        और मैं ही उस निराकार ब्रह्म का आश्रय हूँ, जो अमर्त्य, अविनाशी तथा शाश्वत है और चरम सुख का स्वाभाविक पद है ।
    en:
      title: 'Chapter 14 - Verse 27'
      subtitle: ''
      image: ''
      description: |-
        And I am the basis of the impersonal Brahman, which is immortal, imperishable and eternal and is the constitutional position of ultimate happiness.
