- id: '1'
  type: leaf
  paginated: true
  meta:
    hi:
      title: 'अध्याय ३ - श्लोक १'
      subtitle: ''
      image: ''
      description: |-
        संसार में ऐसा कौन-सा कुल अथवा वंश है, जिसमें कोई-न-कोई दोष अथवा अवगुण न हो, प्रत्येक व्यक्ति को किसी-न-किसी रोग का सामना करना ही पड़ता है, ऐसा मनुष्य कौन-सा है, जो व्यसनों में न पड़ा हो और कौन ऐसा है जो सदा ही सुखी रहता हो, क्योंकि प्रत्येक के जीवन में संकट तो आते ही हैं ।
    en:
      title: 'Chapter 3 - Verse 1'
      subtitle: ''
      image: ''
      description: |-
        In this world, whose family is there without blemish? Who is free from sickness and grief? Who is forever happy?
- id: '2'
  type: leaf
  paginated: true
  meta:
    hi:
      title: 'अध्याय ३ - श्लोक २'
      subtitle: ''
      image: ''
      description: |-
        मनुष्य के व्यवहार से उसके कुल का ज्ञान होता है । मनुष्य की बोल-चाल से इस बात का पता चलता है कि वह कहां का रहने वाला है, वह जिस प्रकार का मान-सम्मान किसी को देता है, उससे उसका प्रेम प्रकट होता है और उसके शरीर को देखकर उसके भोजन की मात्रा का अनुमान लगाया जा सकता है ।
    en:
      title: 'Chapter 3 - Verse 2'
      subtitle: ''
      image: ''
      description: |-
        A man's descent may be discerned by - his conduct, his country by his pronunciation of language, his friendship by his warmth and glow, and his capacity to eat by his body.
- id: '3'
  type: leaf
  paginated: true
  meta:
    hi:
      title: 'अध्याय ३ - श्लोक ३'
      subtitle: ''
      image: ''
      description: |-
        समझदार व्यक्ति का कर्तव्य है कि वह अपनी कन्या का विवाह किसी अच्छे कल में करे, पुत्र को अच्छी शिक्षा दे । उसे इस प्रकार की शिक्षा दे, जिससे उसका मान-सम्मान बढ़े । शत्रु को किसी ऐसे व्यसन में डाल दे, जिससे उसका बाहर निकलना कठिन हो जाए और अपने मित्र को धर्म के मार्ग में लगाए ।
    en:
      title: 'Chapter 3 - Verse 3'
      subtitle: ''
      image: ''
      description: |-
        Give your daughter in marriage to a good family, engage your son in learning, see that your enemy comes to grief, and engage your friends in dharma. (Krsna consciousness).
- id: '4'
  type: leaf
  paginated: true
  meta:
    hi:
      title: 'अध्याय ३ - श्लोक ४'
      subtitle: ''
      image: ''
      description: |-
        दुष्ट व्यक्ति और सांप, इन दोनों में से किसी एक को चुनना हो तो दुष्ट व्यक्ति की अपेक्षा सांप को चुनना ठीक होगा, क्योंकि सांप समय आने पर ही काटेगा, जबकि दुष्ट व्यक्ति हर समय हानि पहुंचाता रहेगा ।
    en:
      title: 'Chapter 3 - Verse 4'
      subtitle: ''
      image: ''
      description: |-
        Of a rascal and a serpent, the serpent is the better of the two, for he strikes only at the time he is destined to kill, while the former at every step.
- id: '5'
  type: leaf
  paginated: true
  meta:
    hi:
      title: 'अध्याय ३ - श्लोक ५'
      subtitle: ''
      image: ''
      description: |-
        राजा लोग कुलीन व्यक्तियों को अपने पास इसलिए रखते हैं कि वे राजा की उन्नति के समय, उसका ऐश्वर्य समाप्त हो जाने पर तथा विपत्ति के समय भी उसे नहीं छोड़ते ।
    en:
      title: 'Chapter 3 - Verse 5'
      subtitle: ''
      image: ''
      description: |-
        Therefore kings gather round themselves men of good families, for they never forsake them either at the beginning, the middle or the end.
- id: '6'
  type: leaf
  paginated: true
  meta:
    hi:
      title: 'अध्याय ३ - श्लोक ६'
      subtitle: ''
      image: ''
      description: |-
        समुद्र भी प्रलय की स्थिति में अपनी मर्यादा का उल्लंघन कर देते हैं और किनारों को लांघकर सारे प्रदेश में फैल जाते हैं, परंतु सज्जन व्यक्ति प्रलय के समान भयंकर विपत्ति और कष्ट आने पर भी अपनी सीमा में ही रहते हैं, अपनी मर्यादा नहीं छोड़ते ।
    en:
      title: 'Chapter 3 - Verse 6'
      subtitle: ''
      image: ''
      description: |-
        At the time of the pralaya (universal destruction) the oceans are to exceed their limits and seek to change, but a saintly man never changes.
- id: '7'
  type: leaf
  paginated: true
  meta:
    hi:
      title: 'अध्याय ३ - श्लोक ७'
      subtitle: ''
      image: ''
      description: |-
        मूर्ख व्यक्ति से दूर ही रहना चाहिए, क्योंकि मनुष्य दिखता हुआ भी वह दो पैरों वाले पशु के समान है । वह सज्जनों को उसी प्रकार कष्ट पहुंचाता रहता है, जैसे शरीर में चुभा हुआ कांटा शरीर को निरंतर पीड़ा देता रहता है ।
    en:
      title: 'Chapter 3 - Verse 7'
      subtitle: ''
      image: ''
      description: |-
        Do not keep company with a fool for as we can see he is a two-legged beast. Like an unseen thorn he pierces the heart with his sharp words.
- id: '8'
  type: leaf
  paginated: true
  meta:
    hi:
      title: 'अध्याय ३ - श्लोक ८'
      subtitle: ''
      image: ''
      description: |-
        सुंदर रूप वाला, यौवन से युक्त, ऊंचे कुल में उत्पन्न होने पर भी विद्या से हीन मनुष्य सुगंधरहित ढाक अथवा टेसू के फूल की भांति उपेक्षित रहता है, प्रशंसा को प्राप्त नहीं होता ।
    en:
      title: 'Chapter 3 - Verse 8'
      subtitle: ''
      image: ''
      description: |-
        Though men be endowed with beauty and youth and born in noble families, yet without education they are like the palasa flower which is void of sweet fragrance.
- id: '9'
  type: leaf
  paginated: true
  meta:
    hi:
      title: 'अध्याय ३ - श्लोक ९'
      subtitle: ''
      image: ''
      description: |-
        कोयल का सौंदर्य उसके स्वर में है, उसकी मीठी आवाज में है, स्त्रियों का सौंदर्य उनका पतिव्रता होना है, कुरूप लोगों का सौंदर्य उनके विद्यावान होने में और तपस्वियों की सुंदरता उनके क्षमावान होने में है ।
    en:
      title: 'Chapter 3 - Verse 9'
      subtitle: ''
      image: ''
      description: |-
        The beauty of a cuckoo is in its notes, that of a woman in her unalloyed devotion to her husband, that of an ugly person in his scholarship, and that of an ascetic in his forgiveness.
- id: '10'
  type: leaf
  paginated: true
  meta:
    hi:
      title: 'अध्याय ३ - श्लोक १०'
      subtitle: ''
      image: ''
      description: |-
        यदि एक व्यक्ति का त्याग करने से कुल की रक्षा होती है, उन्नति होती है, सुख-शांति मिलती है तो उस एक व्यक्ति को छोड़ देना चाहिए, उसका त्याग कर देना चाहिए । ग्राम के हित के लिए कुल छोड़ देना चाहिए । यदि एक गांव को छोड़ने से पूरे जिले का कल्याण हो, तो उस गांव को भी छोड़ देना चाहिए । इसी प्रकार आत्मा की उन्नति के लिए सारे भूमंडल का ही त्याग कर देना चाहिए ।
    en:
      title: 'Chapter 3 - Verse 10'
      subtitle: ''
      image: ''
      description: |-
        Give up a member to save a family, a family to save a village, a village to save a country, and the country to save yourself.
- id: '11'
  type: leaf
  paginated: true
  meta:
    hi:
      title: 'अध्याय ३ - श्लोक ११'
      subtitle: ''
      image: ''
      description: |-
        उद्योग अर्थात पुरुषार्थ करने वाला व्यक्ति दरिद्र नहीं हो सकता, प्रभु का नाम जपते रहने से मनुष्य पाप में लिप्त नहीं होता, मौन रहने पर लड़ाई-झगड़े नहीं होते तथा जो व्यक्ति जागता रहता है अर्थात सतर्क रहता है, उसे किसी प्रकार का भय नहीं रहता ।
    en:
      title: 'Chapter 3 - Verse 11'
      subtitle: ''
      image: ''
      description: |-
        There is no poverty for the industrious. Sin does not attach itself to the person practicing japa (chanting of the holy names of the Lord). Those who are absorbed in maunam (silent contemplation of the Lord) have no quarrel with others. They are fearless who remain always alert.
- id: '12'
  type: leaf
  paginated: true
  meta:
    hi:
      title: 'अध्याय ३ - श्लोक १२'
      subtitle: ''
      image: ''
      description: |-
        अत्यंत रूपवती होने के कारण ही सीता का अपहरण हुआ, अधिक अभिमान होने के कारण रावण मारा गया, अत्यधिक दान देने के कारण राजा बलि को कष्ट उठाना पड़ा, इसलिए किसी भी कार्य में अति नहीं करनी चाहिए । अति का सर्वत्र त्याग कर देना चाहिए ।
    en:
      title: 'Chapter 3 - Verse 12'
      subtitle: ''
      image: ''
      description: |-
        Devi Seeta was abducted by Ravana the Demon King, because of her being extremely beautiful, and  Ravana did this  being extremely proud of his power.   Due to his extremely charitable nature the Demon King Bali also had his downfall from his kingdom.  Therefore, we should always give up the habit of going to the extreme in any case or a situation.
- id: '13'
  type: leaf
  paginated: true
  meta:
    hi:
      title: 'अध्याय ३ - श्लोक १३'
      subtitle: ''
      image: ''
      description: |-
        समर्थ अथवा शक्तिशाली लोगों के लिए कोई भी कार्य कठिन नहीं होता, व्यापारियों के लिए भी कोई स्थान दूर नहीं, पढ़े-लिखे विद्वान व्यक्तियों के लिए कोई भी स्थान विदेश नहीं । इसी प्रकार जो मधुरभाषी है, उनके लिए कोई पराया नहीं ।
    en:
      title: 'Chapter 3 - Verse 13'
      subtitle: ''
      image: ''
      description: |-
        What is too heavy for the strong and what place is too distant for those who put forth effort? What country is foreign to a man of true learning? Who can be inimical to one who speaks pleasingly?
- id: '14'
  type: leaf
  paginated: true
  meta:
    hi:
      title: 'अध्याय ३ - श्लोक १४'
      subtitle: ''
      image: ''
      description: |-
        जिस प्रकार सुगंधित फूलों से लदा हुआ एक ही वृक्ष सारे जंगल को सुगंध से भर देता है, उसी प्रकार सुपुत्र से सारे वंश की शोभा बढ़ती है, प्रशंसा होती है ।
    en:
      title: 'Chapter 3 - Verse 14'
      subtitle: ''
      image: ''
      description: |-
        As a whole forest becomes fragrant by the existence of a single tree with sweet-smelling blossoms in it, so a family becomes famous by the birth of a virtuous son.
- id: '15'
  type: leaf
  paginated: true
  meta:
    hi:
      title: 'अध्याय ३ - श्लोक १५'
      subtitle: ''
      image: ''
      description: |-
        जिस प्रकार एक ही सूखे वक्ष में आग लगने से सारा जंगल जलकर राख हो जाता है, उसी प्रकार एक मूर्ख और कुपुत्र सारे कुल को नष्ट कर देता है ।
    en:
      title: 'Chapter 3 - Verse 15'
      subtitle: ''
      image: ''
      description: |-
        As a single withered tree, if set aflame, causes a whole forest to burn, so does a rascal son destroy a whole family.
- id: '16'
  type: leaf
  paginated: true
  meta:
    hi:
      title: 'अध्याय ३ - श्लोक १६'
      subtitle: ''
      image: ''
      description: |-
        एक ही पुत्र यदि विद्वान और अच्छे स्वभाव वाला हो तो उससे परिवार को उसी प्रकार खुशी होती है, जिस प्रकार एक चंद्रमा के उत्पन्न होने पर काली रात चांदनी से खिल उठती है ।
    en:
      title: 'Chapter 3 - Verse 16'
      subtitle: ''
      image: ''
      description: |-
        As night looks delightful when the moon shines, so is a family gladdened by even one learned and virtuous son.
- id: '17'
  type: leaf
  paginated: true
  meta:
    hi:
      title: 'अध्याय ३ - श्लोक १७'
      subtitle: ''
      image: ''
      description: |-
        दुख देने वाले, हृदय को जलाने वाले बहुत से पुत्रों के उत्पन्न होने से क्या लाभ ? कुल को सहारा देने वाला एक ही पुत्र श्रेष्ठ होता है, उसके आश्रय में पूरा कुल सुख भोगता है ।
    en:
      title: 'Chapter 3 - Verse 17'
      subtitle: ''
      image: ''
      description: |-
        What is the use of having many sons if they cause grief and vexation? It is better to have only one son from whom the whole family can derive support and peacefulness.
- id: '18'
  type: leaf
  paginated: true
  meta:
    hi:
      title: 'अध्याय ३ - श्लोक १८'
      subtitle: ''
      image: ''
      description: |-
        पांच वर्ष की आयु तक पुत्र से प्यार करना चाहिए, इसके बाद दस वर्ष तक उसकी ताड़ना की जा सकती है और उसे दंड दिया जा सकता है, परंतु सोलह वर्ष की आयु में पहुंचने पर उससे मित्र के समान व्यवहार करना चाहिए ।
    en:
      title: 'Chapter 3 - Verse 18'
      subtitle: ''
      image: ''
      description: |-
        Fondle a son until he is five years of age, and use the stick for another ten years, but when he has attained his sixteenth year treat him as a friend.
- id: '19'
  type: leaf
  paginated: true
  meta:
    hi:
      title: 'अध्याय ३ - श्लोक १९'
      subtitle: ''
      image: ''
      description: |-
        प्राकृतिक आपत्तियां-जैसे अधिक वर्षा होना और सूखा पडना अथवा दंगे-फसाद आदि होने पर, महामारी के रूप में रोग फैलने, शत्रु के आक्रमण करने पर, भयंकर अकाल पड़ने पर और नीच लोगों का साथ होने पर जो व्यक्ति सब कुछ छोड़-छाड़कर भाग जाता है, वह मौत के मुंह में जाने से बच जाता है ।
    en:
      title: 'Chapter 3 - Verse 19'
      subtitle: ''
      image: ''
      description: |-
        He who runs away from a fearful calamity, a foreign invasion, a terrible famine, and the companionship of wicked men is safe.
- id: '20'
  type: leaf
  paginated: true
  meta:
    hi:
      title: 'अध्याय ३ - श्लोक २०'
      subtitle: ''
      image: ''
      description: |-
        जिस व्यक्ति के पास धर्म, अर्थ, काम और मोक्ष आदि इन चार पुरुषार्थों में से कोई भी पुरुषार्थ नहीं है, वह बार-बार मनुष्य योनि में जन्म लेकर केवल मरता ही रहता है, इसके अतिरिक्त उसे कोई लाभ नहीं होता ।
    en:
      title: 'Chapter 3 - Verse 20'
      subtitle: ''
      image: ''
      description: |-
        He who has not acquired one of the following: religious merit (dharma), wealth (artha), satisfaction of desires (kama), or liberation (moksa) is repeatedly born to die.
- id: '21'
  type: leaf
  paginated: true
  meta:
    hi:
      title: 'अध्याय ३ - श्लोक २१'
      subtitle: ''
      image: ''
      description: |-
        जहां मों की पूजा नहीं होती, जहां अन्न आदि काफी मात्रा में इकटठे रहते हैं, जहां पति-पत्नी में किसी प्रकार की कलह, लड़ाई-झगड़ा नहीं, ऐसे स्थान पर लक्ष्मी स्वयं आकर निवास करने लगती है ।
    en:
      title: 'Chapter 3 - Verse 21'
      subtitle: ''
      image: ''
      description: |-
        Lakshmi, the Goddess of wealth, comes of Her own accord where fools are not respected, grain is well stored up, and the husband and wife do not quarrel.
