- id: 'hari-stotram'
  type: 'leaf'
  paginated: false
  meta:
    hi:
      title: 'श्री हरि स्तोत्रं'
      subtitle: ''
      image: 'images/hari-stotram-cover-4x3.jpg'
      description: |-
        श्री हरि स्तोत्रम भगवान हरि (विष्णु) की स्तुति में एक भजन है, जो स्वामी ब्रह्मानंद द्वारा रचित है, जो महान तपस्वियों में से एक है ।

        भगवान हरि का यह अष्टक जो कि मुरारी के कंठ की माला के समान है, जो भी इसे सच्चे मन से पढ़ता है वह वैकुण्ठ लोक को प्राप्त होता है । वह दुख, शोक, जन्म-मरण से मुक्त हो जाता है इसमें कोई संदेह नहीं है ।
    en:
      title: 'Shri Hari Stotram'
      subtitle: ''
      image: 'images/hari-stotram-cover-4x3.jpg'
      description: |-
        Sri Hari Stotram is a hymn in the praise of Lord Hari (Vishnu), composed by Swami Brahmananda, one of the great ascetics.

        The one who reads with peace, This octet on Hari, Which is the destroyer of sorrow, Would definitely reach the world of Vishnu, Which is always without sorrow, And he would never undergo sorrow ever.
- id: 'shiv-tandav-stotram'
  type: 'leaf'
  paginated: false
  meta:
    hi:
      title: 'शिव तांडव स्तोत्रं'
      subtitle: ''
      image: 'images/shiv-tandav-cover-4x3.jpg'
      description: |-
        शिव तांडव स्तोत्र लंका के राजा रावण द्वारा रचित सबसे लोकप्रिय शिव स्तोत्र है । वह *नवव्याकरण* (संस्कृत व्याकरण के ९ प्रकार) के विद्वान और भगवान शिव के बहुत बड़े भक्त थे । शिव तांडव स्तोत्र उनकी कई रचनाओं में से एक है ।

        सृष्टि महा-प्रलय के बिंदु पर समाप्त होती है जब अभिव्यक्ति वापस महान शून्य में वापस आ जाती है । यह तब होता है जब शिव अपना प्रसिद्ध ब्रह्मांडीय नृत्य "शिव तांडव" शुरू करते हैं । उनके नृत्य से, विनाशकारी ऊर्जाएँ निकलती हैं और सक्रिय होती हैं जो पूरी सृष्टि को नष्ट कर देती हैं ।

        सायंकाल में पूजा समाप्त होने पर जो रावण के गाये हुए इस शिव तांडव स्तोत्रं का पाठ करता है, भगवान शंकर उस मनुष्य को रथ, हाथी, घोड़ों से युक्त सदा स्थिर रहने वाली संपत्ति प्रदान करते हैं ।
    en:
      title: 'Shiv Tandav Stotram'
      subtitle: ''
      image: 'images/shiv-tandav-cover-4x3.jpg'
      description: |-
        Shiva Tandava Stotram is the most popular Shiva Stotram composed by Ravana, King of Lanka. He was a scholar in *Navavyakarana* (the 9 types of Sanskrit grammar) and a great devotee of Lord Shiva. Shiva Tandav Stotram is one of his many works.

        Creation ends at the point of Maha-Pralaya when manifestation is withdrawn back into the Great Void. This is when Shiva begins his “Shiva Tandav“, his famous cosmic dance. From his dance, the destructive energies are released and activated that dismantle all of the creation.

        He who sings this song composed by the ten-headed one (Ravana), At the end of every worship or, Reads it after worship of Shiva on the Pradosha day, Will get the blessing of Lord Shiva, chariots, elephants and horses, As well as the affectionate sight of the god of wealth.
- id: 'mahishasura-mardini'
  type: 'leaf'
  paginated: false
  meta:
    hi:
      title: 'श्री महिषासुरमर्दिनि स्तोत्रं'
      subtitle: ''
      image: 'images/mahishasur-mardini-cover-4x3.jpg'
      description: |-
        ८१० ईस्वी के आसपास महान ऋषि आदि शंकराचार्य द्वारा रचित, यह स्तोत्रम देवी महात्म्य पर आधारित है और देवी की विभिन्न शक्तियों (शक्तियों) की प्रशंसा करता है । देवी दुर्गा, लक्ष्मी और सरस्वती के विभिन्न रूप लेती हैं और राक्षसों - मधु और कैटभ, महिषासुर, और सुंभ और निशुंभ का वध करती हैं ।

        कहा जाता है कि महिषासुर मर्दिनी स्तोत्रम भक्त को शांति प्रदान करता है और सभी भय और दुखों को दूर करता है । यह संदेह, क्रोध, अहंकार और जड़ता जैसी नकारात्मक भावनाओं को दूर भगाता है । यह स्तोत्रम आस्तिक के मार्ग में आने वाली बाधाओं को भी दूर करता है ।
    en:
      title: 'Shri Mahishasur Mardini Stotram'
      subtitle: ''
      image: 'images/mahishasur-mardini-cover-4x3.jpg'
      description: |-
        Composed by the great sage Adi Shankaracharya around 810 AD, this stotram  is based on the Devi Mahatmyam and extols the different powers (shaktis) of the Devi. The Devi takes different forms of Durga, Lakshmi and Saraswati and destroys the demons - Madhu and Kaitabha, Mahishasura, and Sumbha and Nisumbha.

        Mahishasura Mardini Stotram is said to bring peace to the devotee and removes all fear and sadness. It drives away negative emotions like doubt, anger, ego and inertia. This stotram also removes obstacles from the path of the believer.
- id: 'saraswati-stotram'
  type: 'leaf'
  paginated: false
  meta:
    hi:
      title: 'सरस्वती स्तोत्रं'
      subtitle: ''
      image: 'images/saraswati-stotram-cover-4x3.jpg'
      description: ''
    en:
      title: 'Saraswati Stotram'
      subtitle: ''
      image: 'images/saraswati-stotram-cover-4x3.jpg'
      description: ''
- id: 'vishnu-shodasa-nama-stotram'
  type: 'leaf'
  paginated: false
  meta:
    hi:
      title: 'श्री विष्णु षोडश नाम स्तोत्रं'
      subtitle: ''
      image: 'images/vishnu-shodasa-nama-stotram-cover-4x3.jpg'
      description: 'श्री विष्णु जी के सोलह नाम'
    en:
      title: 'Shri Vishnu Shodash Naam Stotram'
      subtitle: ''
      image: 'images/vishnu-shodasa-nama-stotram-cover-4x3.jpg'
      description: '16 names of Shri Vishnu'