- id: 'hari-stotram'
  type: 'leaf'
  paginated: false
  meta:
    hi:
      title: 'श्री हरि स्तोत्रं'
      subtitle: ''
      image: ''
      description: ''
    en:
      title: 'Shri Hari Stotram'
      subtitle: ''
      image: ''
      description: ''
- id: 'shiv-tandav-stotram'
  type: 'leaf'
  paginated: false
  meta:
    hi:
      title: 'शिव तांडव स्तोत्रं'
      subtitle: ''
      image: ''
      description: ''
    en:
      title: 'Shiv Tandav Stotram'
      subtitle: ''
      image: ''
      description: ''
