- id: 'a'
  type: 'leaf'
  paginated: true
  meta:
    hi:
      title: 'निवेदन'
      subtitle: ''
      image: ''
      description: ''
    en:
      title: 'Publisher''s Note'
      subtitle: ''
      image: ''
      description: ''
- id: 'b'
  type: 'leaf'
  paginated: true
  meta:
    hi:
      title: 'गोस्वामी तुलसीदासजी की संक्षिप्त जीवनी'
      subtitle: ''
      image: ''
      description: ''
    en:
      title: 'Procedure of Reciting the Rāmacaritamānasa'
      subtitle: ''
      image: ''
      description: ''
- id: '1'
  type: 'tree'
  paginated: false
  meta:
    hi:
      title: '१ - बालकाण्ड'
      subtitle: ''
      image: ''
      description: 'बालकाण्ड में प्रभु राम के जन्म से लेकर राम-विवाह तक के घटनाक्रम आते हैं ।'
    en:
      title: '1 - Baal Kaand'
      subtitle: ''
      image: ''
      description: |
        This chapter (Bāl Kāṇḍ) begins with extensive invocations to various Gods and Goddesses. Events leading to the descent of the incarnation of Rām are described. These include, among other tales, the story of Śivā and Pārvatī. The chapter then describes the birth of Rām in Ayodhyā, his childhood, the protection of the sage Viśvāmitra's yajna, entry into Janakpur, breaking of Lord Śivā's bow, marriage to Sītā and return to Ayodhyā.
- id: '2'
  type: 'tree'
  paginated: false
  meta:
    hi:
      title: '२ - अयोध्याकाण्ड'
      subtitle: ''
      image: ''
      description: 'अयोध्याकांड में श्रीराम वनगमन से लेकर श्रीराम-भरत मिलाप तक के घटनाक्रम आते हैं ।'
    en:
      title: '2 - Ayodhya Kaand'
      subtitle: ''
      image: ''
      description: |
        This chapter (Ayodhā Kāṇḍ) begins with the preparations for Rām's coronation in Ayodhyā. Other events described in this chapter are the exile of Rām, Daśaratha's death, Rām's encounter with Niṣāda and the Kevata (boatman), the return of Bharata to Ayodhyā and his anger at his mother's scheming, the meeting of Bharata and Rām in the forest and the installation of Rām's padukās (sandals) on the throne of Ayodhyā with Bharata as regent.
- id: '3'
  type: 'tree'
  paginated: false
  meta:
    hi:
      title: '३ - अरण्यकाण्ड'
      subtitle: ''
      image: ''
      description: 'अरण्यकाण्ड में शूर्पणखा वध से सीता हरण प्रकरण तक के घटनाक्रम आते हैं ।'
    en:
      title: '3 - Aranya Kaand'
      subtitle: ''
      image: ''
      description: |
        This chapter (Araṇya Kāṇḍa) describes Rām's life in the forest with Sītā and Lakṣmaṇa, and his meeting with various sages (Atri, Anasūyā, Agastya) who dwell there. The meeting with Śūrpaṇakhā, Rāvaṇa's sister and her humiliation, battle with the demons Khara and Dūṣana, Rāvaṇa's scheme for revenge, Marīci's impersonation of a golden deer and the abduction of Sītā, Rām's grief and the beginning of the search for Sītā.
- id: '4'
  type: 'tree'
  paginated: false
  meta:
    hi:
      title: '४ - किष्किन्धाकाण्ड'
      subtitle: ''
      image: ''
      description: 'किष्किंधाकाण्ड में हनुमान मिलन से बालि वध व सीता खोज की तैयारी तक के घटनाक्रम आते हैं ।'
    en:
      title: '4 - Kishkindha Kaand'
      subtitle: ''
      image: ''
      description: |
        This chapter (Kiṣkindhā Kāṇḍa) describes the meeting of Hanumān and Rām, Rām's friendship with Sugrīva, the slaying of Bāli and the beginning of the search for Sītā by Sugrīva's army.
- id: '5'
  type: 'tree'
  paginated: false
  meta:
    hi:
      title: '५ - सुन्दरकाण्ड'
      subtitle: ''
      image: ''
      description: 'सुंदरकाण्ड में हनुमान का लंका प्रस्थान, लंका दहन से लंका से वापसी तक के घटनाक्रम आते हैं ।'
    en:
      title: '5 - Sundar Kaand'
      subtitle: ''
      image: ''
      description: |
        This chapter (Sundara Kāṇḍa) describes the exploits of Hanumān: his crossing over the ocean, entry into Laṅkā, his meeting with Vibhīṣaṇa, his discovery of, and meeting with, Sītā and his burning of Laṅkā. Other episodes described in this chapter are the defection of Vibhīṣaṇa, the exchange of messages between Rām and Rāvaṇa and Rām's taming of the ocean.
- id: '6'
  type: 'tree'
  paginated: false
  meta:
    hi:
      title: '६ - लंकाकाणड'
      subtitle: ''
      image: ''
      description: 'लंकाकाण्ड में पुल निर्माण से राम-रावण युद्ध व अयोध्या वापसी तक के घटनाक्रम आते हैं ।'
    en:
      title: '6 - Lanka Kaand'
      subtitle: ''
      image: ''
      description: |
        This chapter (Laṅkā Kāṇaḍa) describes the whole period of Rām's stay in Laṅkā, the island kingdom of Rāvaṇa. The episodes include the building of a bridge on the ocean and crossing over into Laṅkā and Angada's fruitless peace mission to Rāvaṇa. Then follows the battle with the fall of various heroes, Lakṣmaṇa's injury and recovery and finally the slaying of Rāvaṇa. The battle is followed by the crowning of Vibhīṣaṇa as king of Laṅkā, the return of Sītā and the journey back to Ayodhyā.
- id: '7'
  type: 'tree'
  paginated: false
  meta:
    hi:
      title: '७ - उत्तरकाण्ड'
      subtitle: ''
      image: ''
      description: 'उत्तरकाण्ड में राज्याभिषेक से काकभुशुण्डि तक के घटनाक्रम आते हैं ।'
    en:
      title: '7 - Uttar Kaand'
      subtitle: ''
      image: ''
      description: |
        This chapter (Uttara Kāṇḍa) describes of events occurring after the battle of Laṅkā. Major events are the end of Rām's exile and his return to Ayodhyā, crowning of Rām as king of Ayodhyā and the description of his exemplary governance (Rāmrājya). This is followed by details of the departure of the incarnation of Lord Rām, the dialogue between Garuḍa and Kākabhuśuṇḍi and the closing invocation of the text.
