- id: '1'
  type: 'leaf'
  paginated: true
  meta:
    hi:
      title: 'अध्याय ७ - श्लोक १'
      subtitle: ''
      image: ''
      description: |-
        श्रीभगवान् ने कहा - हे पृथापुत्र! अब सुनो कि तुम किस तरह मेरी भावना से पूर्ण होकर और मन को मुझमें आसक्त करके योगाभ्यास करते हुए मुझे पूर्णतया संशयरहित जान सकते हो ।
    en:
      title: 'Chapter 7 - Verse 1'
      subtitle: ''
      image: ''
      description: |-
        The Supreme Personality of Godhead said: Now hear, O son of Pṛthā, how by practicing yoga in full consciousness of Me, with mind attached to Me, you can know Me in full, free from doubt.
- id: '2'
  type: 'leaf'
  paginated: true
  meta:
    hi:
      title: 'अध्याय ७ - श्लोक २'
      subtitle: ''
      image: ''
      description: |-
        अब मैं तुमसे पूर्णरूप से व्यावहारिक तथा दिव्यज्ञान कहूँगा । इसे जान लेने पर तुम्हें जानने के लिए और कुछ भी शेष नहीं रहेगा ।
    en:
      title: 'Chapter 7 - Verse 2'
      subtitle: ''
      image: ''
      description: |-
        I shall now declare unto you in full this knowledge, both phenomenal and numinous. This being known, nothing further shall remain for you to know.
- id: '3'
  type: 'leaf'
  paginated: true
  meta:
    hi:
      title: 'अध्याय ७ - श्लोक ३'
      subtitle: ''
      image: ''
      description: |-
        कई हजार मनुष्यों में से कोई एक सिद्धि के लिए प्रयत्नशील होता है और इस तरह सिद्धि प्राप्त करने वालों में से विरला ही कोई एक मुझे वास्तव में जान पाता है ।
    en:
      title: 'Chapter 7 - Verse 3'
      subtitle: ''
      image: ''
      description: |-
        Out of many thousands among men, one may endeavor for perfection, and of those who have achieved perfection, hardly one knows Me in truth.
- id: '4'
  type: 'leaf'
  paginated: true
  meta:
    hi:
      title: 'अध्याय ७ - श्लोक ४'
      subtitle: ''
      image: ''
      description: |-
        पृथ्वी, जल, अग्नि, वायु, आकाश, मन, बुद्धि तथा अहंकार - ये आठ प्रकार से विभक्त मेरी भिन्ना (अपरा) प्रकृतियाँ हैं ।
    en:
      title: 'Chapter 7 - Verse 4'
      subtitle: ''
      image: ''
      description: |-
        Earth, water, fire, air, ether, mind, intelligence and false ego – all together these eight constitute My separated material energies.
- id: '5'
  type: 'leaf'
  paginated: true
  meta:
    hi:
      title: 'अध्याय ७ - श्लोक ५'
      subtitle: ''
      image: ''
      description: |-
        हे महाबाहु अर्जुन! इनके अतिरिक्त मेरी एक अन्य परा शक्ति है जो उन जीवों से युक्त है, जो इस भौतिक अपरा प्रकृति के साधनों का विदोहन कर रहे हैं ।
    en:
      title: 'Chapter 7 - Verse 5'
      subtitle: ''
      image: ''
      description: |-
        Besides these, O mighty-armed Arjuna, there is another, superior energy of Mine, which comprises the living entities who are exploiting the resources of this material, inferior nature.
- id: '6'
  type: 'leaf'
  paginated: true
  meta:
    hi:
      title: 'अध्याय ७ - श्लोक ६'
      subtitle: ''
      image: ''
      description: |-
        सारे प्राणियों का उद्गम इन दोनों शक्तियों में है । इस जगत् में जो कुछ भी भौतिक तथा आध्यात्मिक है, उसकी उत्पत्ति तथा प्रलय मुझे ही जानो ।
    en:
      title: 'Chapter 7 - Verse 6'
      subtitle: ''
      image: ''
      description: |-
        All created beings have their source in these two natures. Of all that is material and all that is spiritual in this world, know for certain that I am both the origin and the dissolution.
- id: '7'
  type: 'leaf'
  paginated: true
  meta:
    hi:
      title: 'अध्याय ७ - श्लोक ७'
      subtitle: ''
      image: ''
      description: |-
        हे धनञ्जय! मुझसे श्रेष्ठ कोई सत्य नहीं है । जिस प्रकार मोती धागे में गुँथे रहते हैं, उसी प्रकार सब कुछ मुझ पर ही आश्रित है ।
    en:
      title: 'Chapter 7 - Verse 7'
      subtitle: ''
      image: ''
      description: |-
        O conqueror of wealth, there is no truth superior to Me. Everything rests upon Me, as pearls are strung on a thread.
- id: '8'
  type: 'leaf'
  paginated: true
  meta:
    hi:
      title: 'अध्याय ७ - श्लोक ८'
      subtitle: ''
      image: ''
      description: |-
        हे कुन्तीपुत्र! मैं जल का स्वाद हूँ, सूर्य तथा चन्द्रमा का प्रकाश हूँ, वैदिक मन्त्रों में ओंकार हूँ, आकाश में ध्वनि हूँ तथा मनुष्य में सामर्थ्य हूँ ।
    en:
      title: 'Chapter 7 - Verse 8'
      subtitle: ''
      image: ''
      description: |-
        O son of Kuntī, I am the taste of water, the light of the sun and the moon, the syllable oṁ in the Vedic mantras; I am the sound in ether and ability in man.
- id: '9'
  type: 'leaf'
  paginated: true
  meta:
    hi:
      title: 'अध्याय ७ - श्लोक ९'
      subtitle: ''
      image: ''
      description: |-
        मैं पृथ्वी की आद्य सुगंध और अग्नि की ऊष्मा हूँ । मैं समस्त जीवों का जीवन तथा तपस्वियों का तप हूँ ।
    en:
      title: 'Chapter 7 - Verse 9'
      subtitle: ''
      image: ''
      description: |-
        I am the original fragrance of the earth, and I am the heat in fire. I am the life of all that lives, and I am the penances of all ascetics.
- id: '10'
  type: 'leaf'
  paginated: true
  meta:
    hi:
      title: 'अध्याय ७ - श्लोक १०'
      subtitle: ''
      image: ''
      description: |-
        हे पृथापुत्र! यह जान लो कि मैं ही समस्त जीवों का आदि बीज हूँ, बुद्धिमानों की बुद्धि तथा समस्त तेजस्वी पुरुषों का तेज हूँ ।
    en:
      title: 'Chapter 7 - Verse 10'
      subtitle: ''
      image: ''
      description: |-
        O son of Pṛthā, know that I am the original seed of all existences, the intelligence of the intelligent, and the prowess of all powerful men.
- id: '11'
  type: 'leaf'
  paginated: true
  meta:
    hi:
      title: 'अध्याय ७ - श्लोक ११'
      subtitle: ''
      image: ''
      description: |-
        मैं बलवानों का कामनाओं तथा इच्छा से रहित बल हूँ । हे भरतश्रेष्ठ (अर्जुन) ! मैं वह काम हूँ, जो धर्म के विरुद्ध नहीं है ।
    en:
      title: 'Chapter 7 - Verse 11'
      subtitle: ''
      image: ''
      description: |-
        I am the strength of the strong, devoid of passion and desire. I am sex life which is not contrary to religious principles, O lord of the Bhāratas [Arjuna].
- id: '12'
  type: 'leaf'
  paginated: true
  meta:
    hi:
      title: 'अध्याय ७ - श्लोक १२'
      subtitle: ''
      image: ''
      description: |-
        तुम जान लो कि मेरी शक्ति द्वारा सारे गुण प्रकट होते हैं, चाहे वे सतोगुण हों, रजोगुण हों या तमोगुण हों । एक प्रकार से मैं सब कुछ हूँ, किन्तु हूँ स्वतन्त्र । मैं प्रकृति के गुणों के अधीन नहीं हूँ, अपितु वे मेरे अधीन हैं ।
    en:
      title: 'Chapter 7 - Verse 12'
      subtitle: ''
      image: ''
      description: |-
        Know that all states of being – be they of goodness, passion or ignorance – are manifested by My energy. I am, in one sense, everything, but I am independent. I am not under the modes of material nature, for they, on the contrary, are within Me.
- id: '13'
  type: 'leaf'
  paginated: true
  meta:
    hi:
      title: 'अध्याय ७ - श्लोक १३'
      subtitle: ''
      image: ''
      description: |-
        तीन गुणों (सतो, रजो तथा तमो) के द्वारा मोहग्रस्त यह सारा संसार मुझ गुणातीत तथा अविनाशी को नहीं जानता ।
    en:
      title: 'Chapter 7 - Verse 13'
      subtitle: ''
      image: ''
      description: |-
        Deluded by the three modes [goodness, passion and ignorance], the whole world does not know Me, who am above the modes and inexhaustible.
- id: '14'
  type: 'leaf'
  paginated: true
  meta:
    hi:
      title: 'अध्याय ७ - श्लोक १४'
      subtitle: ''
      image: ''
      description: |-
        प्रकृति के तीन गुणों वाली इस मेरी दैवी शक्ति को पार कर पाना कठिन है । किन्तु जो मेरे शरणागत हो जाते हैं, वे सरलता से इसे पार कर जाते हैं ।
    en:
      title: 'Chapter 7 - Verse 14'
      subtitle: ''
      image: ''
      description: |-
        This divine energy of Mine, consisting of the three modes of material nature, is difficult to overcome. But those who have surrendered unto Me can easily cross beyond it.
- id: '15'
  type: 'leaf'
  paginated: true
  meta:
    hi:
      title: 'अध्याय ७ - श्लोक १५'
      subtitle: ''
      image: ''
      description: |-
        जो निपट मूर्ख हैं, जो मनुष्यों में अधम हैं, जिनका ज्ञान माया द्वारा हर लिया गया है तथा जो असुरों की नास्तिक प्रकृति को धारण करने वाले हैं, ऐसे दुष्ट मेरी शरण ग्रहण नहीं करते ।
    en:
      title: 'Chapter 7 - Verse 15'
      subtitle: ''
      image: ''
      description: |-
        Those miscreants who are grossly foolish, who are lowest among mankind, whose knowledge is stolen by illusion, and who partake of the atheistic nature of demons do not surrender unto Me.
- id: '16'
  type: 'leaf'
  paginated: true
  meta:
    hi:
      title: 'अध्याय ७ - श्लोक १६'
      subtitle: ''
      image: ''
      description: |-
        हे भरतश्रेष्ठ! चार प्रकार के पुण्यात्मा मेरी सेवा करते हैंआर्त, जिज्ञासु, अर्थार्थी तथा ज्ञानी ।
    en:
      title: 'Chapter 7 - Verse 16'
      subtitle: ''
      image: ''
      description: |-
        O best among the Bhāratas, four kinds of pious men begin to render devotional service unto Me – the distressed, the desirer of wealth, the inquisitive, and he who is searching for knowledge of the Absolute.
- id: '17'
  type: 'leaf'
  paginated: true
  meta:
    hi:
      title: 'अध्याय ७ - श्लोक १७'
      subtitle: ''
      image: ''
      description: |-
        इनमें से जो परमज्ञानी है और शुद्धभक्ति में लगा रहता है वह सर्वश्रेष्ठ है, क्योंकि मैं उसे अत्यन्त प्रिय हूँ और वह मुझे प्रिय है ।
    en:
      title: 'Chapter 7 - Verse 17'
      subtitle: ''
      image: ''
      description: |-
        Of these, the one who is in full knowledge and who is always engaged in pure devotional service is the best. For I am very dear to him, and he is dear to Me.
- id: '18'
  type: 'leaf'
  paginated: true
  meta:
    hi:
      title: 'अध्याय ७ - श्लोक १८'
      subtitle: ''
      image: ''
      description: |-
        निस्सन्देह ये सब उदारचेता व्यक्ति हैं, किन्तु जो मेरे ज्ञान को प्राप्त है, उसे मैं अपने ही समान मानता हूँ । वह मेरी दिव्यसेवा में तत्पर रहकर मुझ सर्वोच्च उद्देश्य को निश्चित रूप से प्राप्त करता है ।
    en:
      title: 'Chapter 7 - Verse 18'
      subtitle: ''
      image: ''
      description: |-
        All these devotees are undoubtedly magnanimous souls, but he who is situated in knowledge of Me I consider to be just like My own self. Being engaged in My transcendental service, he is sure to attain Me, the highest and most perfect goal.
- id: '19'
  type: 'leaf'
  paginated: true
  meta:
    hi:
      title: 'अध्याय ७ - श्लोक १९'
      subtitle: ''
      image: ''
      description: |-
        अनेक जन्म-जन्मान्तर के बाद जिसे सचमुच ज्ञान होता है, वह मुझको समस्त कारणों का कारण जानकर मेरी शरण में आता है । ऐसा महात्मा अत्यन्त दुर्लभ होता है ।
    en:
      title: 'Chapter 7 - Verse 19'
      subtitle: ''
      image: ''
      description: |-
        After many births and deaths, he who is actually in knowledge surrenders unto Me, knowing Me to be the cause of all causes and all that is. Such a great soul is very rare.
- id: '20'
  type: 'leaf'
  paginated: true
  meta:
    hi:
      title: 'अध्याय ७ - श्लोक २०'
      subtitle: ''
      image: ''
      description: |-
        जिनकी बुद्धि भौतिक इच्छाओं द्वारा मारी गई है, वे देवताओं की शरण में जाते हैं और वे अपने-अपने स्वभाव के अनुसार पूजा के विशेष विधि-विधानों का पालन करते हैं ।
    en:
      title: 'Chapter 7 - Verse 20'
      subtitle: ''
      image: ''
      description: |-
        Those whose intelligence has been stolen by material desires surrender unto demigods and follow the particular rules and regulations of worship according to their own natures.
- id: '21'
  type: 'leaf'
  paginated: true
  meta:
    hi:
      title: 'अध्याय ७ - श्लोक २१'
      subtitle: ''
      image: ''
      description: |-
        मैं प्रत्येक जीव के हृदय में परमात्मा स्वरूप स्थित हूँ । जैसे ही कोई किसी देवता की पूजा करने की इच्छा करता है, मैं उसकी श्रद्धा को स्थिर करता हूँ, जिससे वह उसी विशेष देवता की भक्ति कर सके ।
    en:
      title: 'Chapter 7 - Verse 21'
      subtitle: ''
      image: ''
      description: |-
        I am in everyone’s heart as the Supersoul. As soon as one desires to worship some demigod, I make his faith steady so that he can devote himself to that particular deity.
- id: '22'
  type: 'leaf'
  paginated: true
  meta:
    hi:
      title: 'अध्याय ७ - श्लोक २२'
      subtitle: ''
      image: ''
      description: |-
        ऐसी श्रद्धा से समन्वित वह देवता विशेष की पूजा करने का यत्न करता है और अपनी इच्छा की पूर्ति करता है । किन्तु वास्तविकता तो यह है कि ये सारे लाभ केवल मेरे द्वारा प्रदत्त हैं ।
    en:
      title: 'Chapter 7 - Verse 22'
      subtitle: ''
      image: ''
      description: |-
        Endowed with such a faith, he endeavors to worship a particular demigod and obtains his desires. But in actuality these benefits are bestowed by Me alone.
- id: '23'
  type: 'leaf'
  paginated: true
  meta:
    hi:
      title: 'अध्याय ७ - श्लोक २३'
      subtitle: ''
      image: ''
      description: |-
        अल्पबुद्धि वाले व्यक्ति देवताओं की पूजा करते हैं और उन्हें प्राप्त होने वाले फल सीमित तथा क्षणिक होते हैं । देवताओं की पूजा करने वाले देवलोक को जाते हैं, किन्तु मेरे भक्त अन्ततः मेरे परमधाम को प्राप्त होते हैं ।
    en:
      title: 'Chapter 7 - Verse 23'
      subtitle: ''
      image: ''
      description: |-
        Men of small intelligence worship the demigods, and their fruits are limited and temporary. Those who worship the demigods go to the planets of the demigods, but My devotees ultimately reach My supreme planet.
- id: '24'
  type: 'leaf'
  paginated: true
  meta:
    hi:
      title: 'अध्याय ७ - श्लोक २४'
      subtitle: ''
      image: ''
      description: |-
        बुद्धिहीन मनुष्य मुझको ठीक से न जानने के कारण सोचते हैं कि मैं (भगवान् कृष्ण) पहले निराकार था और अब मैंने इस स्वरूप को धारण किया है । वे अपने अल्पज्ञान के कारण मेरी अविनाशी तथा सर्वोच्च प्रकृति को नहीं जान पाते ।
    en:
      title: 'Chapter 7 - Verse 24'
      subtitle: ''
      image: ''
      description: |-
        Unintelligent men, who do not know Me perfectly, think that I, the Supreme Personality of Godhead, Kṛṣṇa, was impersonal before and have now assumed this personality. Due to their small knowledge, they do not know My higher nature, which is imperishable and supreme.
- id: '25'
  type: 'leaf'
  paginated: true
  meta:
    hi:
      title: 'अध्याय ७ - श्लोक २५'
      subtitle: ''
      image: ''
      description: |-
        मैं मूर्खों तथा अल्पज्ञों के लिए कभी भी प्रकट नहीं हूँ । उनके लिए तो मैं अपनी अन्तरंगा शक्ति द्वारा आच्छादित रहता हूँ, अतः वे यह नहीं जान पाते कि मैं अजन्मा तथा अविनाशी हूँ ।
    en:
      title: 'Chapter 7 - Verse 25'
      subtitle: ''
      image: ''
      description: |-
        I am never manifest to the foolish and unintelligent. For them I am covered by My internal potency, and therefore they do not know that I am unborn and infallible.
- id: '26'
  type: 'leaf'
  paginated: true
  meta:
    hi:
      title: 'अध्याय ७ - श्लोक २६'
      subtitle: ''
      image: ''
      description: |-
        हे अर्जुन! श्रीभगवान् होने के नाते मैं जो कुछ भूतकाल में घटित हो चुका है, जो वर्तमान में घटित हो रहा है और जो आगे होने वाला है, वह सब कुछ जानता हूँ । मैं समस्त जीवों को भी जानता हूँ, किन्तु मुझे कोई नहीं जानता ।
    en:
      title: 'Chapter 7 - Verse 26'
      subtitle: ''
      image: ''
      description: |-
        O Arjuna, as the Supreme Personality of Godhead, I know everything that has happened in the past, all that is happening in the present, and all things that are yet to come. I also know all living entities; but Me no one knows.
- id: '27'
  type: 'leaf'
  paginated: true
  meta:
    hi:
      title: 'अध्याय ७ - श्लोक २७'
      subtitle: ''
      image: ''
      description: |-
        हे भरतवंशी! हे शत्रुविजेता! समस्त जीव जन्म लेकर इच्छा तथा घृणा से उत्पन्न द्वन्द्वों से मोहग्रस्त होकर मोह को प्राप्त होते हैं ।
    en:
      title: 'Chapter 7 - Verse 27'
      subtitle: ''
      image: ''
      description: |-
        O scion of Bharata, O conqueror of the foe, all living entities are born into delusion, bewildered by dualities arisen from desire and hate.
- id: '28'
  type: 'leaf'
  paginated: true
  meta:
    hi:
      title: 'अध्याय ७ - श्लोक २८'
      subtitle: ''
      image: ''
      description: |-
        जिन मनुष्यों ने पूर्वजन्मों में तथा इस जन्म में पुण्यकर्म किये हैं और जिनके पापकर्मों का पूर्णतया उच्छेदन हो चुका होता है, वे मोह के द्वन्द्वों से मुक्त हो जाते हैं और वे संकल्पपूर्वक मेरी सेवा में तत्पर होते हैं ।
    en:
      title: 'Chapter 7 - Verse 28'
      subtitle: ''
      image: ''
      description: |-
        Persons who have acted piously in previous lives and in this life and whose sinful actions are completely eradicated are freed from the dualities of delusion, and they engage themselves in My service with determination.
- id: '29'
  type: 'leaf'
  paginated: true
  meta:
    hi:
      title: 'अध्याय ७ - श्लोक २९'
      subtitle: ''
      image: ''
      description: |-
        जो जरा तथा मृत्यु से मुक्ति पाने के लिए यत्नशील रहते हैं, वे बुद्धिमान व्यक्ति मेरी भक्ति की शरण ग्रहण करते हैं । वे वास्तव में ब्रह्म हैं क्योंकि वे दिव्य कर्मों के विषय में पूरी तरह से जानते हैं ।
    en:
      title: 'Chapter 7 - Verse 29'
      subtitle: ''
      image: ''
      description: |-
        Intelligent persons who are endeavoring for liberation from old age and death take refuge in Me in devotional service. They are actually Brahman because they entirely know everything about transcendental activities.
- id: '30'
  type: 'leaf'
  paginated: true
  meta:
    hi:
      title: 'अध्याय ७ - श्लोक ३०'
      subtitle: ''
      image: ''
      description: |-
        जो मुझ परमेश्वर को मेरी पूर्ण चेतना में रहकर मुझे जगत् का, देवताओं का तथा समस्त यज्ञविधियों का नियामक जानते हैं, वे अपनी मृत्यु के समय भी मुझ भगवान् को जान और समझ सकते हैं ।
    en:
      title: 'Chapter 7 - Verse 30'
      subtitle: ''
      image: ''
      description: |-
        Those in full consciousness of Me, who know Me, the Supreme Lord, to be the governing principle of the material manifestation, of the demigods, and of all methods of sacrifice, can understand and know Me, the Supreme Personality of Godhead, even at the time of death.
